
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Amuco Contacts      <small><?= cclang('detail', ['Amuco Contacts']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_contacts'); ?>">Amuco Contacts</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Amuco Contacts</h3>
                     <h5 class="widget-user-desc">Detail Amuco Contacts</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_amuco_contacts" id="form_amuco_contacts" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Type Contact </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->type_contact); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Active </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->active); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Name </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->name); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">First Name </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->first_name); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Last Name </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->last_name); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Position </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->position); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Departament </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->departament); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Mobile Phone </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->mobile_phone); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Office Phone </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->office_phone); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Personal Phone </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->personal_phone); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Fax </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->fax); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->email); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Skype </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->skype); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Line Products </label>

                        <div class="col-sm-8">
                          <?= join_multi_select($amuco_contacts->line_products, 'amuco_industry_type', 'id', 'name'); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Customer Id </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->amuco_customers_name); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Supplier Id </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->amuco_suppliers_name); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Picture </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->picture); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Home Address </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->home_address); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Country </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->amuco_countries_name); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">City </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->city); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Home Phone </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->home_phone); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Birthday </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->birthday); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Additional Information </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_contacts->additional_information); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('amuco_contacts_update', function() use ($amuco_contacts){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit amuco_contacts (Ctrl+e)" href="<?= site_url('administrator/amuco_contacts/edit/'.$amuco_contacts->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Amuco Contacts']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_contacts/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Contacts']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>