
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Amuco_contacts/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('amuco_contacts') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('amuco_contacts') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('amuco_contacts_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('amuco_contacts')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/amuco_contacts/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('amuco_contacts')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('amuco_contacts_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('amuco_contacts') ?> " href="<?= site_url('administrator/amuco_contacts/export?q='.$this->input->get('q').'&f='.$this->input->get('d')); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('amuco_contacts_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('amuco_contacts') ?> " href="<?= site_url('administrator/amuco_contacts/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('amuco_contacts') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('amuco_contacts')]); ?>  <i class="label bg-yellow"><?= $amuco_contacts_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_amuco_contacts" id="form_amuco_contacts" action="<?= base_url('administrator/amuco_contacts/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th data-field="id"data-sort="1" data-primary-key="1"> <?= cclang('id') ?></th>
                           <th data-field="type_contact"data-sort="1" data-primary-key="0"> <?= cclang('type_contact') ?></th>
                           <th data-field="name"data-sort="1" data-primary-key="0"> <?= cclang('name') ?></th>
                           <th data-field="position"data-sort="1" data-primary-key="0"> <?= cclang('position') ?></th>
                           <th data-field="email"data-sort="1" data-primary-key="0"> <?= cclang('email') ?></th>
                           <th data-field="line_products"data-sort="1" data-primary-key="0"> <?= cclang('line_products') ?></th>
                           <th data-field="customer_id"data-sort="1" data-primary-key="0"> <?= cclang('Customer') ?></th>
                           <th data-field="supplier_id"data-sort="1" data-primary-key="0"> <?= cclang('Supplier') ?></th>
                           <th data-field="country"data-sort="1" data-primary-key="0"> <?= cclang('country') ?></th>
                           <th data-field="additional_information"data-sort="1" data-primary-key="0"> <?= cclang('additional_information') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_amuco_contacts">
                     <?php foreach($amuco_contactss as $amuco_contacts): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $amuco_contacts->id; ?>">
                           </td>
                                                       
                           <td><?= _ent($amuco_contacts->id); ?></td> 
                           <td><?= _ent($amuco_contacts->type_contact); ?></td> 
                           <td><?= _ent($amuco_contacts->name); ?></td> 
                           <td><?= _ent($amuco_contacts->position); ?></td> 
                           <td><?= _ent($amuco_contacts->email); ?></td> 
                           <td><?= join_multi_select($amuco_contacts->line_products, 'amuco_industry_type', 'id', 'name'); ?></td> 
                           <td><?php if  ($amuco_contacts->customer_id && $amuco_contacts->type_contact == 'Customer') {

                              echo anchor('administrator/amuco_customers/view/'.$amuco_contacts->customer_id.'?popup=show', $amuco_contacts->amuco_customers_name, ['class' => 'popup-view']); }?> </td>
                             
                           <td><?php if  ($amuco_contacts->supplier_id && $amuco_contacts->type_contact == 'Supplier') {

                              echo anchor('administrator/amuco_suppliers/view/'.$amuco_contacts->supplier_id.'?popup=show', $amuco_contacts->amuco_suppliers_name, ['class' => 'popup-view']); }?> </td>
                             
                           <td><?php 

                              echo  $amuco_contacts->amuco_countries_name ;?> </td>
                             
                           <td><?= _ent($amuco_contacts->additional_information); ?></td> 
                           <td width="200">
                            
                                                              <?php is_allowed('amuco_contacts_view', function() use ($amuco_contacts){?>
                                
                              <a href="<?= site_url('administrator/amuco_contacts/view/' . $amuco_contacts->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('amuco_contacts_update', function() use ($amuco_contacts){?>
                              <a href="<?= site_url('administrator/amuco_contacts/edit/' . $amuco_contacts->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('amuco_contacts_delete', function() use ($amuco_contacts){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/amuco_contacts/delete/' . $amuco_contacts->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($amuco_contacts_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Amuco Contacts data is not available
                           </td>
                         </tr>
                      <?php endif; ?>

                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'id' ? 'selected' :''; ?> value="id">Id</option>
                           <option <?= $this->input->get('f') == 'type_contact' ? 'selected' :''; ?> value="type_contact">Type Contact</option>
                           <option <?= $this->input->get('f') == 'name' ? 'selected' :''; ?> value="name">Name</option>
                           <option <?= $this->input->get('f') == 'position' ? 'selected' :''; ?> value="position">Position</option>
                           <option <?= $this->input->get('f') == 'email' ? 'selected' :''; ?> value="email">Email</option>
                           <option <?= $this->input->get('f') == 'line_products' ? 'selected' :''; ?> value="line_products">Line Products</option>
                           <option <?= $this->input->get('f') == 'customer_id' ? 'selected' :''; ?> value="customer_id">Customer Id</option>
                           <option <?= $this->input->get('f') == 'supplier_id' ? 'selected' :''; ?> value="supplier_id">Supplier Id</option>
                           <option <?= $this->input->get('f') == 'country' ? 'selected' :''; ?> value="country">Country</option>
                           <option <?= $this->input->get('f') == 'additional_information' ? 'selected' :''; ?> value="additional_information">Additional Information</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/amuco_contacts');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_amuco_contacts').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/amuco_contacts/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });
    initSortable('amuco_contacts', $('table.dataTable'));
  }); /*end doc ready*/
</script>