
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Amuco Credit Insurance      <small><?= cclang('detail', ['Amuco Credit Insurance']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_credit_insurance'); ?>">Amuco Credit Insurance</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Amuco Credit Insurance</h3>
                     <h5 class="widget-user-desc">Detail Amuco Credit Insurance</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_amuco_credit_insurance" id="form_amuco_credit_insurance" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Customer Id </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->amuco_customers_name); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Date Updated </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->date_updated); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Date Created </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->date_created); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Raiting </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->raiting); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Credit Ever Denied </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->credit_ever_denied); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Available Credit </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->available_credit); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Insured Credit </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->insured_credit); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Own Risk </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->own_risk); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Highest Ever Insured </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->highest_ever_insured); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Request Increase Status </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->request_increase_status); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Mount Increase </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->mount_increase); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Last Increased Requested </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->last_increased_requested); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Date Last Increased Requested </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_credit_insurance->date_last_increased_requested); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('amuco_credit_insurance_update', function() use ($amuco_credit_insurance){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit amuco_credit_insurance (Ctrl+e)" href="<?= site_url('administrator/amuco_credit_insurance/edit/'.$amuco_credit_insurance->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Amuco Credit Insurance']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_credit_insurance/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Credit Insurance']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>