
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Amuco Visits      <small><?= cclang('detail', ['Amuco Visits']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_visits'); ?>">Amuco Visits</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Amuco Visits</h3>
                     <h5 class="widget-user-desc">Detail Amuco Visits</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_amuco_visits" id="form_amuco_visits" >
                  
                     <div class="form-group " style="display:none">
                           <label for="content" class="col-sm-2 control-label">Id </label>

                           <div class="col-sm-8">
                              <?= _ent($amuco_visits->id); ?>
                           </div>
                     </div>
                     <div class="col-md-6">
                        <div class="box box-widget widget-user-2">
                           <!-- Add the bg color to the header using any of the bg-* classes -->
                           
                              <h3 class="">Details Visit</h3>
                          
                           <div class="box-footer no-padding">
                              <ul class="nav nav-stacked">
                                 <li><label>Date Created </label> <span class="pull-right "> <?= _ent(substr($amuco_visits->date_created,0,10)); ?></span></li>
                                 <li><label>Date Visit </label> <span class="pull-right "> <?= _ent(substr($amuco_visits->date_visit,0,10)); ?></span></li>
                                 <li><label> Visit Type </label><span class="pull-right "><?= _ent($amuco_visits->type_visit); ?></span></li>
                                 <li> <label>Client Type</label> <span class="pull-right "><?= _ent($amuco_visits->type_client); ?></span></li>
                                 <li><label> User</label> <span class="pull-right "><?= _ent($amuco_visits->aauth_users_username); ?></span></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                     <div class="col-md-6">
                        <div class="box box-widget widget-user-2">
                           <!-- Add the bg color to the header using any of the bg-* classes -->
                           
                              <h3 class=""><br></h3>
                      
                           <div class="box-footer no-padding">
                              <ul class="nav nav-stacked">
                                 <?php if($amuco_visits->type_client == 'Customer'):?>
                                 <li><label>Customer </label> <span class="pull-right "> <?= _ent($amuco_visits->amuco_customers_name); ?></span></li>
                                 <?php else:?>
                                 <li><label>Supplier</label>  <span class="pull-right "> <?= _ent($amuco_visits->amuco_suppliers_name); ?></span></li>
<?php endif;?>
                                 <li><label>Date Visit </label> <span class="pull-right "> <?= _ent(substr($amuco_visits->date_visit,0,10)); ?></span></li>
                                 <li><label>Contact </label><span class="pull-right "><?= _ent($amuco_visits->amuco_contacts_name); ?></span></li>
                                 <li><label> Subject</label> <span class="pull-right "><?= _ent($amuco_visits->subject); ?></span></li>
                                 <li><label> Notes </label><span class="pull-right "><?= _ent($amuco_visits->notes); ?></span></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                                          
                     <!--div class="form-group "  >
                           <label for="content" class="col-sm-2 control-label">Date Created </label>

                           <div class="col-sm-8">
                              <?= _ent(substr($amuco_visits->date_created,0,10)); ?>
                           </div>
                     </div>
                                          
                     <div class="form-group "  >
                           <label for="content" class="col-sm-2 control-label">Date Updated </label>

                           <div class="col-sm-8">
                              <?= _ent(substr($amuco_visits->date_updated,0,10)); ?>
                           </div>
                     </div>

                     <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label">Date Visit </label>

                           <div class="col-sm-8">
                              <?= _ent(substr($amuco_visits->date_visit,0,10)); ?>
                           </div>
                     </div>
                                          
                     <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label"> Visit Type </label>

                           <div class="col-sm-8">
                              <?= _ent($amuco_visits->type_visit); ?>
                           </div>
                     </div>
                                          
                     <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label"> Client Type </label>

                           <div class="col-sm-8">
                              <?= _ent($amuco_visits->type_client); ?>
                           </div>
                     </div>
                                          
                     <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label">User Id </label>

                           <div class="col-sm-8">
                              <?= _ent($amuco_visits->aauth_users_username); ?>
                           </div>
                     </div>
                                          
                     <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label">Customer Id </label>

                           <div class="col-sm-8">
                              <?= _ent($amuco_visits->amuco_customers_name); ?>
                           </div>
                     </div>
                                          
                     <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label">Supplier Id </label>

                           <div class="col-sm-8">
                              <?= _ent($amuco_visits->amuco_suppliers_name); ?>
                           </div>
                     </div>
                                          
                     
                                          
                     <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label">Contact Name </label>

                           <div class="col-sm-8">
                              <?= _ent($amuco_visits->amuco_contacts_name); ?>
                           </div>
                     </div>
                                          
                     <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label">Subject </label>

                           <div class="col-sm-8">
                              <?= _ent($amuco_visits->subject); ?>
                           </div>
                     </div>
                                          
                     <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label">Notes </label>

                           <div class="col-sm-8">
                              <?= _ent($amuco_visits->notes); ?>
                           </div>
                     </div-->
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('amuco_visits_update', function() use ($amuco_visits){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit amuco_visits (Ctrl+e)" href="<?= site_url('administrator/amuco_visits/edit/'.$amuco_visits->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Amuco Visits']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_visits/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Visits']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>