<style>
.widget-user-2 .widget-user-header {
    padding: 35px;
}

.input_height {
   height: 25px;
   border-radius: 0px !important;
   text-align: right;
   padding: 1px;
}

.form-group {
    padding-top: 15px;
}

.separador {
  border-top: 1px solid black;
  height: 2px;
  max-width: 200px;
  padding: 0;
  margin: 20px auto 0 auto;
}

#terms {
   padding-top: 0;
   padding-bottom: 0px;
   height: 25px;
   border-radius: 0px !important;
}

#incoterm {
   padding-top: 0;
   padding-bottom: 0px;
   height: 25px;
   border-radius: 0px !important;
}

.input_percentage {
   padding: 0;
   width: 25px;
   text-align: center;
}

.off_padding{
   padding: 0px;
}
table th{
   font-size: 14px;
   text-align: center;
}

table td{
   font-size: 13px;
   text-align: center;
}
.btn-aux{
    background-color:#79be58;
    color:white;
    margin-right:2%;
  }
  .btn-aux:hover{
    background-color:#79be80;
    color:white;
  }
  .btn-aux:focus{
    color:white;
  }
  .disabled {
      pointer-events: none;
      cursor: default;
    }
    .hide_column{
  display:none
}
</style>
<!--link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet"-->
<link href="<?= BASE_ASSET; ?>/admin-lte/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/fixedcolumns/3.2.4/css/fixedColumns.bootstrap4.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/buttons/1.6.3/css/buttons.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/select/1.3.1/css/select.dataTables.min.css" rel="stylesheet">
<!--link href="<?= BASE_ASSET; ?>/css/editor.dataTables.min.css" rel="stylesheet"-->
<script src="<?= BASE_ASSET; ?>/js/cleave.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.3/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>
<!--script src="<?= BASE_ASSET; ?>/js/dataTables.editor.min.js"></script-->

<script src="https://cdn.datatables.net/fixedcolumns/3.2.4/js/dataTables.fixedColumns.min.js"></script>



<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){

   $('.input-number').toArray().forEach(function(field){
      new Cleave(field, {
         numeral: true,
         numeralThousandsGroupStyle: 'thousand'
      });
   });
   
   
   $('.input_percentage').toArray().forEach(function(field){
      new Cleave(field, {
         numeral: true,
         numeralThousandsGroupStyle: 'thousand'
      });
   });
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->

<!-- Main content -->
<section class="content">
   <div class="row">
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body">
               <div class="box box-widget widget-user-2">
                     <!-- Add the bg color to the header using any of the bg-* classes -->
                     <div class="widget-user-header ">
                        <div class="widget-user-image">
                           <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                        </div>
                        <!-- /.widget-user-image -->
                        <h3 class="widget-user-username"><?= cclang('amuco_price_calculator') ?></h3>
                     </div>
                  </div>               
               </div>
               <div class="row" style="margin-top: -30px;">
                  <form id="form_calculator">
                     <div class="col-md-4" style="padding-right: 20px;">
                        <h4 style="margin-left: 10px;">Purchase to Supplier</h4>
                        <div class="row" style="margin-top: -13px;">
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Incoterm</label>
                              <div class="col-sm-5">
                                 <select  class="form-control" name="incoterm" id="incoterm" data-placeholder="Select Incoterm" >
                                       <?php foreach (db_get_all_data('amuco_incoterm') as $row): ?>
                                       <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                       <?php endforeach; ?>  
                                 </select>
                                 <!-- <input type="text" class="form-control input_height" name="incoterm" id="incoterm"> -->
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Quantity</label>
                              <div class="col-sm-5">
                                 <input type="text" class="form-control input_height input-number" name="quantity" id="quantity">
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Price FOB/FCA/Unit</label>
                              <div class="col-sm-5">
                                 <input type="text" class="form-control input_height input-number" name="price_fob_fca_unit" id="price_fob_fca_unit">
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Freight</label>
                              <div class="col-sm-5">
                                 <input type="text" class="form-control input_height input-number" name="freight" id="freight">
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Supp. Overprice</label>
                              <div class="col-sm-5">
                                 <input type="text" class="form-control input_height input-number" name="sup_overprice" id="sup_overprice">
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Purchase Amount</label>
                              <div class="col-sm-5">
                                 <input type="text" class="form-control input_height input-number" name="purchase_amount" id="purchase_amount" readonly>
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Price/Unit</label>
                              <div class="col-sm-5">
                                 <input type="text" class="form-control input_height input-number" name="price_unit" id="price_unit" readonly>
                              </div>
                           </div>
                           <!--div class="form-group">
                              <label for="name" class="col-sm-3 col-sm-offset-8 control-label" style="margin-left: 80%;">Days +</label>
                           </div-->
                           <div class="form-group">
                              <label for="name" class="col-sm-2 col-sm-offset-1 control-label">Terms</label>
                              <div class="col-sm-7">
                                 <select name="terms" id="terms" class="form-control">
                                 <?php foreach (db_get_all_data('amuco_supplier_payment_terms') as $row): ?>
                                       <option value="<?= $row->days ?>"><?= $row->description; ?></option>
                                       <?php endforeach; ?>  
                                 </select>
                                  <input type="hidden" class="form-control input_height" name="payment_customer_select" id="payment_customer_select" value="0"> 
                              </div>
                              <div class="col-sm-2" style="padding-left: 0px;display:none">
                                 <input type="text" class="form-control input_height input-number" name="days" id="days" value="0" style="text-align: center;">
                              </div>
                           </div>
                           <div class="form-group" style="padding-top: 30px;">
                              <div class="col-sm-4 col-sm-offset-4" style="padding-right: 0px;">
                                 <input type="submit" class="btn btn-success" id="btn_calculate" style="border-radius: 0px !important; width: 95px;" value="Calculate" />
                              </div>
                              <div class="col-sm-4">
                              <button type="button" class="btn btn-secondary" id="btn_reset" style="border-radius: 0px !important; width: 95px;">Reset</button>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-md-3" style="border-right: solid 0.5px #80808047 ; border-left: solid 0.5px #80808047;">
                        <h4 style="margin-left: 10px;">Commissions</h4>
                        <?php $pricing_settings = db_get_all_data('amuco_pricing_settings')[0];  ?>
                        <div class="row" style="margin-top: -13px;">
                           <div class="form-group">
                              <label for="name" class="col-sm-7 col-sm-offset-1 control-label">Sales Agent</label>
                              <div class="col-sm-2">
                                 <input type="text" class="form-control input_height input_percentage" name="com_sales_agent" id="com_sales_agent" value="0">
                              </div>
                              <label for="name" class="col-sm-1 control-label" style="padding: 0;">%</label>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-7 col-sm-offset-1 control-label">Purchase Office</label>
                              <div class="col-sm-2">
                                 <input type="text" class="form-control input_height input_percentage" name="com_purchase_office" id="com_purchase_office" value="0">
                              </div>
                              <label for="name" class="col-sm-1 control-label" style="padding: 0;">%</label>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-7 col-sm-offset-1 control-label">Other Supp. Comm</label>
                              <div class="col-sm-2">
                                 <input type="text" class="form-control input_height input_percentage" name="com_other_supp_comm" id="com_other_supp_comm" value="0">
                              </div>
                              <label for="name" class="col-sm-1 control-label" style="padding: 0;">%</label>
                           </div>
                        </div>
                        <div class="row">
                        <hr width="220px;" 
                           size="10" 
                           align="center"> 
                        </div>
                        <h4 style="margin-left: 10px; margin-top: -10px;">Representative</h4>
                        <div class="row" style="margin-top: -13px;">
                           <div class="form-group">
                              <label for="name" class="col-sm-7 col-sm-offset-1 control-label">Commissions</label>
                              <div class="col-sm-2">
                                 <input type="text" class="form-control input_height input_percentage" name="representative_commission" id="representative_commission" value="0">
                              </div>
                              <label for="name" class="col-sm-1 control-label" style="padding: 0;">%</label>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-7 col-sm-offset-1 control-label">Over Price</label>
                              <div class="col-sm-3">
                                 <input style="text-align:center" type="text" class="form-control input_height" name="representative_purchase_office" id="representative_purchase_office" value="0">
                              </div>
                              <!-- <label for="name" class="col-sm-1 control-label" style="padding: 0;">%</label> -->
                           </div>
                        </div>
                        <div class="row">
                        <hr width="220px;" 
                           size="10" 
                           align="center"> 
                        </div>
                        <h4 style="margin-left: 10px; margin-top: -10px;">Price Increase</h4>
                        <div class="row" style="margin-top: -13px;">
                           <div class="form-group">
                              <label for="name" class="col-sm-7 col-sm-offset-1 control-label">Margin</label>
                              <div class="col-sm-2">
                                 <input type="text" class="form-control input_height input_percentage" name="price_increase_commission" id="price_increase_commission" value="6">
                              </div>
                              <label for="name" class="col-sm-1 control-label" style="padding: 0;">%</label>
                           </div>
                        </div>
                     </div>
                     <div class="col-md-4">
                     <h4 style="margin-left: 10px;">Purchase Costs</h4>
                        <div class="row" style="margin-top: -13px;">
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Purchase Amount</label>
                              <div class="col-sm-5 off_padding">
                                 <input type="text" class="form-control input_height input-number" name="costs_purchase_amount" id="costs_purchase_amount" readonly>
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" id="label_financing" class="col-sm-6 col-sm-offset-1 control-label">Financing</label>
                              <div class="col-sm-5 off_padding">
                                 <input type="text" class="form-control input_height input-number" name="financing_prepaid" id="financing_prepaid" readonly>
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Coface</label>
                              <div class="col-sm-5 off_padding">
                                 <input type="text" class="form-control input_height input-number" name="coface" id="coface" readonly>
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Bank Charge</label>
                              <div class="col-sm-5 off_padding">
                                 <input type="text" class="form-control input_height input-number" name="bank_charge" id="bank_charge" readonly>
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Freight Insurance</label>
                              <div class="col-sm-5 off_padding">
                                 <input type="text" class="form-control input_height input-number" name="freight_insurance" id="freight_insurance" readonly>
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Purchase Office Comm.</label>
                              <div class="col-sm-5 off_padding">
                                 <input type="text" class="form-control input_height input-number" name="purchase_office_comm" id="purchase_office_comm" readonly>
                              </div>
                           </div><br><br>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Comm. Other Supplier</label>
                              <div class="col-sm-5 off_padding">
                                 <input type="text" class="form-control input_height input-number" name="comm_other_supplier" id="comm_other_supplier" readonly>
                              </div>
                           </div>
                           <div class="form-group">
                              <label for="name" class="col-sm-6 col-sm-offset-1 control-label">Total Purchase Cost</label>
                              <div class="col-sm-3 off_padding" style="padding-right: 5px;">
                                 <input type="text" class="form-control input_height input-number" name="total_purchase_cost1" id="total_purchase_cost1" readonly>
                              </div>
                              <div class="col-sm-2 off_padding" style="padding-left: 0px;">
                                 <input type="text" class="form-control input_height input-number" name="total_purchase_cost2" id="total_purchase_cost2" readonly>
                              </div>
                           </div>
                        </div>
                     </div>
                  </form>
               </div>
               <hr>
                <div clas="row">    
                  <div class="form-group">
                     <h3 class=" col-sm-6 widget-user-username" style="color: #80808073;">Sale to Customer</h3>
                    
                  </div>
                </div>
                <div class="row" style="margin-top:5%;margin-bottom:1%;margin-left:-1.5%">
                 
                 <div class="col-sm-2" style="margin-left:0.5%">
                   <label class="col-sm-12">Additional days </label>
                 </div> 
                 <div class="col-sm-1"  style="margin-left:-7%" > 
                     <input type="text" class="form-control input_height input-number" name="add_days" id="add_days" value="0" style="text-align: center;">
                 </div>
                
             </div>
             <div clas="row"> 
               <table class="table table-bordered display dataTable" id="sale_customer">
                     <thead>
                         <th>Select</th>
                         <th style="width: 174px;">Payment Terms Customer</th>
                         <th>Calculated Offer Price</th>
                         <th>Offer Price Per Unit</th>
                         <th>Margin (%)</th>
                         <th>Sales Amount</th>
                         <th>Estimated Gross Profit </th>
                         <th>Estimated Commission</th>
                         <th>Rep. Commission</th>
                         <th class="hide_column">Code Payment</th>
                         <th class="hide_column">id</th>
                     </thead>
                     <tbody>
                        
                     </tbody>
               </table>
            </div>
               <hr>
               <div clas="row">    
                  <div class="form-group">
                     <h3 class="widget-user-username" style="color: #80808073; margin-left: 20px;">Payment Terms Select</h3>
                     <button style="margin-right: 2%;margin-top: -3%;" class="btn btn-flat btn-aux pull-right disabled" id="btn_quit_offer" data-stype='stay'  title="<?= cclang('Save'); ?>">
                     <i class="fa fa-save" ></i> <?= cclang('Save Quick Offer'); ?></button>
                  </div>
               </div>
              
               <div class="row ">
                  <table class="table table-bordered display nowrap" id="table_offering_details">
                      <thead>
                      <th style="width: 174px;">Payment Terms Customer</th>
                           <th>Calculated Offer Price</th>
                           <th>Offer Price Per Unit</th>
                           <th>Margin (%)</th>
                           <th>Sales Amount</th>
                           <th>Estimated Gross Profit </th>
                           <th>Estimated Commission</th>
                           <th>Rep. Commission</th>
                           <th>Quantity</th>
                           <th>Actions</th> 
                           <th class="hide_column">Code Payment</th>
                           <th class="hide_column">id</th>
                           <th  class="hide_column">Incoterm</th>
                           <th  class="hide_column">Price FOB</th>
                           <th class="hide_column">Freight</th>
                           <th  class="hide_column" >Supp.Overprice</th>
                           <th class="hide_column">Purchasing Amount </th>
                           <th  class="hide_column">Price/unit</th>
                           <th class="hide_column">Supp. Term</th>
                           <th class="hide_column">Sales Agent</th>
                           <th class="hide_column">Purchasing Office</th>
                           <th class="hide_column">Other Supp.Comm</th>
                           <th class="hide_column">Rep. Comm</th>
                           <th class="hide_column">Rep. Overprice</th>
                           <th class="hide_column">Price Increase</th>
                           <th class="hide_column">Financing</th>
                           <th class="hide_column">Coface</th>
                           <th class="hide_column">Bank Charge</th>
                           <th class="hide_column">freight insurance</th>
                           <th class="hide_column">Purchase Off Comm</th>
                           <th class="hide_column">Comm. Other Supp</th>
                           <th class="hide_column">Total Purchase Cost</th>
                           
                      </thead>
                      <tbody>
                  
                      </tbody>
                </table>
                 
               </div>
               <br>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->
<script src="<?= BASE_ASSET; ?>/js/jquery.tabledit.min.js"></script>
<!-- Page script -->
<script>
   var table_payments_select;
   var data_payments_table = [];
   var item_payment = 0;
 /********************************************************************************************** */
   var x =  '<?php echo $this->security->get_csrf_hash(); ?>';
   var y = '<?php echo $this->security->get_csrf_token_name(); ?>';
   $.ajaxPrefilter(function(options, originalOptions, jqXHR){
         if (options['type'].toLowerCase() === "post") {
            console.log(options.data);
            options.data =  options.data + '&'+ y + '='+ x;
            //jqXHR.setRequestHeader('X-CSRFToken', csrf_token);
         }
   });
   /************************************************************************************************* */
   function delete_item_table_payments(elem,valu){
      let row = elem.parentNode.parentNode;
      table_payments.row(row).remove().draw();
      valu = valu ;
      data_payments_table.forEach(function(car, index, object) {
          if(car.tr == valu){
            console.log("Eliminar");
            object.splice(index, 1);
          }
      });
      console.log(data_payments_table);
      if(data_payments_table.length == 0){
        item_payment = 0
        $('#btn_send_request').addClass('disabled') ;
      }
   }
    /************************************************************************************************** */
   var click_column = 0;
   function calculate_data(btn_action){
      var incoterm = $('#incoterm').val().replace(/\,/g, '');
       var quantity = $('#quantity').val().replace(/\,/g, '');
       var price_fob_fca_unit = $('#price_fob_fca_unit').val().replace(/\,/g, '');
       var freight = $('#freight').val().replace(/\,/g, '');
       var sup_overprice = $('#sup_overprice').val().replace(/\,/g, '');
       var purchase_amount = $('#purchase_amount').val().replace(/\,/g, '');
       var price_unit = $('#price_unit').val().replace(/\,/g, '');
       var terms = $('#terms').val();
       var days = $('#days').val().replace(/\,/g, '');

       //Commissions
       var commission_sales_agent = $('#com_sales_agent').val();
       var commission_purchase_office = $('#com_purchase_office').val();
       var commission_other_supp_comm = $('#com_other_supp_comm').val();

       //Representative
       var representative_commission = $('#representative_commission').val();
       var representative_purchase_office = $('#representative_purchase_office').val();

       //Price Increase
       var price_increase_commission = $('#price_increase_commission').val();
       var payment_customer_select = $('#payment_customer_select').val();
      console.log(quantity+"  "+price_fob_fca_unit+"  "+freight);
       if(quantity !== '' && price_fob_fca_unit !== '' ) {
         $.ajax({
            type:"post",
            url: "<?php echo base_url(); ?>administrator/amuco_price_calculator/price_calculator",
            data:{ incoterm: incoterm, 
                  quantity: quantity, 
                  price_fob_fca_unit: price_fob_fca_unit,  
                  freight: freight, 
                  sup_overprice: sup_overprice, 
                  purchase_amount: purchase_amount,
                  price_unit: price_unit,
                  terms: terms,
                  days:days,
                  commission_sales_agent: commission_sales_agent,
                  commission_purchase_office: commission_purchase_office,
                  commission_other_supp_comm: commission_other_supp_comm,
                  representative_commission: representative_commission,
                  representative_purchase_office: representative_purchase_office,
                  price_increase_commission: price_increase_commission,
                  payment_customer_select : payment_customer_select,
                  '<?php echo $this->security->get_csrf_token_name(); ?>':'<?php echo $this->security->get_csrf_hash(); ?>'
                  },
            success:function(response) {
            if(response){
               var json = JSON.parse(response);
               console.log(json.coface_result);
               $('#costs_purchase_amount').val(numeral(purchase_amount).format('0,0.00'));
              // $('#financing_prepaid').val(numeral(json[0].financing_result).format('0,0.00'));
               if(btn_action == "btn_calculate"){
                  $('#financing_prepaid').val('0.00');
                  $('#coface').val(numeral(json.coface_result).format('0,0.00'));
                  $('#bank_charge').val(numeral(json.bank_charge_result).format('0,0.00'));
                  $('#freight_insurance').val(numeral(json.freight_insurance_result).format('0,0.00'));
                  $('#purchase_office_comm').val(numeral(json.purchase_office_comm).format('0,0.00'));
                  $('#comm_other_supplier').val(numeral(json.comm_other_supplier).format('0,0.00'));
                  //$('#total_purchase_cost1').val(numeral(json[0].total_purchase_cost).format('0,0.00'));
                  //$('#total_purchase_cost2').val(numeral(json[0].total_purchase_unit).format('0,0.00'));
                  total_cost = parseFloat(purchase_amount) +parseFloat(numeral(json.coface_result).format('0,0.00')) + parseFloat(numeral(json.bank_charge_result).format('0,0.00')) + parseFloat(numeral(json.freight_insurance_result).format('0,0.00')) + parseFloat(numeral(json.purchase_office_comm).format('0,0.00')) + parseFloat(numeral(json.comm_other_supplier).format('0,0.00'));
                  console.log(total_cost);
                  total_cost_unit = total_cost/ $('#quantity').val();
                  $('#total_purchase_cost1').val(numeral(total_cost).format('0,0.00'));
                  $('#total_purchase_cost2').val(numeral(total_cost_unit).format('0,0.00'));
                 
                  Table.clear().draw();
                  Table.rows.add(json.calculations ).draw();
               }else{
                  $('#financing_prepaid').val(numeral(json.financing_result).format('0,0.00'));
                  $('#coface').val(numeral(json.coface_result).format('0,0.00'));
                  $('#bank_charge').val(numeral(json.bank_charge_result).format('0,0.00'));
                  $('#freight_insurance').val(numeral(json.freight_insurance_result).format('0,0.00'));
                  $('#purchase_office_comm').val(numeral(json.purchase_office_comm).format('0,0.00'));
                  $('#comm_other_supplier').val(numeral(json.comm_other_supplier).format('0,0.00'));
                  total_cost = parseFloat(purchase_amount) + parseFloat(numeral(json.financing_result).format('0,0.00')) + parseFloat(numeral(json.coface_result).format('0,0.00')) + parseFloat(numeral(json.bank_charge_result).format('0,0.00')) + parseFloat(numeral(json.freight_insurance_result).format('0,0.00')) + parseFloat(numeral(json.purchase_office_comm).format('0,0.00')) + parseFloat(numeral(json.comm_other_supplier).format('0,0.00'));
                  console.log(total_cost);
                  total_cost_unit = total_cost/ $('#quantity').val();
                  $('#total_purchase_cost1').val(numeral(total_cost).format('0,0.00'));
                  $('#total_purchase_cost2').val(numeral(total_cost_unit).format('0,0.00'));

                  $('#label_financing').html("Financing "+ json.code_payment); 
               }
                  // Activate an inline edit on click of a table cell
                 /* $('#sale_customer').on( 'click', 'tbody td:not(:first-child)', function (e) {
                     editor.inline( this );
                  } );*/
                  


            }
            },
            error: function() 
            {
               alert("Invalide!");
            }
         });
      }else{
         alert("Please enter the values ​​for the calculations");
      }
   }
   $(document).ready(function(){
      $('#add_days').keyup(function(){
        $('#days').val( $('#add_days').val());
      });
      /******************************************************************************************* */

       table_payments_select = $("#table_offering_details").DataTable({
     
         columns: [
            
            { data: "payment_terms_customer" },
            { data: "calculated_offer_price", render: $.fn.dataTable.render.number( ',', '.', 2 )},
            { data: "offer_price_per_unit", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "price_increase", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "sales_amount", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "estimated_gross_profit", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "estimated_commission", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "rep_commission", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "quantity", render: $.fn.dataTable.render.number( ',', '.', 2 )},
            { data: "actions" },
            { data: "code_payment" },
            { data: "id" },
            { data: "incoterm" },
           
            { data: "price_fob", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "freight", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "supp_overprice", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "purchase_amount", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "price_unit", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "supp_term", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "sales_agent" },
            { data: "purchasing_office" },
            { data: "other_supp_comm", render: $.fn.dataTable.render.number( ',', '.', 2 )},
            { data: "rep_comm", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "rep_overprice", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "price_increase", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "financing", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "coface", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "bank_charge", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "freight_insurance", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "purchase_off_comm", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "comm_other_supp", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            { data: "total_purchase", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
            
         ],

         columnDefs: [
            { className: "hide_column", "targets": [10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31] }
         ],
         
         rowCallback: function (row, data) {},
            filter: false,
            info: false,
            ordering: [[ 1, "desc" ]],
            processing: false,
            retrieve: false,
            paging :  false,
            searching: false,
            scrollX: true,
            responsive: true,
            scrollCollapse: true, 
            fixedColumns:
               {
               leftColumns: 1,
               rightColumns: 1
                     
               },
         });
         
      /******************************************************************************************* */
      $('#sale_customer').on( 'select.dt', function ( e, dt, type, indexes ) {
         console.log("sale_customer entro");
        
            var data_calculator = dt.rows(indexes).data();
            console.log(data_calculator[0]['price_increase']);
            var data_table_payments = [
                {
                  payment_terms_customer: data_calculator[0]['payment_terms_customer'],
                  calculated_offer_price:data_calculator[0]['calculated_offer_price'],
                  offer_price_per_unit:data_calculator[0]['offer_price_per_unit'],
                  price_increase: data_calculator[0]['price_increase'],
                  sales_amount: data_calculator[0]['sales_amount'],
                  estimated_gross_profit : data_calculator[0]['estimated_gross_profit'],
                  estimated_commission : data_calculator[0]['estimated_commission'],
                  rep_commission : data_calculator[0]['rep_commission'],
                  quantity : $('#quantity').val(),
                  actions:'<a onclick="delete_item_table_payments(this,'+ item_payment +')"  id="delete_payment_' + item_payment + '"  href="javascript:void(0);"  class="label-default delete_product"><i class="fa fa-close"></i> Delete</a>',
                  code_payment :  data_calculator[0]['code_payment'],
                  id : data_calculator[0]['id'],
                  incoterm : $('#incoterm').val(),
                  price_fob: $('#price_fob_fca_unit').val(),
                  freight : $('#freight').val(),
                  supp_overprice:  $('#sup_overprice').val(),
                  purchase_amount : $('#purchase_amount').val(),
                  price_unit  : $('#price_unit').val(),
                  supp_term :  $('#payment_customer_select').val(),
                  sales_agent : $('#com_sales_agent').val(),
                  purchasing_office: $('#com_purchase_office').val(),
                  other_supp_comm : $('#com_other_supp_comm').val(),
                  rep_comm : $('#representative_commission').val(),
                  rep_overprice : $('#representative_purchase_office').val(),
                //  price_increase : $('#price_increase_commission').val(),
                  financing : $('#financing_prepaid').val(),
                  coface: $('#coface').val(),
                  bank_charge: $('#bank_charge').val(),
                  freight_insurance :$('#freight_insurance').val(),
                  purchase_off_comm: $('#purchase_office_comm').val(),
                  comm_other_supp : $('#comm_other_supplier').val(),
                  total_purchase : $('#total_purchase_cost1').val(),
                 
                }
              ];
               table_payments_select.rows.add(data_table_payments).draw();
               data_payments_table.push({
                  payment_terms_customer: data_calculator[0]['payment_terms_customer'],
                  calculated_offer_price:data_calculator[0]['calculated_offer_price'],
                  offer_price_per_unit:data_calculator[0]['offer_price_per_unit'],
                  price_increase : data_calculator[0]['price_increase'],
                  sales_amount: data_calculator[0]['sales_amount'],
                  estimated_gross_profit : data_calculator[0]['estimated_gross_profit'],
                  estimated_commission : data_calculator[0]['estimated_commission'],
                  rep_commission : data_calculator[0]['rep_commission'],
                  code_payment :  data_calculator[0]['code_payment'],
                  id : data_calculator[0]['id'],
                  incoterm : $('#incoterm').val(),
                  quantity : $('#quantity').val(),
                  price_fob: $('#price_fob_fca_unit').val(),
                  freight : $('#freight').val(),
                  supp_overprice:  $('#sup_overprice').val(),
                  purchase_amount : $('#purchase_amount').val(),
                  price_unit  : $('#price_unit').val(),
                  supp_term :  $('#payment_customer_select').val(),
                  sales_agent : $('#com_sales_agent').val(),
                  purchasing_office: $('#com_purchase_office').val(),
                  other_supp_comm : $('#com_other_supp_comm').val(),
                  rep_comm : $('#representative_commission').val(),
                  rep_overprice : $('#representative_purchase_office').val(),
                  financing : $('#financing_prepaid').val(),
                  coface: $('#coface').val(),
                  bank_charge: $('#bank_charge').val(),
                  freight_insurance :$('#freight_insurance').val(),
                  purchase_off_comm: $('#purchase_office_comm').val(),
                  total_purchase : $('#total_purchase_cost1').val(),
                  tr:item_payment,
                  '<?php echo $this->security->get_csrf_token_name(); ?>':'<?php echo $this->security->get_csrf_hash(); ?>'
            });
            item_payment++;
            console.log(table_payments_select.rows().count());
            if(table_payments_select.rows().count() > 0){
               $('#btn_send_request').removeClass('disabled') ;
            }
         });  







      /**************************************************************************************************** */
      $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_amuco_price_calculator').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/amuco_price_calculator/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });
    initSortable('amuco_price_calculator', $('table.dataTable'));

   $("#quantity").keyup(function() {
      var quantity = $('#quantity').val();
      var price_fob_fca_unit = $('#price_fob_fca_unit').val();
      var freight = $('#freight').val() == '' ? '0'  : $('#freight').val();
      var sup_overprice = $('#sup_overprice').val() == '' ? '0'  :  $('#sup_overprice').val();;
      var purchase_amount = '';
      var price_unit = '';

      if(quantity !== '' && price_fob_fca_unit !== '' && freight !== '' && sup_overprice !== '') {
         purchase_amount = (parseFloat(quantity.replace(/\,/g, '')) *  parseFloat(price_fob_fca_unit.replace(/\,/g, ''))) + parseFloat(freight.replace(/\,/g, '')) + parseFloat(sup_overprice.replace(/\,/g, ''));
         price_unit = purchase_amount.toFixed(2) / parseFloat(quantity.replace(/\,/g, ''));
         $('#purchase_amount').val(purchase_amount);
         $('#price_unit').val(price_unit);
         domo();
      } else {
         $('#purchase_amount').val('');
         $('#price_unit').val('');  
      }
   });

   $("#price_fob_fca_unit").keyup(function() {
      var quantity = $('#quantity').val();
      var price_fob_fca_unit = $('#price_fob_fca_unit').val();
      var freight = $('#freight').val() == '' ? '0' : $('#freight').val();
      var sup_overprice = $('#sup_overprice').val() == '' ? '0'  :  $('#sup_overprice').val();
      var purchase_amount = '';
      var price_unit = '';

      if(quantity !== '' && price_fob_fca_unit !== '' && freight !== '' && sup_overprice !== '') {
         purchase_amount = (parseFloat(quantity.replace(/\,/g, '')) *  parseFloat(price_fob_fca_unit.replace(/\,/g, ''))) + parseFloat(freight.replace(/\,/g, '')) + parseFloat(sup_overprice.replace(/\,/g, ''));
         price_unit = purchase_amount.toFixed(2) / parseFloat(quantity.replace(/\,/g, ''));
         $('#purchase_amount').val(purchase_amount);
         $('#price_unit').val(price_unit);
         domo();
      } else {
         $('#purchase_amount').val('');
         $('#price_unit').val('');  
      }
   });

   $("#freight").keyup(function() {
      var quantity = $('#quantity').val();
      var price_fob_fca_unit = $('#price_fob_fca_unit').val();
      var freight = $('#freight').val() == '' ? '0'  : $('#freight').val();
      var sup_overprice =  $('#sup_overprice').val() == '' ? '0'  :  $('#sup_overprice').val();
      var purchase_amount = '';
      var price_unit = '';

      if(quantity !== '' && price_fob_fca_unit !== '' && freight !== '' && sup_overprice !== '') {
         purchase_amount = (parseFloat(quantity.replace(/\,/g, '')) *  parseFloat(price_fob_fca_unit.replace(/\,/g, ''))) + parseFloat(freight.replace(/\,/g, '')) + parseFloat(sup_overprice.replace(/\,/g, ''));
         price_unit = purchase_amount.toFixed(2) / parseFloat(quantity.replace(/\,/g, ''));
         $('#purchase_amount').val(purchase_amount);
         $('#price_unit').val(price_unit);
         domo();
      } else {
         $('#purchase_amount').val('');
         $('#price_unit').val('');  
      }
   });

   $("#sup_overprice").keyup(function() {
      var quantity = $('#quantity').val();
      var price_fob_fca_unit = $('#price_fob_fca_unit').val();
      var freight = $('#freight').val() == '' ? '0'  : $('#freight').val();
      var sup_overprice = $('#sup_overprice').val() == '' ? '0' :  $('#sup_overprice').val();
      var purchase_amount = '';
      var price_unit = '';
      if(quantity !== '' && price_fob_fca_unit !== '' && freight !== '' ) {
         purchase_amount = (parseFloat(quantity.replace(/\,/g, '')) *  parseFloat(price_fob_fca_unit.replace(/\,/g, ''))) + parseFloat(freight.replace(/\,/g, '')) + parseFloat(sup_overprice.replace(/\,/g, ''));
         price_unit = purchase_amount.toFixed(2) / parseFloat(quantity.replace(/\,/g, ''));
         $('#purchase_amount').val(purchase_amount);
         $('#price_unit').val(price_unit);
         domo();
      } else {
         $('#purchase_amount').val('');
         $('#price_unit').val('');  
      }
   });

   $('#btn_reset').click(function(){
      $('#label_financing').html("Financing ");
      $('#form_calculator')[0].reset();
      $('#add_days').val('0');
      $('#days').val( $('#add_days').val());
      Table.clear().draw();
   });


  /* editor = new $.fn.dataTable.Editor( {
      table: "#sale_customer",
      idSrc:  'id',
      fields: [ {
               label: "Payment Terms Customer",
               name: "payment_terms_customer"
            }, {
               label: "Calculated Offer Price",
               name: "calculated_offer_price"
            }, {
               label: "Offer Price Per Unit",
               name: "offer_price_per_unit"
            }, {
               label: "Price Increase (%)",
               name: "price_increase"
            }, {
               label: "Sales Amount",
               name: "sales_amount"
            }, {
               label: "Estimated Gross Profit",
               name: "estimated_gross_profit",
            }, {
               label: "Estimated Commission",
               name: "estimated_commission"
            }, {
               label: "Rep. Commission",
               name: "rep_commission"
            }
      ]
   });*/

   Table = $("#sale_customer").DataTable({
      data:[],
      columns: [
         {
                data: '',
                defaultContent: '',
                className: 'select-checkbox',
                orderable: false,
                id:'select_col'
            },
         { data: "payment_terms_customer" },
         { data: "calculated_offer_price", render: $.fn.dataTable.render.number( ',', '.', 2 )},
         { data: "offer_price_per_unit", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
         { data: "price_increase", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
         { data: "sales_amount", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
         { data: "estimated_gross_profit", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
         { data: "estimated_commission", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
         { data: "rep_commission", render: $.fn.dataTable.render.number( ',', '.', 2 ) },
         { data: "code_payment" },
         { data: "id" },
      ],
      columnDefs: [
       { className: "hide_column", "targets": [9,10 ] }
     ],
      rowCallback: function (row, data) {
         
      },
         filter: false,
         info: false,
         ordering: [[ 1, "desc" ]],
         processing: false,
         retrieve: false,
         scrollY: "380px",
         scrollCollapse  : true,
         paging :         false,
         select: {
            style:    'os',
            selector: 'td:first-child'
        },
      });

    $('#btn_calculate').click(function(e){
       e.preventDefault();
       calculate_data("btn_calculate");
       //purchase to supplier
       
       
    });

   /* $('#sale_customer').on('click', 'tbody td', function (e) {
       alert("columna"+$(this).hasClass('select-checkbox'));
       console.log($(this).parents('tr').hasClass('selected'));
       alert("columna" +  $(this).parents('tr').hasClass('selected') );
       //$( this ).toggleClass( "chosen" );
       if($(this).hasClass('select-checkbox') ){
          if($(this).parents('tr').hasClass('selected')){
            console.log($(this).parents('tr').data());
          }else{

          }

       }
       var count =  Table.rows( { selected: true } ).count();
       console.log( count);
    });*/
    $('#sale_customer').on('click', 'tbody td', function (e) {
      console.log(Table.rows(this.parentNode).data()[0]);
      if($(this).hasClass('select-checkbox') ){
          if($(this).parents('tr').hasClass('selected')){
            $('#payment_customer_select').val(0);
            $('#financing_prepaid').val('0.00');
            $('#btn_quit_offer').addClass('disabled') ;
          }else{
            console.log(Table.rows(this.parentNode).data()[0]['id']);
            $('#payment_customer_select').val(Table.rows(this.parentNode).data()[0]['id']);   
            calculate_data("select_payment");
            $('#btn_quit_offer').removeClass('disabled') ;
          }
      }
      $('#sale_customer').Tabledit({
                     deleteButton: false,
                     editButton: false,          
                     columns: {
                        identifier:[10, 'id'],                    
                        editable:[ [3,'offer_price_per_unit'],[4,'price_increase'],
                                    [5, 'sales_amount'],[6,'estimated_gross_profit'],[7,'estimated_commission'],[8,'rep_commission'],
                        ],
                     },

                    
                     hideIdentifier: false,
                     url: BASE_URL + '/administrator/amuco_details_request_office/edit_save_table_test/',  
                     onSuccess:function(data, textStatus, jqXHR)
                     {
                        //console.log(data.columns.id);
                        //console.log(textStatus);
                        //console.log(jqXHR);

                        if(textStatus=='success' && data.success){
                           var column_1=0,column_2=0,column_3=0,column_4=0,column_5=0;
                         
                           
                           $('#sale_customer tr').each(function() {
                              //console.log( $(this).find("td").eq(10).text());
                             

                              if( $(this).find("td").eq(10).text() == data.columns.id){
                                 var temp = Table.rows(this).data();
                               
                                 let y = 0;
                                 $(this).children('td').each ( function() {
                                   // console.log($(this).html());
                                    if(y==2)
                                      column_price_cal = $(this).text();
                                    if(y == 3)
                                      column_1 = $(this).text();
                                    if(y == 4)
                                      column_2 = $(this).text();
                                    if(y == 5)
                                      column_3 = $(this).text();
                                    if(y == 6)
                                      column_4 = $(this).text();
                                    if(y == 7)
                                      column_5 = $(this).text();  

                                      y++;
                                 });
                                 if(data.columns.column_name == 'offer_price_per_unit'){
                                    let offer_increase = 1 - (1 * parseFloat($('#price_increase_commission').val().replace(/\,/g, ''))/ 100);
                                    let cost = (parseFloat(column_price_cal.replace(/\,/g, '')) *  offer_increase).toFixed(2);
                                    let vall = column_1 * $('#quantity').val();
                                    let purchaase_amo= cost;
                                    let vall_2 = parseFloat((1 - ( purchaase_amo/ vall)))*100;
                                    let vall_3 = vall - purchaase_amo;
                                    let vall_4 = vall_3 *  parseFloat($('#com_sales_agent').val().replace(/\,/g, ''));
                                   
                                       console.log('aqui');
                                       console.log(temp[0]);
                                       console.log(numeral(column_1).format('0,0.00'));
                                       temp[0]['offer_price_per_unit'] = column_1;
                                       temp[0]['price_increase'] = vall_2.toFixed(2);
                                       temp[0]['sales_amount'] = vall;
                                       temp[0]['estimated_gross_profit'] =vall_3;
                                       temp[0]['estimated_commission'] = vall_4;
                                       //Table.rows(1).data(temp).invalidate();
                                       $('#sale_customer').dataTable().fnUpdate(temp[0],this,undefined,true);
                                       console.log(data);
                                       console.log(Table.rows(this).data()); 
                                     /*  $(this).find("td").eq(3).find('span').text(numeral(column_1).format('0,0.00'));
                                    $(this).find("td").eq(3).find('input').val(numeral(column_1).format('0,0.00'));
                                    $(this).find("td").eq(5).find('span').text(numeral(vall).format('0,0.00'));
                                    $(this).find("td").eq(5).find('input').val(numeral(vall).format('0,0.00'));
                                   // $(this).find("td").eq(5).text(vall.toFixed(2)); 
                                    $(this).find("td").eq(4).find('span').text(numeral(vall_2).format('0,0.00'));
                                    $(this).find("td").eq(4).find('input').val(numeral(vall_2).format('0,0.00')); 
                                    $(this).find("td").eq(6).find('span').text(numeral(vall_3).format('0,0.00')); 
                                    $(this).find("td").eq(6).find('input').val(numeral(vall_3).format('0,0.00')); 
                                    $(this).find("td").eq(7).find('span').text(numeral(vall_4).format('0,0.00')); 
                                    $(this).find("td").eq(7).find('input').val(numeral(vall_4).format('0,0.00'));*/
                                 }
                                 if(data.columns.column_name == 'price_increase'){
                                    let offer_increase = 1 - (1 * parseFloat($('#price_increase_commission').val().replace(/\,/g, ''))/ 100);
                                    let offer_increase_new =  1 - (1 * parseFloat(column_2)/100).toFixed(2);
                                    let purchaase_amo = (parseFloat(column_price_cal.replace(/\,/g, '')) *  offer_increase).toFixed(2);
                                    let vall = purchaase_amo /offer_increase_new;
                                    let vall_2 = vall/ $('#quantity').val();
                                    let vall_3 = vall - purchaase_amo;
                                    let vall_4 = vall_3 *  parseFloat($('#com_sales_agent').val().replace(/\,/g, ''));
                                   /* $(this).find("td").eq(4).find('span').text(numeral(column_2).format('0,0.00'));
                                    $(this).find("td").eq(4).find('input').val(numeral(column_2).format('0,0.00'));
                                    $(this).find("td").eq(5).find('span').text(numeral(vall).format('0,0.00'));
                                    $(this).find("td").eq(5).find('input').val(numeral(vall).format('0,0.00'));
                                   // $(this).find("td").eq(5).text(vall.toFixed(2)); 
                                    $(this).find("td").eq(3).find('span').text(numeral(vall_2).format('0,0.00'));
                                    $(this).find("td").eq(3).find('input').val(numeral(vall_2).format('0,0.00')); 
                                    $(this).find("td").eq(6).find('span').text(numeral(vall_3).format('0,0.00')); 
                                    $(this).find("td").eq(6).find('input').val(numeral(vall_3).format('0,0.00')); 
                                    $(this).find("td").eq(7).find('span').text(numeral(vall_4).format('0,0.00')); 
                                    $(this).find("td").eq(7).find('input').val(numeral(vall_4).format('0,0.00')); */

                                    temp[0]['offer_price_per_unit'] = vall_2.toFixed(2);;
                                    temp[0]['price_increase'] = column_2;
                                    temp[0]['sales_amount'] = vall.toFixed(2);
                                    temp[0]['estimated_gross_profit'] =vall_3.toFixed(2);
                                    temp[0]['estimated_commission'] = vall_4.toFixed(2);
                                       //Table.rows(1).data(temp).invalidate();
                                    $('#sale_customer').dataTable().fnUpdate(temp[0],this,undefined,true);
                                    console.log(data);
                                    console.log(Table.rows(this).data()); 
                                 }
                                 if(data.columns.column_name == 'sales_amount'){
                                    let offer_increase = 1 - (1 * parseFloat($('#price_increase_commission').val().replace(/\,/g, ''))/ 100);
                                    let purchaase_amo = (parseFloat(column_price_cal.replace(/\,/g, '')) *  offer_increase);
                                    let vall_2 = parseFloat(column_3)/ $('#quantity').val();
                                    let vall =   (1 - ( purchaase_amo/  parseFloat(column_3)))*100;
                                    let vall_3 =  parseFloat(column_3) - purchaase_amo;
                                    let vall_4 = vall_3 *  parseFloat($('#com_sales_agent').val().replace(/\,/g, ''));
                                   /* $(this).find("td").eq(5).find('span').text(numeral(column_3).format('0,0.00'));
                                    $(this).find("td").eq(5).find('input').val(numeral(column_3).format('0,0.00'));
                                    $(this).find("td").eq(4).find('span').text(numeral(vall).format('0,0.00'));
                                    $(this).find("td").eq(4).find('input').val(numeral(vall).format('0,0.00'));
                                   // $(this).find("td").eq(5).text(vall.toFixed(2)); 
                                    $(this).find("td").eq(3).find('span').text(numeral(vall_2).format('0,0.00'));
                                    $(this).find("td").eq(3).find('input').val(numeral(vall_2).format('0,0.00')); 
                                    $(this).find("td").eq(6).find('span').text(numeral(vall_3).format('0,0.00')); 
                                    $(this).find("td").eq(6).find('input').val(numeral(vall_3).format('0,0.00')); 
                                    $(this).find("td").eq(7).find('span').text(numeral(vall_4).format('0,0.00')); 
                                    $(this).find("td").eq(7).find('input').val(numeral(vall_4).format('0,0.00')); */
                                    temp[0]['offer_price_per_unit'] = vall_2.toFixed(2);;
                                    temp[0]['price_increase'] = vall.toFixed(2);
                                    temp[0]['sales_amount'] = column_3;
                                    temp[0]['estimated_gross_profit'] =vall_3.toFixed(2);
                                    temp[0]['estimated_commission'] = vall_4.toFixed(2);
                                       //Table.rows(1).data(temp).invalidate();
                                    $('#sale_customer').dataTable().fnUpdate(temp[0],this,undefined,true);
                                 }
                                 if(data.columns.column_name == 'estimated_gross_profit'){
                                    let offer_increase = 1 - (1 * parseFloat($('#price_increase_commission').val().replace(/\,/g, ''))/ 100);
                                    let purchaase_amo = (parseFloat(column_price_cal.replace(/\,/g, '')) *  offer_increase).toFixed(2);
                                    let vall_3 =  parseFloat(column_4) + parseFloat(purchaase_amo);
                                  //  console.log('sales'+vall_3);
                                    let vall_2 = parseFloat(vall_3) / $('#quantity').val();
                                    let vall =   (1 - ( purchaase_amo/  parseFloat(vall_3)))*100;
                                    let vall_4 = parseFloat(column_4) *  parseFloat($('#com_sales_agent').val().replace(/\,/g, ''));
                                   /* $(this).find("td").eq(6).find('span').text(numeral(column_4).format('0,0.00'));
                                    $(this).find("td").eq(6).find('input').val(numeral(column_4).format('0,0.00'));
                                    $(this).find("td").eq(4).find('span').text(numeral(vall).format('0,0.00'));
                                    $(this).find("td").eq(4).find('input').val(numeral(vall).format('0,0.00'));
                                   // $(this).find("td").eq(5).text(vall.toFixed(2)); 
                                    $(this).find("td").eq(3).find('span').text(numeral(vall_2).format('0,0.00'));
                                    $(this).find("td").eq(3).find('input').val(numeral(vall_2).format('0,0.00')); 
                                    $(this).find("td").eq(5).find('span').text(numeral(vall_3).format('0,0.00')); 
                                    $(this).find("td").eq(5).find('input').val(numeral(vall_3).format('0,0.00')); 
                                    $(this).find("td").eq(7).find('span').text(numeral(vall_4).format('0,0.00')); 
                                    $(this).find("td").eq(7).find('input').val(numeral(vall_4).format('0,0.00')); */
                                    temp[0]['offer_price_per_unit'] = vall_2.toFixed(2);;
                                    temp[0]['price_increase'] = vall.toFixed(2);
                                    temp[0]['sales_amount'] = vall_3.toFixed(2);
                                    temp[0]['estimated_gross_profit'] =column_4;
                                    temp[0]['estimated_commission'] = vall_4.toFixed(2);
                                       //Table.rows(1).data(temp).invalidate();
                                    $('#sale_customer').dataTable().fnUpdate(temp[0],this,undefined,true);
                                 }
                                 if(data.columns.column_name == 'estimated_commission'){
                                    let est_comm =  parseFloat(column_5);
                                   /* $(this).find("td").eq(7).find('span').text(numeral(est_comm).format('0,0.00'));
                                    $(this).find("td").eq(7).find('input').val(numeral(est_comm).format('0,0.00')); */
                                  
                                    temp[0]['estimated_commission'] = est_comm.toFixed(2);
                                       //Table.rows(1).data(temp).invalidate();
                                    $('#sale_customer').dataTable().fnUpdate(temp[0],this,undefined,true);
                                    
                                 }
                               
                                
                              }
                        
                              
                           });
                         // console.log(column_1+"- " +column_2+"- " + column_3+"- " +column_4+"- " +column_5+"- ");
                      
                        }
                     },
                     onAjax: function(action, serialize) {
                        //console.log('onAjax(action, serialize)');
                        //console.log(action);
                        
                     //console.log(serialize);
                     serialize = serialize + '&'+ y + '='+ x;
                    // console.log(serialize);
                     },
                  });  
   });

    
      /*$('#sale_customer').on('click', 'tbody tr', function (e) {
        // $(this).toggleClass('selected');
         console.log( Table.row( this ).data());
         //console.log("table"+Table.rows('.selected').data().length);
        
         if(Table.rows('.selected').data().length > 0){
         // console.log(Table.rows(this.parentNode).data()[0]);
         // $('#payment_customer_select').val(Table.rows('.selected').data()[0]['id']);
            $('#payment_customer_select').val(Table.row( this ).data()['id']);   
            calculate_data("select_payment");
            $('#btn_quit_offer').removeClass('disabled') ;
         }else{ 
            $('#payment_customer_select').val(0);
            $('#financing_prepaid').val('0.00');
            $('#btn_quit_offer').addClass('disabled') ;
         }
      });*/
    


    /******************************************************************************************* */
    $('#btn_quit_offer').click(function(){
       alert(Table.rows().count());
       if(Table.rows().count() > 0){
          $('#btn_quit_offer').addClass('disabled') ;
        }
    });
    /********************************************************************************************* */

    if( $('#sale_customer').find('tbody tr td').length > 1){
      $('#sale_customer').Tabledit({
            deleteButton: false,
            editButton: false,          
            columns: {
              identifier:[9, 'id'],                    
              editable:[ [3, 'quantity'],[4,'unit', JSON.stringify(obj_units)],[6,'fcl'],[7,'fcl_option'],
              [8,'type_fcl',JSON.stringify(obj_type_fcl)],[9,'weight'],[10,'unit_pack',JSON.stringify(obj_units)],
              [12,'material',JSON.stringify(obj_material)],[14,'shape',JSON.stringify(obj_packing)],
              [16,'pallets',JSON.stringify({"0":"Without Pallets","1":"With Pallets"})],[17,'price_fob'],[18,'total_freight'],[19,'total_price'],
              [20,'shipping_port',JSON.stringify(obj_sp)],[25,'manufacturer',JSON.stringify(obj_suppliers)],
              [27,'supplier_incoterm',JSON.stringify(obj_incoterm)], [29,'payment_terms',JSON.stringify(obj_payments)],
              [31,'incoterm_price',JSON.stringify(obj_incoterm)],[33,'destination_port',JSON.stringify(obj_sp)],
              [35,'ETD'],[36,'analysis_standard'],[37,'valid_until'],[38,'comments']
        
              ]
            },
            hideIdentifier: false,
            url: BASE_URL + '/administrator/amuco_details_request_office/edit_save_table/'+table_price.rows(this.parentNode).data()[0]['id'],  
            onSuccess:function(data, textStatus, jqXHR)
            {
              console.log(data);
              console.log(textStatus);
              console.log(jqXHR);
            },
            onAjax: function(action, serialize) {
              console.log('onAjax(action, serialize)');
                console.log(action);
                serialize.new ="hh";
              console.log(serialize);
              serialize = serialize + '&'+ y + '='+ x;
              console.log(serialize);
            },
        });
    }
  }); /*end doc ready*/
</script>