
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Amuco Suppliers      <small><?= cclang('detail', ['Amuco Suppliers']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_suppliers'); ?>">Amuco Suppliers</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <div class="col-md-12">
                  <div class="box box-widget widget-user">
                     <div class="widget-user-header " style="background: url('<?= BASE_ASSET; ?>admin-lte/dist/img/photo1.png') center center;">
                        <h3 class="widget-user-username text-white" style="margin-left:1%"><?= _ent(ucwords($amuco_suppliers->name)); ?></h3>
                        <h5 class="widget-user-desc text-white" style="margin-left:1.2%"><?= ' ID: '._ent($amuco_suppliers->id); ?></h5>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_URL.'uploads/user/'.(!empty($amuco_suppliers->avatar) ? $amuco_suppliers->avatar:'default.png'); ?>" alt="User Avatar" style="height: 80px; width: 80px" >
                     </div>
                     <div class="box-footer">         
                     <!-- /.row -->
                     </div>
                  </div>     
               </div>
               <div class="nav-tabs-custom padding-left-0 tab-page ">
                  <ul class="nav nav-tabs">
                  <li class="active"><a class=" active tab_animation" href="#tab_1" data-toggle="tab"><i class="fa fa-gear text-green"></i> Information</a></li>
                  <li><a class=" active btn-form-preview tab_animation" href="#tab_2" data-toggle="tab"><i class="fa fa-user"></i> Contacts</a></li>
                  <li><a class=" active btn-form-preview tab_animation" href="#tab_3" data-toggle="tab"><i class="fa fa-product-hunt"></i> Visits</a></li>
                  </ul>
                  <div class="tab-content">
                     <div class="tab-pane rest-page-test active" id="tab_1" style="margin-top:20px;">
                        <div class="col-md-4">
                           <div class="box box-widget widget-user-2">
                              <!-- Add the bg color to the header using any of the bg-* classes -->
                              <div class="">
                                 <h3 class="">Details Supplier</h3>
                              </div>
                              <div class="box-footer no-padding">
                                 <ul class="nav nav-stacked">
                                    <li><a href="#"><i class='fa fa-shield color-orange'></i> <?= cclang('status'); ?> 
                                       <?php if ($amuco_suppliers->active) :?>
                                          <span class="pull-right badge bg-green">Active</span></a>
                                       <?php else: ?>
                                          <span class="pull-right badge bg-red">Inactive</span></a>
                                       <?php endif; ?>
                                    </li>
                                    <li><a href="#"> Code <span class="pull-right "><?= _ent($amuco_suppliers->supplier_code); ?></span></a></li>
         
                                    <li><a href="#"> EMAIL <span class="pull-right "><?= _ent($amuco_suppliers->email); ?></span></a></li>
                                    <li><a href="#"> URL <span class="pull-right "><?= _ent($amuco_suppliers->url); ?></span></a></li>
                                    <li><a href="#"> Classification <span class="pull-right "><?= join_multi_select($amuco_suppliers->classification_id, 'amuco_classification_suppliers', 'id', 'name'); ?></span></a> </li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                        <div class="col-md-4">
                           <div class="box box-widget widget-user-2">
                              <div class="">
                                 <h3 class="">Location Information</h3>
                              </div>
                              <div class="box-footer no-padding">
                                 <ul class="nav nav-stacked">

                                    <li><a href="#"> Country <span class="pull-right "> <?= _ent($amuco_suppliers->amuco_countries_name); ?></span></a></li>
                                    <li><a href="#"> City <span class="pull-right "><?= _ent($amuco_suppliers->city); ?></span></a></li>
                                    <li><a href="#"> State/Province <span class="pull-right "><?= _ent($amuco_suppliers->state); ?></span></a></li>
                                    <li><a href="#"> Address <span class="pull-right "><?= _ent($amuco_suppliers->address); ?></span></a></li>
                                    <li><a href="#"> Postal Code <span class="pull-right "><?= _ent($amuco_suppliers->postal_code); ?></span></a></li>
                                    <li><a href="#"> Mobile Phone <span class="pull-right "><?= _ent($amuco_suppliers->mobile_phone); ?></span></a></li>
                                    <li><a href="#"> Office Phone <span class="pull-right "><?= _ent($amuco_suppliers->office_phone); ?></span></a></li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                     </div> 

                     <div class="tab-pane" id="tab_2">
                        <div class="col-md-12">
                           <div class="">
                              <h3 class="">Contacts</h3>
                           </div>
                           <div>
                              <button type="button" class="btn btn-flat btn-success btn_add_new" data-toggle="modal" data-target="#modal-contact"> Add New Contact</button>
                           </div>
                           <?php if(isset($supplier_contacts) && is_array($supplier_contacts) && count($supplier_contacts) > 0):?>
                        
                           <?php foreach($supplier_contacts as $contact):?>
                           
                              <div class="col-12 col-sm-4 col-md-3 d-flex align-items-stretch">
                                 <div class="card bg-light">
                                    <div class="card-header text-muted border-bottom-0">
                                 
                                    </div>
                                    <div class="card-body pt-0">
                                       <div class="row">
                                          <div class="col-7">
                                             <h2 class="lead"><b><?php echo $contact->name;?></b></h2>
                                             <p class="text-muted text-sm"><b>About: </b> <?php echo $contact->departament.'/'.$contact->position;?><br>
                                                email: <?php echo $contact->email;?> </p>
                                             <ul class="ml-4 mb-0 fa-ul text-muted">
                                             <li class="small"><span class="fa-li"><i class="fa fa-lg fa-building"></i></span> Country/city: <?php echo $contact->country.' /'.$contact->city?></li>
                                             <li class="small"><span class="fa-li"><i class="fa fa-lg fa-building"></i></span> Address: <?php echo $contact->home_address ;?></li>
                                             <li class="small"><span class="fa-li"><i class="fa fa-lg fa-phone"></i></span> Phone #: <?php echo $contact->office_phone != null ? $contact->mobile_phone : 'N/A' ; ?></li>
                                             <li class="small"><span class="fa-li"><i class="fa fa-lg fa-phone"></i></span> Mobile Phone #: <?php echo $contact->mobile_phone != null ? $contact->mobile_phone : 'N/A' ; ?></li>
                                             </ul>
                                          </div>
                                          <div class="col-5" style="margin-left:15%">
                                             <img src="../../dist/img/user1-128x128.jpg" alt="" class="img-circle img-fluid">
                                             <a href="" ><?php  echo anchor('administrator/amuco_contacts/view/'.$contact->id.'?popup=show',' <i class="fa fa-user"></i> View', ['class' => 'popup-view']); ?>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="card-footer">
                                       <div class="text-center">
                                         
                                             
                                          </a>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                          
                           <?php endforeach; else: ?>
                           <label> Customer does not have contacts</label>
                          
                           <?php   endif;?>
                        </div> 
                     </div> 
                  
                     <div class="tab-pane" id="tab_3">
                        <div class="col-md-12">
                           <div class="box box-warning">
                              <div class="box-body ">
                                 <!-- Widget: user widget style 1 -->
                                 <div class="box box-widget widget-user-2">
                                    <!-- Add the bg color to the header using any of the bg-* classes -->
                                    <div class="widget-user-header ">
                                    <h3 ><?= cclang('amuco visits') ?></h3>
                                       <div >
                                          <?php is_allowed('amuco_visits_add', function(){?>
                                          <a class="btn btn-flat btn-success btn_add_new"  data-toggle="modal" data-target="#modal-visit" title="<?= cclang('add_new_button', [cclang('amuco_visits')]); ?>  (Ctrl+a)"  ?><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button'); ?> Visit</a>
                                          <?php }) ?>
                                         
                                       </div>
                     
                                       <!-- /.widget-user-image -->
                                       
                                      
                                    </div>

                                    <form name="form_amuco_visits" id="form_amuco_visits" action="<?= base_url('administrator/amuco_visits/index'); ?>">
                                    

                                       <div class="table-responsive"> 
                                          <table class="table table-bordered table-striped dataTable">
                                             <thead>
                                                <tr class="">
                                                   
                                                   <th data-field="id"data-sort="1" data-primary-key="1"> <?= cclang('id') ?></th>
                                                   <th data-field="user_id"data-sort="1" data-primary-key="0"> <?= cclang('User') ?></th>
                                                   <!--th data-field="customer_id"data-sort="1" data-primary-key="0"> <?= cclang('Supplier') ?></th-->
                                                   <th data-field="date_visit"data-sort="1" data-primary-key="0"> <?= cclang('date Visit') ?></th>
                                                   <th data-field="contact_name"data-sort="1" data-primary-key="0"> <?= cclang('Contact Name') ?></th>
                                                   <th data-field="subject"data-sort="1" data-primary-key="0"> <?= cclang('Subject') ?></th>
                                                   <th>Action</th>                        
                                                </tr>
                                             </thead>
                                             <tbody id="tbody_amuco_visits">
                                                <?php foreach($supplier_visits as $amuco_visits): ?>
                                                <tr>
                                                                     
                                                                        
                                                   <td><?= _ent($amuco_visits->id); ?></td> 
                                                   <td><?php if  ($amuco_visits->user_id) {

                                                       echo anchor('administrator/aauth_users/view/'.$amuco_visits->user_id.'?popup=show', $amuco_visits->aauth_users_username, ['class' => 'popup-view']); }?> </td>
                                             
                                                   <td><?= _ent($amuco_visits->date_visit); ?></td> 
                                                   <td><?php if  ($amuco_visits->contact_name) {

                                                   echo anchor('administrator/amuco_contacts/view/'.$amuco_visits->contact_name.'?popup=show', $amuco_visits->amuco_contacts_first_name, ['class' => 'popup-view']); }?> </td>
                                                   <td><?= _ent($amuco_visits->subject); ?></td> 
                                                   <td width="200">
                                             
                                                                              <?php is_allowed('amuco_visits_view', function() use ($amuco_visits){?>
                                                     
                                                   <?= anchor('administrator/amuco_visits/view/'.$amuco_visits->id.'?popup=show','<i class="fa fa-newspaper-o">View</i> ', ['class' => 'popup-view']); ?>
                                                   <?php }) ?>
                                                   <?php is_allowed('amuco_visits_update', function() use ($amuco_visits){?>
                                                   <a href="<?= site_url('administrator/amuco_visits/edit/' . $amuco_visits->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                                                   <?php }) ?>
                                                   <?php is_allowed('amuco_visits_delete', function() use ($amuco_visits){?>
                                                   <a href="javascript:void(0);" data-href="<?= site_url('administrator/amuco_visits/delete/' . $amuco_visits->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                                                   <?php }) ?>

                                                   </td>                        
                                                </tr>
                                                <?php endforeach; ?>
                                                <?php if (count($supplier_visits) == 0) :?>
                                                   <tr>
                                                      <td colspan="100">
                                                      Amuco Visits data is not available
                                                      </td>
                                                   </tr>
                                                <?php endif; ?>

                                             </tbody>
                                          </table>
                                       </div>
                                    </div>
                                    <hr>
                                    <!-- /.widget-user -->
                                    <div class="row">
                                       </form>                 
                                        <div class="col-md-4">
                                          <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                                             <?= $pagination; ?>
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>  
                        </div>
                     </div>  
                  </div> 
            
               <div class="row-fluid col-md-12" style="top:15px" >
                        <?php is_allowed('amuco_suppliers_update', function() use ($amuco_suppliers){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit amuco_suppliers (Ctrl+e)" href="<?= site_url('administrator/amuco_suppliers/edit/'.$amuco_suppliers->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Amuco Suppliers']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_suppliers/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Suppliers']); ?></a>      
               </div>
            </div>
         </div>
      </div>
   </div>
</section>

<section>
   <div class="modal fade" id="modal-contact">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
               <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                        <div class="widget-user-image">
                           <img class="img-circle" src="<?= BASE_ASSET; ?>/img/add2.png" alt="User Avatar">
                        </div>
                        <!-- /.widget-user-image -->
                        <h3 class="widget-user-username">Amuco Contacts</h3>
                        <h5 class="widget-user-desc"><?= cclang('new', ['Amuco Contacts']); ?></h5>
                        <hr>
                  </div>
                  <?= form_open('', [
                        'name'    => 'form_amuco_contacts', 
                        'class'   => 'form-horizontal form-step', 
                        'id'      => 'form_amuco_contacts', 
                        'enctype' => 'multipart/form-data', 
                        'method'  => 'POST'
                        ]); ?>
                     
                     <div class="form-group ">
                            <label for="type_contact" class="col-sm-2 control-label">Type Contact 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <select  class="form-control chosen chosen-select" name="type_contact" id="type_contact" data-placeholder="Select Type Contact" >
                                    <option value=""></option>
                                    <option selected value="Supplier">Supplier</option>
                                    <!--option value="Customer">Customer</option-->
                                    </select>
                                <small class="info help-block">
                                </small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="name" class="col-sm-2 control-label">Name 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="name" id="name" placeholder="Name" value="<?= set_value('name'); ?>">
                                <small class="info help-block">
                                <b>Input Name</b> Max Length : 100.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="position" class="col-sm-2 control-label">Position 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="position" id="position" placeholder="Position" value="<?= set_value('position'); ?>">
                                <small class="info help-block">
                                <b>Input Position</b> Max Length : 100.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="departament" class="col-sm-2 control-label">Departament 
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="departament" id="departament" placeholder="Departament" value="<?= set_value('departament'); ?>">
                                <small class="info help-block">
                                <b>Input Departament</b> Max Length : 100.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="mobile_phone" class="col-sm-2 control-label">Mobile Phone 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="mobile_phone" id="mobile_phone" placeholder="Mobile Phone" value="<?= set_value('mobile_phone'); ?>">
                                <small class="info help-block">
                                <b>Input Mobile Phone</b> Max Length : 30.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="office_phone" class="col-sm-2 control-label">Office Phone 
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="office_phone" id="office_phone" placeholder="Office Phone" value="<?= set_value('office_phone'); ?>">
                                <small class="info help-block">
                                <b>Input Office Phone</b> Max Length : 30.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="personal_phone" class="col-sm-2 control-label">Personal Phone 
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="personal_phone" id="personal_phone" placeholder="Personal Phone" value="<?= set_value('personal_phone'); ?>">
                                <small class="info help-block">
                                <b>Input Personal Phone</b> Max Length : 30.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="fax" class="col-sm-2 control-label">Fax 
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="fax" id="fax" placeholder="Fax" value="<?= set_value('fax'); ?>">
                                <small class="info help-block">
                                <b>Input Fax</b> Max Length : 30.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="email" class="col-sm-2 control-label">Email 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="email" id="email" placeholder="Email" value="<?= set_value('email'); ?>">
                                <small class="info help-block">
                                <b>Input Email</b> Max Length : 100.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="skype" class="col-sm-2 control-label">Skype 
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="skype" id="skype" placeholder="Skype" value="<?= set_value('skype'); ?>">
                                <small class="info help-block">
                                <b>Input Skype</b> Max Length : 100.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="line_products" class="col-sm-2 control-label">Line Products 
                            </label>
                            <div class="col-sm-8">
                                <select  class="form-control chosen chosen-select" name="line_products[]" id="line_products" data-placeholder="Select Line Products" multiple >
                                    <option value=""></option>
                                    <?php foreach (db_get_all_data('amuco_industry_type') as $row): ?>
                                    <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                    <?php endforeach; ?>  
                                </select>
                                <small class="info help-block">
                                <b>Input Line Products</b> Max Length : 100.</small>
                            </div>
                        </div>
                                                 
                                            

                                                 
                                                <div class="form-group " id="supplier" style="display:block">
                            <label for="supplier_id" class="col-sm-2 control-label">Supplier  
                            </label>
                            <div class="col-sm-8">
                                <select  class="form-control chosen chosen-select-deselect" name="supplier_id" id="supplier_id"  >
                                <option value=""></option>
                           <?php foreach (db_get_all_data('amuco_suppliers') as $row): ?>
                           <?php if($row->id == $amuco_suppliers->id): ?>
                              <option selected value="<?= $row->id ?>"><?= $row->name; ?></option>
                           <?php endif; ?>   
                           <?php endforeach; ?>   
                                </select>
                                <small class="info help-block">
                                <b>Input Supplier Id</b> Max Length : 10.</small>
                            </div>
                        </div>

                        

                                                 
                                                <div class="form-group ">
                            <label for="picture" class="col-sm-2 control-label">Picture 
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="picture" id="picture" placeholder="Picture" value="<?= set_value('picture'); ?>">
                                <small class="info help-block">
                                <b>Input Picture</b> Max Length : 250.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="home_address" class="col-sm-2 control-label">Home Address 
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="home_address" id="home_address" placeholder="Home Address" value="<?= set_value('home_address'); ?>">
                                <small class="info help-block">
                                <b>Input Home Address</b> Max Length : 250.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="country" class="col-sm-2 control-label">Country 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <select  class="form-control chosen chosen-select-deselect" name="country" id="country" data-placeholder="Select Country" >
                                    <option value=""></option>
                                    <?php foreach (db_get_all_data('amuco_countries') as $row): ?>
                                    <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                    <?php endforeach; ?>  
                                </select>
                                <small class="info help-block">
                                <b>Input Country</b> Max Length : 10.</small>
                            </div>
                        </div>

                                                 
                                                <div class="form-group ">
                            <label for="city" class="col-sm-2 control-label">City 
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="city" id="city" placeholder="City" value="<?= set_value('city'); ?>">
                                <small class="info help-block">
                                <b>Input City</b> Max Length : 100.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="home_phone" class="col-sm-2 control-label">Home Phone 
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="home_phone" id="home_phone" placeholder="Home Phone" value="<?= set_value('home_phone'); ?>">
                                <small class="info help-block">
                                <b>Input Home Phone</b> Max Length : 30.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="birthday" class="col-sm-2 control-label">Birthday 
                            </label>
                            <div class="col-sm-6">
                            <div class="input-group date col-sm-8">
                              <input type="text" class="form-control pull-right datetimepicker" name="birthday"  id="birthday">
                            </div>
                            <small class="info help-block">
                            </small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="additional_information" class="col-sm-2 control-label">Additional Information 
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="additional_information" id="additional_information" placeholder="Additional Information" value="<?= set_value('additional_information'); ?>">
                                <small class="info help-block">
                                <b>Input Additional Information</b> Max Length : 250.</small>
                            </div>
                        </div>
                                                
                  <div class="message"></div>
                  <div class="modal-footer justify-content-between">
                     <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                     <button class="btn btn-flat btn-primary btn_save btn_action" id="btn_save_contact" data-stype='stay' title="<?= cclang('save_button'); ?> (Ctrl+s)">
                        <i class="fa fa-save" ></i> <?= cclang('save_button'); ?>
                     </button>
                  </div>
                  
                  <?= form_close(); ?>
               </div>
            </div>
           
         
          <!-- /.modal-content -->
         </div>
        <!-- /.modal-dialog -->
      </div>
   </div>   
</section>

<section>
   <div class="modal fade" id="modal-visit">
      <div class="modal-dialog modal-lg">
         <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
               <div class="row" >
                  <div class="box box-warning">
                     <div class="box-body ">
                        <!-- Widget: user widget style 1 -->
                        <div class="box box-widget widget-user-2">
                           <!-- Add the bg color to the header using any of the bg-* classes -->
                           <div class="widget-user-header ">
                              <div class="widget-user-image">
                                 <img class="img-circle" src="<?= BASE_ASSET; ?>/img/add2.png" alt="User Avatar">
                              </div>
                              <!-- /.widget-user-image -->
                              <h3 class="widget-user-username">Amuco Visits</h3>
                              <h5 class="widget-user-desc"><?= cclang('new', ['Amuco Visits']); ?></h5>
                             
                           </div>
                        </div>
                     <div>   
                  <?= form_open('', [
                            'name'    => 'form_amuco_visit', 
                            'class'   => 'form-horizontal form-step', 
                            'id'      => 'form_amuco_visit', 
                            'enctype' => 'multipart/form-data', 
                            'method'  => 'POST'
                            ]); ?>
                  <div class="form-group ">
                        <label for="type_client" class="col-sm-2 control-label">Type Client 
                        <i class="required">*</i>
                        </label>
                        <div class="col-sm-8">
                           <select  class="form-control chosen chosen-select" name="type_client" id="type_client" data-placeholder="Select Type Client" >
                              <option value=""></option>
                              <option value="Supplier" selected>Supplier</option>
                              <!--option value="Supplier">Supplier</option-->
                              </select>
                           <small class="info help-block">
                           </small>
                        </div>
                  </div>
                         
                  <div class="form-group ">
                     <label for="user_id" class="col-sm-2 control-label">User  
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <select  class="form-control chosen chosen-select-deselect" name="user_id" id="user_id" data-placeholder="Select User Id" >
                           <option value=""></option>
                           <?php foreach (db_get_all_data('aauth_users') as $row): ?>
                           <option value="<?= $row->id ?>"><?= $row->username; ?></option>
                           <?php endforeach; ?>  
                        </select>
                        <small class="info help-block">
                        <b>Input User Id</b> Max Length : 10.</small>
                     </div>
                  </div>

                                                 
                  <div class="form-group " id="customer" style="display:none">
                            <label for="customer_id" class="col-sm-2 control-label">Customer  
                            </label>
                            <div class="col-sm-8">
                                <select  class="form-control chosen chosen-select-deselect" name="customer_id" id="customer_id" data-placeholder="Select Customer Id" >
                                    <option value=""></option>
                                    <?php foreach (db_get_all_data('amuco_customers') as $row): ?>
                                    <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                    <?php endforeach; ?>  
                                </select>
                                <small class="info help-block">
                                <b>Input Customer Id</b> Max Length : 10.</small>
                            </div>
                        </div>

                                                 
                                                <div class="form-group " id="supplier" style="display:block">
                            <label for="supplier_id" class="col-sm-2 control-label">Supplier  
                            </label>
                            <div class="col-sm-8">
                                <select  class="form-control chosen chosen-select-deselect" name="supplier_id" id="supplier_id"  >
                                    <option value=""></option>
                                    <?php foreach (db_get_all_data('amuco_suppliers') as $row): ?>
                                    <option <?=  ($row->id==$amuco_suppliers->id) ? 'selected' : ''; ?> value="<?= $row->id ?>"><?= $row->name; ?></option> 
                  
                                    <?php endforeach; ?>  
                                </select>
                                <small class="info help-block">
                                <b>Input Supplier Id</b> Max Length : 10.</small>
                            </div>
                        </div>

                                                 
                  <div class="form-group ">
                     <label for="date_visit" class="col-sm-2 control-label">Date Visit 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-6">
                        <div class="input-group date col-sm-8">
                           <input type="text" class="form-control pull-right datetimepicker" name="date_visit"  id="date_visit">
                         </div>
                        <small class="info help-block">
                        </small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="contact_name" class="col-sm-2 control-label">Contact Name 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <select  class="form-control chosen chosen-select-deselect" name="contact_name" id="contact_name" data-placeholder="Select Contact Name" >
                           <option value=""></option>
                           <?php foreach ($supplier_contacts as $row): ?>
                           <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                           <?php endforeach; ?>  
                        </select>
                        <small class="info help-block">
                        <b>Input Contact Name</b> Max Length : 50.</small>
                     </div>
                  </div>

                  <div class="form-group ">
                     <label for="subject" class="col-sm-2 control-label">Subject 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" value="<?= set_value('subject'); ?>">
                        <small class="info help-block">
                        <b>Input Subject</b> Max Length : 250.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="notes" class="col-sm-2 control-label">Notes 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <textarea id="notes" name="notes" rows="5" cols="80"><?= set_value('Notes'); ?></textarea>
                        <small class="info help-block">
                        </small>
                     </div>
                  </div>
                                                
                  <div class="message"></div>
                  <div class="modal-footer justify-content-between">
                     <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                     <button class="btn btn-flat btn-primary btn_save btn_action" id="btn_save_visit"  name="btn_save_visit" data-stype='stay' title="<?= cclang('save_button'); ?> (Ctrl+s)">
                        <i class="fa fa-save" ></i> <?= cclang('save_button'); ?>
                     </button>  
                  </div>
                 
                  <?= form_close(); ?>
               </div>
            </div>
         </div>
          <!-- /.modal-content -->
      </div>
        <!-- /.modal-dialog -->
   </div>
</section>
<!-- /.content -->
<script src="<?= BASE_ASSET; ?>ckeditor/ckeditor.js"></script>
<script>
$(document).ready(function(){
   CKEDITOR.replace('notes'); 
   var notes = CKEDITOR.instances.notes;

   $('#btn_save_visit').click(function(){
      $('.message').fadeOut();
      $('#notes').val(notes.getData());
   
      var form_amuco_visit = $('#form_amuco_visit');
      var data_post = form_amuco_visit.serializeArray();
      var save_type = $(this).attr('data-stype');

      data_post.push({name: 'save_type', value: save_type});
      console.log(data_post);
      $('.loading').show();
      
      $.ajax({
         url: BASE_URL + '/administrator/amuco_visits/add_save',
         type: 'POST',
         dataType: 'json',
         data: data_post,
      })
      .done(function(res) {
         
         $('form').find('.form-group').removeClass('has-error');
         $('.steps li').removeClass('error');
         $('form').find('.error-input').remove();
         if(res.success) {
            $('#modal-visit').modal('hide');
            location.reload();
            if (save_type == 'back') {
               window.location.href = res.redirect;
               return;
            }
   
            $('.message').printMessage({message : res.message});
            $('.message').fadeIn();
            resetForm();
            $('.chosen option').prop('selected', false).trigger('chosen:updated');
            notes.setData('');
                
         } else {
            if (res.errors) {
                
               $.each(res.errors, function(index, val) {
                  $('form #'+index).parents('.form-group').addClass('has-error');
                  $('form #'+index).parents('.form-group').find('small').prepend(`
                     <div class="error-input">`+val+`</div>
                     `);
               });
               $('.steps li').removeClass('error');
               $('.content section').each(function(index, el) {
                  if ($(this).find('.has-error').length) {
                     $('.steps li:eq('+index+')').addClass('error').find('a').trigger('click');
                  }
               });
            }
            $('.message').printMessage({message : res.message, type : 'warning'});
         }
    
      })
      .fail(function() {
         $('.message').printMessage({message : 'Error save data', type : 'warning'});
      })
      .always(function() {
         $('.loading').hide();
         $('html, body').animate({ scrollTop: $(document).height() }, 2000);
      });
    
      return false;
   }); /*end btn save**/

   $('#btn_save_contact').click(function(){
      $('.message').fadeOut();
         
      var form_amuco_contacts = $('#form_amuco_contacts');
      var data_post = form_amuco_contacts.serializeArray();
      var save_type = $(this).attr('data-stype');

      data_post.push({name: 'save_type', value: save_type});
    
      $('.loading').show();
    
      $.ajax({
         url: BASE_URL + '/administrator/amuco_contacts/add_save',
         type: 'POST',
         dataType: 'json',
         data: data_post,
      })
      .done(function(res) {
         $('form').find('.form-group').removeClass('has-error');
         $('.steps li').removeClass('error');
         $('form').find('.error-input').remove();
         if(res.success) {
           // $('#modal-contact').modal('hide');
           // location.reload();
            if (save_type == 'back') {
               window.location.href = res.redirect;
               return;
            }
   
            $('.message').printMessage({message : res.message});
            $('.message').fadeIn();
            resetForm();
            $('.chosen option').prop('selected', false).trigger('chosen:updated');
               
         } else {
            if (res.errors) {
                  
                  $.each(res.errors, function(index, val) {
                     $('form #'+index).parents('.form-group').addClass('has-error');
                     $('form #'+index).parents('.form-group').find('small').prepend(`
                        <div class="error-input">`+val+`</div>
                        `);
                  });
                  $('.steps li').removeClass('error');
                  $('.content section').each(function(index, el) {
                     if ($(this).find('.has-error').length) {
                        $('.steps li:eq('+index+')').addClass('error').find('a').trigger('click');
                     }
                  });
            }
         $('.message').printMessage({message : res.message, type : 'warning'});
         }
   
      })
      .fail(function() {
         $('.message').printMessage({message : 'Error save data', type : 'warning'});
      })
      .always(function() {
         $('.loading').hide();
         $('html, body').animate({ scrollTop: $(document).height() }, 2000);
      });
   
      return false;
   }); /*end btn save*/

});
</script>