
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Amuco_customer_request/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
     <br>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('amuco_customer_request') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('amuco_customer_request') ?></h3>
                     <!--h5 class="widget-user-desc"><?= cclang('list_all', [cclang('amuco_customer_request')]); ?>  <i class="label bg-yellow"><?= $amuco_customer_request_counts; ?>  <?= cclang('items'); ?></i></h5-->
                  </div>

                  <form name="form_amuco_customer_request" id="form_amuco_customer_request" action="<?= base_url('administrator/amuco_customer_request/list_request_pending_price'); ?>">
                  <br>

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th data-field="id"data-sort="1" data-primary-key="1"> <?= cclang('id') ?></th>
                           <th data-field="date_created"data-sort="1" data-primary-key="0"> <?= cclang('date_created') ?></th>
                           <th data-field="customer"data-sort="1" data-primary-key="0"> <?= cclang('Customer') ?></th>
                           <th data-field="sales_agent"data-sort="1" data-primary-key="0"> <?= cclang('Sales Agent') ?></th>
                           <th data-field="Recipients"data-sort="1" data-primary-key="0"> <?= cclang('Recipients') ?></th>
                           <th data-field="type" data-sort="1" data-primary-key="0"> <?= cclang('Type') ?></th>
                           <th data-field="Product"data-sort="1" data-primary-key="0"> <?= cclang('Product') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_amuco_customer_request">
                     <?php foreach($amuco_customer_request as $amuco_customer_request): 
                     foreach($amuco_details_customers_requests as $details): ?>
                        <tr>                           
                           <td><?= _ent($amuco_customer_request->id); ?></td> 
                           <td><?= _ent(date("Y-m-d", strtotime( $amuco_customer_request->date_created))); ?></td>
                           <td><?php if  ($amuco_customer_request->customer) {
                              echo anchor('administrator/amuco_customers/view/'.$amuco_customer_request->customer.'?popup=show', $amuco_customer_request->amuco_customers_name, ['class' => 'popup-view']); }?> </td>
                           <td><?php if  ($amuco_customer_request->sales_agent) {
                              echo anchor('administrator/aauth_users/view/'.$amuco_customer_request->sales_agent.'?popup=show', $amuco_customer_request->aauth_users_username, ['class' => 'popup-view']); }?> </td>
                           <?php 
                              if($details->purchasing_username != null):
                              ?>   
                                 <td><?= _ent($details->purchasing_username); ?></td> 
                                 <td><?= 'Office' ?></td> 
                              <?php else :?>
                                 <td><?= _ent($details->amuco_suppliers_name); ?></td> 
                                 <td><?= 'Supplier' ?></td> 
                              <?php endif; ?>
                              <td><?= _ent($details->amuco_products_name); ?></td> 
                             
                              
                              <td width="200">
                             
                             
                                 
                              <a href="<?= site_url('administrator/amuco_customer_request/view_add_price/' .$details->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view'); ?>
                            
                             
                              
                             
                           </td> 
                        </tr>
                      <?php endforeach; endforeach; ?>
                      <?php if ($amuco_details_customers_request_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Amuco Customer Request data is not available
                           </td>
                         </tr>
                      <?php endif; ?>

                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <!--div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div-->
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'id' ? 'selected' :''; ?> value="id">Id</option>
                           <option <?= $this->input->get('f') == 'date_created' ? 'selected' :''; ?> value="date_created">Date Created</option>
                           <option <?= $this->input->get('f') == 'status' ? 'selected' :''; ?> value="status">Status</option>
                           <option <?= $this->input->get('f') == 'customer' ? 'selected' :''; ?> value="customer">Customer</option>
                           <option <?= $this->input->get('f') == 'sales_agent' ? 'selected' :''; ?> value="sales_agent">Sales Agent</option>
                           <option <?= $this->input->get('f') == 'contact' ? 'selected' :''; ?> value="contact">Contact</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('amuco_customer_request/list_request_pending_price');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){

      
   
      $('.remove-data').click(function(){

         var url = $(this).attr('data-href');

         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
         },
         function(isConfirm){
            if (isConfirm) {
               document.location.href = url;            
            }
         });

         return false;
      });


      $('#apply').click(function(){

         var bulk = $('#bulk');
         var serialize_bulk = $('#form_amuco_customer_request').serialize();

         if (bulk.val() == 'delete') {
            swal({
               title: "<?= cclang('are_you_sure'); ?>",
               text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
               type: "warning",
               showCancelButton: true,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
               cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
               closeOnConfirm: true,
               closeOnCancel: true
            },
            function(isConfirm){
               if (isConfirm) {
                  document.location.href = BASE_URL + '/administrator/amuco_customer_request/delete?' + serialize_bulk;      
               }
            });

         return false;

         } else if(bulk.val() == '')  {
            swal({
               title: "Upss",
               text: "<?= cclang('please_choose_bulk_action_first'); ?>",
               type: "warning",
               showCancelButton: false,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "Okay!",
               closeOnConfirm: true,
               closeOnCancel: true
            });

         return false;
         }

         return false;

      });/*end appliy click*/


      //check all
      var checkAll = $('#check_all');
      var checkboxes = $('input.check');

      checkAll.on('ifChecked ifUnchecked', function(event) {   
         if (event.type == 'ifChecked') {
               checkboxes.iCheck('check');
         } else {
               checkboxes.iCheck('uncheck');
         }
      });

      checkboxes.on('ifChanged', function(event){
         if(checkboxes.filter(':checked').length == checkboxes.length) {
               checkAll.prop('checked', 'checked');
         } else {
               checkAll.removeProp('checked');
         }
         checkAll.iCheck('update');
      });
      initSortable('amuco_customer_request', $('table.dataTable'));
   }); /*end doc ready*/
</script>