
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<style>
   /* Style the buttons that are used to open and close the accordion panel */
.accordion {
  
  transition: 0.4s;
}

/* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
.active, .accordion:hover {
  background-color: #ccc;
}

/* Style the accordion panel. Note: hidden by default */
.panel {
  padding: 0 18px;
  background-color: white;
  display: none;
  overflow: hidden;
}

</style>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Amuco Customer Request      <small><?= cclang('detail', ['Amuco Customer Request']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_customer_request'); ?>">Amuco Customer Request</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Amuco Customer Request</h3>
                     <h5 class="widget-user-desc">Detail Amuco Customer Request</h5>
                     <h3 class="widget-user-username"><?= 'ID: '.$amuco_customer_request->id ?></h3> 
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_amuco_customer_request" id="form_amuco_customer_request" >
                  
                  <div class="row">                        
                     <div class="col-md-6 col-sm-6" > 
                        <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label">Status </label>

                           <div class="col-sm-8">
                           <input readonly type="text" class="form-control" name="status" id="status" value=" <?= _ent($amuco_customer_request->status); ?>">
                           </div>
                        </div>        
                     </div>   
                     <div class="col-md-6 col-sm-6" >      
                        <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">Date Created </label>

                              <div class="col-sm-8">
                                 <div class="input-group date col-sm-8">
                                    <input readonly type="text" class="form-control pull-right datepicker" name="created"  id="created" value=" <?= _ent($amuco_customer_request->date_created); ?>">
                                 </div>
                                
                              </div>
                        </div>
                     </div>
                  </div>                  
                   
                  <div class="row">                        
                     <div class="col-md-6 col-sm-6" >               
                        <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">Customer </label>
                              <div class="col-sm-8">
                                 <input readonly type="text" class="form-control" name="customer" id="customer" value=" <?= _ent($amuco_customer_request->amuco_customers_name); ?>">
                              </div>
                        </div>
                     </div>  
                     <div class="col-md-6 col-sm-6" > 
                        <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label">Destination Port </label>
                           <div class="col-sm-8">
                           <input readonly type="text" class="form-control" name="customer" id="customer" value=" <?= _ent($amuco_customer_request->amuco_destination_port_name); ?>">
                           </div>
                        </div> 
                     </div>   
                  </div>   
                  <div class="row">                        
                     <div class="col-md-6 col-sm-6" >               
                        <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">Contact </label>
                              <div class="col-sm-8">
                                 <input readonly type="text" class="form-control" name="contact" id="contact" value=" <?= _ent($amuco_customer_request->amuco_contacts_name); ?>">
                              </div>
                        </div>
                     </div>  
                     <div class="col-md-6 col-sm-6" > 
                        <div class="form-group ">
                           <label for="content" class="col-sm-2 control-label">Incoterm </label>
                           <div class="col-sm-8">
                           <input readonly type="text" class="form-control" name="incoterm" id="incoterm" value=" <?= _ent($amuco_customer_request->amuco_incoterm_name); ?>">
                           </div>
                        </div> 
                     </div>   
                  </div>   
                  <div class="row">                        
                     <div class="col-md-6 col-sm-6" >               
                        <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">Sales Agent </label>
                              <div class="col-sm-8">
                                 <input readonly type="text" class="form-control" name="sales" id="sales" value=" <?= _ent($amuco_customer_request->aauth_users_username); ?>">
                              </div>
                        </div>
                     </div>  
                     <div class="col-md-6 col-sm-6" > 
                        <div class="form-group ">
                           <label for="combinate_container" class="col-sm-2 control-label">Combined  Container </label>
                           <div class="col-sm-8">
                           <br>
                              <div class="col-md-2 padding-left-0">
                                    <label>
                                       <input type="radio" class="flat-red" name="combinate_container" id="combinate_container"  value="1" <?= $amuco_customer_request->combinate_container == "1" ? "checked" : ""; ?>>
                                       Yes
                                    </label>
                              </div>
                              <div class="col-md-14">
                                    <label>
                                       <input type="radio" class="flat-red" name="combinate_container" id="combinate_container"  value="0" <?= $amuco_customer_request->combinate_container == "0" ? "checked" : ""; ?>>
                                       No
                                    </label>
                              </div>
                           </div>
                        </div>
                     </div>  
                  </div>                       
                  <div class="row">                       
                     <div class="col-md-6 col-sm-6" >                                       
                     <div class="form-group ">
                        <label for="remarks" class="col-sm-2 control-label">Remarks </label>
                        <div class="col-sm-8">
                           <textarea style="resize:none" readonly id="remarks" name="remarks" rows="5" cols="65"> <?= set_value('remarks', $amuco_customer_request->remarks); ?></textarea>
                        </div>
                     </div>
                     </div>
                     <div class="col-md-6 col-sm-6" style="display:none"> 
                     <div class="form-group ">
                        <label for="date_created" class="col-sm-2 control-label">RSD </label>
                        <div class="col-sm-10">
                           <div class="input-group date col-sm-8">
                           <input type="text" class="form-control pull-right datepicker" name="rsd"  placeholder="Date RSD" id="rsd" value="<?= set_value( date("Y-m-d"), $amuco_customer_request->RSD); ?>">
                           </div>
                           <small class="info help-block"></small>
                        </div>
                     </div>
                     </div> 
                  </div>  
                  <br>
                  <br>     
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<section class="content">
    <div class="row" > 
      <div class="col-md-12">
        <div class="box box-warning">
          <div class="box-body ">
            <div class="box box-widget widget-user-2">
              <form name="form_amuco_details_customers_request" id="form_amuco_details_customers_request" action="<?= base_url('administrator/amuco_details_customers_request/index'); ?>">
                <div class="table-responsive"> 
                  <table class="table table-hover table-striped dataTable" >
                     <thead>
                        <tr>
                           <!--th><input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all"></th-->
                           <th data-field="customer_request_id"data-sort="1" data-primary-key="0"> <?= cclang('request_id') ?></th>
                           <th data-field="product_id"data-sort="1" data-primary-key="0"> <?= cclang('Product') ?></th>
                           <!--th data-field="customer_request_id"data-sort="1" data-primary-key="0"> <?= cclang('customer_request_id') ?></th-->
                           <th data-field="supplier"data-sort="1" data-primary-key="0"> <?= cclang('Supplier') ?></th>
                           <th data-field="office"data-sort="1" data-primary-key="0"> <?= cclang('Office') ?></th>
                           <!--th data-field="quantity"data-sort="1" data-primary-key="0"> <?= cclang('quantity') ?></th-->
                           <th data-field="status"data-sort="1" data-primary-key="0"> <?= cclang('status') ?></th>
                           <!--th data-field="packing"data-sort="1" data-primary-key="0"> <?= cclang('packing') ?></th-->
                           <th>Action</th>                        
                        </tr>
                     </thead>
                     <tbody id="tbody_amuco_details_customers_request">
                        <?php foreach($amuco_details_customers_requests as $amuco_details_customers_request): ?>
                        <tr data-toggle="collapse" data-target="#accordion_<?= $amuco_details_customers_request->id ?>" class="clickable">
                           <td><?= _ent($amuco_details_customers_request->customer_request_id); ?></td>
                           <td><?php if  ($amuco_details_customers_request->product_id) {
                           echo anchor('administrator/amuco_products/view/'.$amuco_details_customers_request->product_id.'?popup=show', $amuco_details_customers_request->amuco_products_name, ['class' => 'popup-view']); }?> </td>
                              
                        
                           <td><?= _ent($amuco_details_customers_request->amuco_suppliers_name); ?></td>  
                           <td><?= _ent($amuco_details_customers_request->purchasing_username); ?></td>
                           <td><?= $amuco_details_customers_request->status; ?></td> 
                           <?php if($current_page == 'view'): ?>
                           <td width="200" >
                              <a class="label-default add-price" id="btn_edit" data-stype='back' title="edit amuco_customer_request (Ctrl+e)" href="<?= site_url('administrator/amuco_customer_request/edit/'.$amuco_customer_request->id); ?>"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?> </a>
                           </td>
                           <?php else:?>
                           <td width="200">
                           
                           <a  data-id="<?= $amuco_details_customers_request->id ; ?>" 
                                 data-request_id ="<?=  $amuco_details_customers_request->customer_request_id; ?>"
                                 data-product_name ="<?=  $amuco_details_customers_request->amuco_products_name; ?>"
                                 data-product_id ="<?=  $amuco_details_customers_request->product_id; ?>"
                                 data-office ="<?= $amuco_details_customers_request->purchasing_username; ?>"
                                 data-contact_id ="<?= $amuco_details_customers_request->contacts ?>"
                                 data-quantity ="<?= $amuco_details_customers_request->quantity ?>"
                                 data-unit ="<?= $amuco_details_customers_request->amuco_unit_types_name; ?>"
                                 data-unit_id ="<?= $amuco_details_customers_request->unit; ?>"
                                 data-fcl ="<?= $amuco_details_customers_request->fcl; ?>"
                                 data-fcl_option ="<?= $amuco_details_customers_request->fcl_option; ?>"
                                 data-fcl_type ="<?= $amuco_details_customers_request->type_fcl; ?>"
                                 data-weigth ="<?= $amuco_details_customers_request->weight; ?>"
                                 data-packing ="<?= $amuco_details_customers_request->packing; ?>"
                                 data-material ="<?= $amuco_details_customers_request->material; ?>"
                                 data-unit_pack ="<?= $amuco_details_customers_request->unit_pack; ?>"
                                 data-pallets ="<?= $amuco_details_customers_request->pallets; ?>"
                                 data-etd ="<?= $amuco_details_customers_request->ETD; ?>"
                                 data-eta ="<?= $amuco_details_customers_request->ETA; ?>"
                                 data-remarks ="<?= $amuco_details_customers_request->specific_remarks; ?>"                             
                                 id="add-price_<?=  $amuco_details_customers_request->id ?>" href="javascript:void(0);" class="label-default add-price"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                           
                           </td> 
                           <?php endif; ?>                       
                        </tr>
                        <?php endforeach; ?>
                        <?php if (count($amuco_details_customers_requests) == 0) :?>
                        <tr>
                           <td colspan="100">Amuco Details Customers Request data is not available</td>
                        </tr>
                        <?php endif; ?>
                     </tbody>
                  </table>
                </div>
               </form>
               <div class="view-nav">
                        <?php is_allowed('amuco_customer_request_update', function() use ($amuco_customer_request){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit amuco_customer_request (Ctrl+e)" href="<?= site_url('administrator/amuco_customer_request/edit/'.$amuco_customer_request->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Amuco Customer Request']); ?> </a>
                        <?php }) ?>
                        <?php if($current_page == 'view'): ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_customer_request/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Customer Request']); ?></a>
                        <?php endif?>
                        <?php if($current_page == 'view_office'): ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_dashboard_office/request_pendig/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Customer Request Pending']); ?></a>
                        <?php endif?>
               </div>
            </div>
            <hr>               
          </div>
        </div>
      </div>
    </div>
</section>
<!-- /.content -->
<section>
   <div class="modal fade" id="modal-add-price">
      <div class="modal-dialog modal-lg">
         <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
               </button>
            </div>
            <div class="modal-body">
               <div class="row" >
                  <div class="box box-warning">
                     <div class="box-body ">
                        <div class="box box-widget widget-user-2">
                           <div class="widget-user-header ">
                              <div class="widget-user-image">
                                 <img class="img-circle" src="<?= BASE_ASSET; ?>/img/add2.png" alt="User Avatar">
                              </div>
                              <h3 class="widget-user-username">Amuco Request </h3>
                              <h5 class="widget-user-desc"><?= cclang('Add Price', ['Amuco Request']); ?></h5>
                              <h3 class="widget-user-username"><?= 'ID: '.$amuco_customer_request->id ?></h3> 
                           </div>
                        </div>
                        
                            <?= form_open('', [
                            'name'    => 'form_amuco_details_request_office', 
                            'class'   => 'form-horizontal form-step', 
                            'id'      => 'form_amuco_details_request_office', 
                            'enctype' => 'multipart/form-data', 
                            'method'  => 'POST'
                            ]); ?>
                           <div class="container">
                              <div class="row"> 
                                 <div class="col-md-3" >                          
                                    <label for="content" class="col-sm-4">Product: </label>
                                    <p id="product_name_label"> </p>
                                 </div>
                                 <div class="col-md-3" >                          
                                    <label for="content" class="col-sm-4">Customer: </label>
                                    <p id="customer_label"><?= $amuco_customer_request->amuco_customers_name ?> </p>
                                 </div> 
                                 <div class="col-md-3" >                          
                                    <label for="content" class="col-sm-3">ETA: </label>
                                    <p id="eta_label"> </p>
                                 </div>   
                              </div>
                              <div class="row"> 
                                 <div class="col-md-3" >                          
                                    <label for="content" class="col-sm-4">Incoterm: </label>
                                    <p id="incoterm_label"> <?= $amuco_customer_request->amuco_incoterm_name ?> </p>
                                 </div> 
                                 <div class="col-md-3" >                          
                                    <label for="content" class="col-sm-7">Destination Port: </label>
                                    <p id="destination_label"><?= $amuco_customer_request->amuco_destination_port_name ?> </p>
                                 </div>
                                 <div class="col-md-4" >   
                                    <label for="combinate_container" class="col-sm-3 ">Combined  Container </label>
                                    <div class="col-sm-8">
                              
                                       <div class="col-md-4 padding-left-0">
                                             <label>
                                                <input  type="radio" class="flat-red" name="combinate_container" id="combinate_container"  value="1" <?= $amuco_customer_request->combinate_container == "1" ? "checked" : ""; ?>>
                                                Yes
                                             </label>
                                       </div>
                                       <div class="col-md-14">
                                             <label>
                                                <input  type="radio" class="flat-red" name="combinate_container" id="combinate_container"  value="0" <?= $amuco_customer_request->combinate_container == "0" ? "checked" : ""; ?>>
                                                No
                                             </label>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                              <div class="row"> 
                                 <div class="col-md-6" >                          
                                    <label for="content" class="col-sm-2">Remarks: </label>
                                    <p id="remarks_label"><?= $amuco_customer_request->remarks ?> </p>
                                 </div> 
                              </div>
                           </div>
                           <hr>
                           <div class="row" style="display:none">  
                              <div class="col-md-6" >                          
                                 <div class="form-group ">
                                    <label for="content" class="col-sm-3 control-label">Customer Request Id </label>
                                    <div class="col-sm-8">
                                       <input readonly type="text" class="form-control" name="customer_request_id" id="request_id"  value=" <?= _ent($amuco_details_customers_request->customer_request_id); ?>">
                                       <input readonly type="text" class="form-control" name="purchasing" id="purchasing"  value=" <?= _ent($amuco_details_customers_request->purchasing); ?>">
                                    </div>
                                 </div>
                              </div>  
                              <div class="col-md-6">                          
                                 <div class="form-group ">
                                    <label for="content" class="col-sm-2 control-label">Product  </label>
                                    <div class="col-sm-8">
                                       <input  readonly type="text" class="form-control" name="product_name" id="product_name_modal" >
                                       <input   type="hidden" class="form-control" name="product_id" id="product_id"  >
                                    </div>
                                 </div>
                              </div> 
                           </div>                 
                           <div class="row">  
                              <div class="col-md-3">                         
                                 <div class="form-group ">
                                    <label for="quantity" class="col-sm-5 control-label">Quantity </label>
                                    <div class="col-sm-7">
                                       <input  type="text" class="form-control" name="quantity" id="quantity"  value="">
                                    </div>
                                 </div>
                              </div>  
                              <div class="col-md-3">                
                                 <div class="form-group ">
                                    <label for="unit" class="col-sm-3 control-label">Unit </label>
                                    <div class="col-sm-9">
                                       <select  class="form-control chosen chosen-select-deselect" name="unit" id="unit" data-placeholder="Select Unit" >
                                          <option value=""></option>
                                          <?php foreach (db_get_all_data('amuco_unit_types') as $row): ?>
                                          <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                          <?php endforeach; ?>  
                                       </select>
                                    </div>
                                 </div>
                              </div> 
                              <div class="col-md-3"> 
                                 <div class="form-group ">
                                    <label for="content" class="col-sm-1 control-label">Fcl </label>
                                    <div class="col-sm-4">
                                       <input   type="text" class="form-control" name="fcl" id="fcl"  value="">
                                    </div>
                                    <div class="col-md-3 col-sm-3" > 
                                       <div class="form-group ">
                                          <div class="row">
                                          <div class="col-md-4  fcl_option_1">
                                                <label id="fcl_option_1">
                                                   <input type="radio" class="flat-red" name="fcl_option" id="fcl_option_1"  value="20" >
                                                   20'
                                                </label>
                                          </div>
                                          <div class="col-md-3  fcl_option_2" >
                                                <label id ="fcl_option_2">
                                                   <input type="radio" class="flat-red" name="fcl_option" id="fcl_option"  value="40" >
                                                   40'
                                                </label>
                                          </div>
                           
                                          </div> 
                                       </div>
                                    </div> 
                                 </div>  
                              </div>
                              <div class="col-md-3"> 
                                 <div class="form-group ">
                                    <label for="Type" class="col-sm-2 control-label">Type</label>
                                    <div class="col-sm-8">
                                       <select  class="form-control chosen chosen-select-deselect" name="type_fcl" id="type_FCL" data-placeholder="Select Type" >
                                             <option value=""></option>
                                             <option value="NOR">NOR</option>
                                             <option value="HCube">HCube</option>
                                             <option value="Standard">Standard</option>
                                       </select>
                                    </div>
                                 </div>
                              </div>         
                           </div> 
                           <div class="row"> 
                              <div class="col-md-2" >                                       
                                 <div class="form-group ">
                                    <label for="weight" class="col-sm-6 control-label">Weight/Vol </label>
                                    <div class="col-sm-6">
                                       <input type="text" class="form-control" name="weight" id="weight"  value="<?= set_value('weight'); ?>">
                                    </div>
                                 </div>
                              </div>  
                              <div class="col-md-2" >                                        
                                 <div class="form-group ">
                                    <label for="unit" class="col-sm-2 control-label">Unit </label>
                                    <div class="col-sm-9">
                                       <select  class="form-control chosen chosen-select-deselect" name="unit_pack" id="unit_pack" data-placeholder="Select Unit" >
                                             <option value=""></option>
                                             <?php foreach (db_get_all_data('amuco_unit_types') as $row): ?>
                                             <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                             <?php endforeach; ?>  
                                       </select>
                                    </div>
                                 </div>
                              </div> 
                              <div class="col-md-3" >                                  
                                 <div class="form-group ">
                                    <label for="packing" class="col-sm-3    control-label">Shape </label>
                                    <div class="col-sm-8">
                                       <select  class="form-control " name="shape" id="shape" data-placeholder="Select Packing" >
                                          <option value=""></option>
                                          <?php foreach (db_get_all_data('amuco_packing') as $row): ?>
                                          <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                          <?php endforeach; ?>  
                                       </select>
                                    </div>
                                 </div>
                              </div>
                              <div class="col-md-3" >                                       
                                 <div class="form-group ">
                                    <label for="material" class="col-sm-3 control-label">Material </label>
                                    <div class="col-sm-8">
                                       <select  class="form-control " name="material" id="material" data-placeholder="Select material" >
                                             <option value=""></option>
                                             <?php foreach (db_get_all_data('amuco_material') as $row): ?>
                                             <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                             <?php endforeach; ?>  
                                       </select>
                                    </div>
                                 </div>
                              </div> 
                              <div class="col-md-2" >                       
                                 <div class="form-group">
                                    <label  class="col-sm-4 "> Pallets</label>
                                    <div  class="col-sm-8 pallets" >
                                       <input type="checkbox" class="form-control flat-red" name="pallets" id="pallets"  value="0" >
                                    </div>
                                 </div>  
                              </div>  
                              
                           </div>  
                           <hr> 
                           <div class="row">
                              <div class="col-md-3">                         
                                 <div class="form-group ">
                                    <label for="price" class="col-sm-5 ">Unit Price FOB/FCA </label>
                                    <div class="col-sm-7">
                                       <input  type="text" class="form-control" name="price_fob" id="price_fob"  value="">
                                    </div>
                                 </div>
                              </div>  
                              <div class="col-md-3">                         
                                 <div class="form-group ">
                                    <label for="freight" class="col-sm-4 ">Total Freight</label>
                                    <div class="col-sm-8">
                                       <input  type="text" class="form-control" name="total_freight" id="total_freight"  value="">
                                    </div>
                                 </div>
                              </div>   
                              <div class="col-md-3">                         
                                 <div class="form-group">
                                    <label for="price" class="col-sm-6">Unit Price $</label>
                                    <div class="col-sm-6" style="margin-left:-10%">
                                       <input  type="text" class="form-control" name="total_price" id="total_price"  value="">
                                    </div>
                                 </div>
                              </div>  
                              <div class="col-md-3">                         
                                 <div class="form-group ">
                                    <label for="price" class="col-sm-4">Incoterm</label>
                                    <div class="col-sm-8">
                                       <select  class="form-control chosen chosen-select-deselect" name="supplier_incoterm" id="incoterm"  >
                                          <option value=""></option>
                                          <?php foreach (db_get_all_data('amuco_incoterm') as $row): ?>
                                          <option  value="<?= $row->id ?>"><?= $row->name; ?></option>
                                          <?php endforeach; ?>  
                                       </select>
                                    </div>
                                 </div>
                              </div>  
                           </div>
                         
                           <div class="row">
                              <div class="col-md-4">                         
                                 <div class="form-group ">
                                    <label for="supplier" class="col-sm-3 control-label">Supplier </label>
                                    <div class="col-sm-9">
                                       <select  class="form-control chosen chosen-select-deselect" name="supplier" id="suppliers" data-placeholder="Select Destination Port" >
                                            <option value=""></option>
                                            <?php foreach (db_get_all_data('amuco_suppliers') as $row): ?>
                                            <?php foreach (db_get_all_data('amuco_classification_suppliers') as $row_cla): 
                                                 if($row->classification_id == $row_cla->id && $row_cla->name == "Purchasing Office" ):
                                             ?>
                                                   <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                                 <?php endif; endforeach;  endforeach;?>  
                                        </select>
                                    </div>
                                 </div>
                              </div>
                              <div class="col-md-8">                         
                                 <div class="form-group ">
                                    <label for="incoterm" class="col-sm-1 control-label">Brand </label>
                                    <div class="col-sm-10">
                                       <input  type="text" class="form-control" name="brand" id="brand"  value="">
                                    </div>
                                 </div>
                              </div>   
                           </div>
                           <div class="row">
                              <div class="col-md-3">                         
                                 <div class="form-group ">
                                    <label for="payment" class="col-sm-4">Payments Terms</label>
                                    <div class="col-sm-8">
                                       <select  class="form-control chosen chosen-select-deselect" name="payment_terms" id="payment_terms" data-placeholder="Select Destination Port" >
                                            <option value=""></option>
                                            <?php foreach (db_get_all_data('amuco_payments_terms_suppliers') as $row): ?>
                                            <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                            <?php endforeach; ?>  
                                        </select>
                                    </div>
                                 </div>
                              </div> 
                              <div class="col-md-3">                         
                                 <div class="form-group ">
                                    <label for="incoterm" class="col-sm-4">Supplier Incoterm</label>
                                    <div class="col-sm-8">
                                       <select  class="form-control chosen chosen-select-deselect" name="supplier_incoterm" id="incoterm"  >
                                          <option value=""></option>
                                          <?php foreach (db_get_all_data('amuco_incoterm') as $row): ?>
                                          <option  value="<?= $row->id ?>"><?= $row->name; ?></option>
                                          <?php endforeach; ?>  
                                       </select>
                                    </div>
                                 </div>
                              </div>
                              <div class="col-md-3">                         
                                 <div class="form-group ">
                                    <label for="price" class="col-sm-4">Shipping Port</label>
                                    <div class="col-sm-8">
                                       <select  class="form-control chosen chosen-select-deselect" name="shipping_port" id="shipping_port" data-placeholder="Select Destination Port" >
                                            <option value=""></option>
                                            <?php foreach (db_get_all_data('amuco_destination_port') as $row): ?>
                                            <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                            <?php endforeach; ?>  
                                        </select>
                                    </div>
                                 </div>
                              </div> 
                              <div class="col-md-3">                         
                                 <div class="form-group ">
                                    <label for="date_created" class="col-sm-3">Delivery Date </label>
                                    <div class="col-sm-6">
                                       <div class="input-group date col-sm-12">
                                          <input type="text" class="form-control pull-right datepicker" name="ETD"  placeholder="Date ETD" id="etd" value="<?php echo date("Y-m-d");?>">
                                       </div>
                                    </div>
                                 </div>
                              </div>  
                           </div> 
                                
                           <div class="row">
                              <div class="col-md-4">                         
                                 <div class="form-group ">
                                    <label for="date_created" class="col-sm-4 control-label">Valid Untill</label>
                                    <div class="col-sm-8">
                                       <div class="input-group date col-sm-12">
                                          <input type="text" class="form-control pull-right datepicker" name="valid_untill"  placeholder="Date " id="valid_untill" value="<?php echo date("Y-m-d");?>">
                                       </div>
                                    </div>
                                 </div>
                              </div> 
                              
                              <div class="col-md-4">                         
                                 <div class="form-group ">
                                    <label for="price" class="col-sm-6 control-label">Analysis Standard</label>
                                    <div class="col-sm-6">
                                       <input  type="text" class="form-control" name="analysis_standard" id="analysis_standard"  value="">
                                    </div>
                                 </div>
                              </div>
                              <div class="col-md-4">    </div>   
                           </div>

                           <div class="row">
                              <div class="col-md-12">                         
                                 <div class="form-group ">
                                    <label for="incoterm" class="col-sm-1 control-label">Remarks </label>
                                    <div class="col-sm-11">
                                       <textarea id="comments" name="comments" rows="3" cols="80"> <?= set_value('comments'); ?></textarea>
                                    </div>
                                 </div>
                              </div>  
                           </div>
                           <div class="modal-footer justify-content-between">
                              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                              <button class="btn btn-flat btn-primary  btn_action" id="btn_new_offer"  name="btn_new_offer" data-stype='stay' data-action="clear" title="<?= cclang('save_button'); ?> (Ctrl+s)">
                                 <i class="fa fa-add" ></i> <?= cclang('Clear Data'); ?>
                              </button>
                              <button class="btn btn-flat btn-primary  btn_action" id="btn_save_offer"  name="btn_save_offer" data-stype='stay 'data-action="save"  title="<?= cclang('save_button'); ?> (Ctrl+s)">
                                 <i class="fa fa-save" ></i> <?= cclang('Save'); ?>
                              </button>  
                              <button class="btn btn-flat btn-primary  btn_action" id="btn_send_offer"  name="btn_send_offer" data-stype='stay' data-action="send"  title="<?= cclang('save_button'); ?> (Ctrl+s)">
                                 <i class="fa fa-send" ></i> <?= cclang('Send Offer'); ?>
                              </button>
                           </div>
                        </div>
                     <div>   
                  </div>
               <div>   
            <div>   
         </div>
      <div> 
   <div>         
</section>

<script>
$(document).ready(function(){
   $('#price_fob').change(function(){
      if($(this).val() > 0){
         let freight = 0;
         let price_fob = parseFloat($(this).val());
         if(parseFloat($('#total_freight').val()) > 0){
           freight = parseFloat($('#total_freight').val());
           $('#total_price').val(price_fob + freight);
         }else{
            if(parseFloat($('#total_price').val()) > 0){
               freight = parseFloat($('#total_price').val() - price_fob);
               $('#total_freight').val(freight);
            }else{
               $('#total_price').val(price_fob + freight);
            }
         }
      }else{
         if(parseFloat($('#total_freight').val()) > 0){
           freight = parseFloat($('#total_freight').val());
           $('#total_price').val(freight);
         }else{
            $('#total_price').val(0);
         }
      }
      var number =  $('#price_fob').val();
      number =  number.replace(/\D/g, "").replace(/\B(?=(\d{3})+(?!\d)\.?)/g, ",");
      alert(number);
      $('#price_fob').val(number);
   }) ;
   $('#total_freight').change(function(){
      if($(this).val() > 0){
        let price_fob = 0;
        freight = parseFloat($('#total_freight').val());
        if($('#price_fob').val() > 0){
           price_fob = parseFloat($(this).val());
           $('#total_price').val(price_fob + freight);
        }else{
            if( $('#total_price').val() > 0){
               total = parseFloat($('#total_price').val());
               $('#price_fob').val(total - freight);
            }else{
               $('#total_price').val(freight);
            }
         }
      }else{
         if($('#price_fob').val() > 0){
            price_fob = parseFloat($('#price_fob').val());
            $('#total_price').val(price_fob);
         }else{
            $('#total_price').val(0);
         }   
      }
   }) ;
   $('#total_price').change(function(){
      if($('#price_fob').val() > 0 && $('#price_freight').val() > 0){
            alert("Price FOB and Total Freight are greater than 0");
            price_fob = parseFloat($('#price_fob').val());
            freight = parseFloat($('#total_freight').val());
            $('#total_price').val( price_fob + freight);
      }else{
         if($(this).val() > 0){
            let price_fob = 0;
            let freight = 0;
            total_price = parseFloat($('#total_price').val());
            if($('#price_fob').val() > 0 ){
               price_fob = parseFloat($('#price_fob').val());
               $('#total_freight').val( total_price - price_fob );
            }else{
               if( $('#total_freight').val() > 0){
                  freight = parseFloat($('#total_freight').val());
                  $('#price_fob').val(total_price - freight);
               }else{
                  $('#total_price').val(total_price);
               }
            }
         }else{
            if($('#price_fob').val() > 0){
               price_fob = parseFloat($('#price_fob').val());
               $('#total_price').val(price_fob);
            }else{
               freight = parseFloat($('#total_freight').val());
               $('#total_price').val(freight); 
            }
         }
      }   
      
   }) ;

   $('.add-price').click(function(){
     // alert($(this).data('product_name'));
      $('#request_id_label').html($(this).data('request_id'));
      $('#request_id').val($(this).data('request_id'));
      $('#product_id').val($(this).data('product_id'));
      $('#product_id_label').html($(this).data('product_id'));
      $('#product_name_label').html($(this).data('product_name'));
      $('#quantity_label').html($(this).data('quantity'));
      $('#quantity').val($(this).data('quantity'));
      $('#unit_label').html($(this).data('unit'));
      $('#unit').val($(this).data('unit'));
      $("#unit option[value='"+ $(this).data('unit') +"']").attr("selected",true);
      $('#unit option').prop('selected', true).trigger('chosen:updated');
      $('#fcl_label').html($(this).data('fcl'));
      $('#fcl').val($(this).data('fcl'));
      $('#fcl_option_label').html($(this).data('fcl_option'));
      $('#fcl_option').val($(this).data('fcl_option'));
     // alert($(this).data('fcl_option'));
      if($(this).data('fcl_option') == 20){
         $('.fcl_option_1').find('.iradio_minimal-red').addClass('checked');
         
      }else{
          if($(this).data('fcl_option') == 40){
            $('.fcl_option_2').find('.iradio_minimal-red').addClass('checked');
          }
      }
      $('#type_fcl').html($(this).data('fcl_type'));
      $("#type_FCL option[value='"+ $(this).data('fcl_type').toString()+"']").attr("selected",true);
      $('#type_FCL option').prop('selected', true).trigger('chosen:updated');
      $('#weight_label').html($(this).data('weight'));
      $('#weight').val($(this).data('weight'));
      $('#weight_unit_label').html($(this).data('unit_pack'));
      $("#unit_pack option[value='"+ $(this).data('unit_pack') +"']").attr("selected",true);
      $('#unit_pack option').prop('selected', true).trigger('chosen:updated');
      $('#packing_label').html($(this).data('packing'));
      $("#shape option[value='"+ $(this).data('packing') +"']").attr("selected",true);
      $('#shape option').prop('selected', true).trigger('chosen:updated');
      $('#material_label').html($(this).data('material'));
      $("#material option[value='"+ $(this).data('material') +"']").attr("selected",true);
      $('#material option').prop('selected', true).trigger('chosen:updated');
      $('#pallets_label').html($(this).data('pallets'));
      if($(this).data('pallets') == 1){
         $('.pallets').find('.icheckbox_minimal-red').addClass('checked');
         
      }
      $('#remarks_label').html($(this).data('remarks'));
      $('#remarks').val($(this).data('remarks'));
      $('#etd_label').html($(this).data('etd'));
      $('#etd').val($(this).data('etd'));
      $('#eta_label').html($(this).data('eta'));
    
      $('#modal-add-price').modal('show');

   });

   $('#btn_save_offer').click(function(){
        $('.message').fadeOut();
        var form_amuco_details_request_office = $('#form_amuco_details_request_office');
        var data_post = form_amuco_details_request_office.serializeArray();
        var save_type = $(this).attr('data-stype');
        var save_status = $(this).attr('data-action');

        data_post.push({name: 'save_type', value: save_type});
        data_post.push({name: 'save_status', value: save_status});
    
        $('.loading').show();
    
        $.ajax({
          url: BASE_URL + '/administrator/amuco_details_request_office/add_save',
          type: 'POST',
          dataType: 'json',
          data: data_post,
        })
        .done(function(res) {
          $('form').find('.form-group').removeClass('has-error');
          $('.steps li').removeClass('error');
          $('form').find('.error-input').remove();
          if(res.success) {
            $('#form_amuco_details_request_office').trigger("reset");
            $('#modal-add-price').modal('hide');
         
    
            $('.message').printMessage({message : res.message});
            $('.message').fadeIn();
            resetForm();
            $('.chosen option').prop('selected', false).trigger('chosen:updated');
                
          } else {
            if (res.errors) {
                
                $.each(res.errors, function(index, val) {
                    $('form #'+index).parents('.form-group').addClass('has-error');
                    $('form #'+index).parents('.form-group').find('small').prepend(`
                      <div class="error-input">`+val+`</div>
                      `);
                });
                $('.steps li').removeClass('error');
                $('.content section').each(function(index, el) {
                    if ($(this).find('.has-error').length) {
                        $('.steps li:eq('+index+')').addClass('error').find('a').trigger('click');
                    }
                });
            }
            $('.message').printMessage({message : res.message, type : 'warning'});
          }
    
        })
        .fail(function() {
          $('.message').printMessage({message : 'Error save data', type : 'warning'});
        })
        .always(function() {
          $('.loading').hide();
          $('html, body').animate({ scrollTop: $(document).height() }, 2000);
        });
    
        return false;
      }); /*end btn save*/
});
</script>