
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
         <small><?= cclang(' ',' '); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_suppliers_bank'); ?>">Amuco Suppliers Bank</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Amuco Suppliers Bank</h3>
                     <h5 class="widget-user-desc">Detail Amuco Suppliers Bank</h5>
                     <hr>
                  </div>
              
                 
                  <div class="form-horizontal form-step" name="form_amuco_suppliers_bank" id="form_amuco_suppliers_bank" >
                     <div class="row" >                 
                        <div class="form-group ">
                            <label for="beneficiary_wires" class="col-sm-2 control-label">Beneficiary Wires </label>
                            <div class="col-sm-8">
                                <input readonly type="text" class="form-control" name="beneficiary_wires" id="beneficiary_wires" placeholder="Beneficiary Wires" value="<?= set_value('beneficiary_wires', $amuco_suppliers_bank->beneficiary_wires); ?>"> 
                            </div>
                        </div>
                     </div>
                     <div class="row" >    
                        <div class="tab-pane" > 
                           <div class="col-md-6">
                            
                              <div class="box-footer no-padding">
                                 <div style="text-align:center">
                                       <h4 class="">Beneficiary Bank</h4>
                                 </div>
                                 <div class="form-group ">
                                    <label for="beneficiary_bank" class="col-sm-2 control-label">Bank </label>
                                    <div class="col-sm-8">
                                       <input readonly type="text" class="form-control" name="beneficiary_bank" id="beneficiary_bank" placeholder="Beneficiary Bank" value="<?= set_value('beneficiary_bank', $amuco_suppliers_bank->beneficiary_bank); ?>">   
                                    </div>
                                 </div>
                                                 
                                 <div class="form-group ">
                                    <label for="account_number" class="col-sm-2 control-label">Account  
                                    </label>
                                    <div class="col-sm-8">
                                       <input readonly type="text" class="form-control" name="account_number" id="account_number" placeholder="Account Number" value="<?= set_value('account_number', $amuco_suppliers_bank->account_number); ?>">
                                    </div>
                                 </div>
                                                 
                                 <div class="form-group ">
                                    <label for="switf" class="col-sm-2 control-label">Switf </label>
                                    <div class="col-sm-8">
                                       <input readonly type="text" class="form-control" name="switf" id="switf" placeholder="Switf" value="<?= set_value('switf', $amuco_suppliers_bank->switf); ?>">
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-md-6">
                            
                              <div class="box-footer no-padding">
                                 <div style="text-align:center">
                                       <h4 class="">Intermediary Bank</h4>
                                 </div>
                                 <div class="form-group ">
                                    <label for="intermediary_bank" class="col-sm-2 control-label"> Bank </label>
                                    <div class="col-sm-8">
                                       <input readonly type="text" class="form-control" name="intermediary_bank" id="intermediary_bank" placeholder="Intermediary Bank" value="<?= set_value('intermediary_bank', $amuco_suppliers_bank->intermediary_bank); ?>">
                                    </div>
                                 </div>
                                                         
                                 <div class="form-group ">
                                    <label for="account_intermediary" class="col-sm-2 control-label">Account  </label>
                                    <div class="col-sm-8">
                                       <input readonly type="text" class="form-control" name="account_intermediary" id="account_intermediary" placeholder="Account Intermediary" value="<?= set_value('account_intermediary', $amuco_suppliers_bank->account_intermediary); ?>">  
                                    </div>
                                 </div>
                                                         
                                 <div class="form-group ">
                                    <label for="swift_intermediary" class="col-sm-2 control-label">Swift  </label>
                                    <div class="col-sm-8">
                                       <input readonly type="text" class="form-control" name="swift_intermediary" id="swift_intermediary" placeholder="Swift Intermediary" value="<?= set_value('swift_intermediary', $amuco_suppliers_bank->swift_intermediary); ?>">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>                    
                     <br>
                     <br>

                  </div> 
               </div>        
               <div class="view-nav">
                  <?php is_allowed('amuco_suppliers_bank_update', function() use ($amuco_suppliers_bank){?>
                  <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit amuco_suppliers_bank (Ctrl+e)" href="<?= site_url('administrator/amuco_suppliers_bank/edit/'.$amuco_suppliers_bank->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Amuco Suppliers Bank']); ?> </a>
                  <?php }) ?>
                  <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_suppliers_bank/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Suppliers Bank']); ?></a>
               </div>
                    
            </div>
         </div>
      </div>
   </div>
  
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>