
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<!--section class="content-header">
   <h1>
      Amuco Products      <small><?= cclang('detail', ['Amuco Products']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_products'); ?>">Amuco Products</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section-->

<!-- Main content -->
<section class="content">
   <div class="row" >
      <div class="col-md-8">
         <div class="box box-warning">
            <div class="box-body ">
               <div class="col-md-12">
                  <!-- Widget: user widget style 1 -->
                  <div class="box box-widget widget-user">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                     <div class="widget-user-header " style="background: url('<?= BASE_ASSET; ?>admin-lte/dist/img/photo1.png') center center;">
                        <h3 class="widget-user-username text-white"><?= _ent(ucwords($amuco_products->name)); ?></h3>
                        <h5 class="widget-user-desc text-white"><?= 'ID: '._ent($amuco_products->id); ?></h5>
                     </div>
                     
                     <div class="box-footer">         
                        <!-- /.row -->
                     </div>
                  </div> 
                  <div class="col-md-6">
                     <div class="box box-widget widget-user-2">
                        <div class="">
                           <h3 class="">Category Product</h3>
                        </div>
                        <div class="box-footer no-padding">
                           <ul class="nav nav-stacked">
                         
                              <li><a href="#"><i class="fa fa-chevron-right"></i> <?=  _ent($amuco_products->amuco_category_product_name); ?></a></li>
                          
                           </ul>
                        </div>
                        <div class="">
                           <h3 class="">Suppliers</h3>
                        </div>
                        <div class="box-footer no-padding">
                           <ul class="nav nav-stacked">
                         
                              <li><a href="#"><i class="fa fa-chevron-right"></i>     <?= join_multi_select($amuco_products->suppliers_id, 'amuco_suppliers', 'id', 'name'); ?></a></li>
                          
                           </ul>
                        </div>
                     </div>
                  </div>

                  <div class="col-md-6">
                     <div class="box box-widget widget-user-2">
                        <div class="">
                          <h3 class="">Detail Product</h3>
                        </div>
                        <div class="box-footer no-padding">
                           <ul class="nav nav-stacked">
                              <li><a href="#"><i class='fa fa-shield color-orange'></i> Active 
                                 <?php if (!$amuco_products->active) :?>
                                    <span class="pull-right badge bg-red">Inactive</span></a>
                                 <?php else: ?>
                                    <span class="pull-right badge bg-blue">Active</span></a>
                                 <?php endif; ?>
                              </li>
                              <li><a href="#"><i class='fa  fa-safari  color-orange'></i> Custom Number <span class="pull-right "><?= _ent($amuco_products->custom_number); ?></span></a></li>
                              <li><a href="#"><i class='fa fa-history color-orange'></i> Custom Number Brazil <span class="pull-right "><?= _ent($amuco_products->custom_number_brazil); ?></span></a></li>
                              <li><a href="#"><i class='fa fa-calendar-check-o  color-orange'></i> Cas <span class="pull-right "><?= _ent($amuco_products->cas); ?></span></a></li>
                              <li><a href="#"><i class='fa fa-chrome color-orange'></i> Units <span class="pull-right "><?= _ent($amuco_products->amuco_unit_types_name); ?></span></a></li>
                              <li><a href="#"><i class='fa fa-history color-orange'></i> Industry Type <span class="pull-right "><?= join_multi_select($amuco_products->industry_id, 'amuco_industry_type', 'name', 'name'); ?></span></a></li>
                              <li><a href="#"><i class='fa fa-chrome color-orange'></i> Remarks <span class="pull-right "><?= _ent($amuco_products->remarks); ?></span></a></li>
                           </ul>
                        </div>    
                     </div>
                     <div class="nav-tabs-custom padding-left-0 tab-page ">        
                  </div> 
               </div>
               
            </div> 
            <div class="view-nav">
                        <?php is_allowed('amuco_products_update', function() use ($amuco_products){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit amuco_products (Ctrl+e)" href="<?= site_url('administrator/amuco_products/edit/'.$amuco_products->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Amuco Products']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_products/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Products']); ?></a>
                     </div> 
         </div>
      </div>  
   </div>            
</section>

<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>


