
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Amuco Offers Sent Customers      <small><?= cclang('detail', ['Amuco Offers Sent Customers']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_offers_sent_customers'); ?>">Amuco Offers Sent Customers</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Amuco Offers Sent Customers</h3>
                     <h5 class="widget-user-desc">Detail Amuco Offers Sent Customers</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_amuco_offers_sent_customers" id="form_amuco_offers_sent_customers" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Date Created </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->date_created); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->status); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Date Updated </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->date_updated); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Customer Request Id </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->customer_request_id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Request Details Id </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->request_details_id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Request Details Price Id </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->request_details_price_id); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Payments Terms Id </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->amuco_supplier_payment_terms_description); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Quantity </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->quantity); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Unit </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->amuco_unit_types_name); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Freight </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->freight); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Unit Price </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->unit_price); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Incoterm </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->amuco_incoterm_name); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Destination Port </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->amuco_destination_port_name); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Packing </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->amuco_packing_name); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Fcl </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->fcl); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Type Fcl </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->type_fcl); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Option Fcl </label>

                        <div class="col-sm-8">
                           <?= _ent($amuco_offers_sent_customers->option_fcl); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('amuco_offers_sent_customers_update', function() use ($amuco_offers_sent_customers){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit amuco_offers_sent_customers (Ctrl+e)" href="<?= site_url('administrator/amuco_offers_sent_customers/edit/'.$amuco_offers_sent_customers->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Amuco Offers Sent Customers']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_offers_sent_customers/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Offers Sent Customers']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>