
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <br>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_details_customers_request'); ?>">Amuco Details Customers Request</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <!--h3 class="widget-user-username">Amuco Details Customers Request</h3-->
                     <h5 class="widget-user-desc">Amuco Customers Request</h5>
                     <h3 class="widget-user-username"><?= 'ID: '.$amuco_customer_request->id; ?></h3> 
                     <hr>
                 
               </div>
               <div class="row">  
                  <div class="col-md-12" > 
                     <h4 class="col-md-12">Product Information</h4>
                  </div>
               </div>
               <div class="row"> 
                  <div class="col-md-2">  </div>                    
                  <div class="col-md-8" style ="margin-left: -2.6%;" >    
                     <div class="form-group">
                        <label for="product_id" class="col-sm-2 label-right control-label">Product</label>
                        
                        <div class="col-sm-9">
                              <input readonly type="text" class="form-control" name="purchasing" id="purchasing"  value=" <?= _ent($amuco_details_customers_request->amuco_products_name); ?>">
                        </div>
                     </div>
                  </div>
                  <div class="col-md-2">  </div>
               </div> 
               <br>  
               <div class="row">
                  <div class="col-md-2">  </div>
                  <div class="col-md-4" >                                        
                     <div class="form-group ">
                        <label for="quantity" class="col-sm-3 label-right control-label">Quantity </label>
                        <div class="col-sm-8">
                        <input readonly type="text" class="form-control" name="quantity" id="quantity" placeholder="Quantity" value="<?= $amuco_details_customers_request->quantity ?>">
                        </div>
                     </div>
                  </div>
                  <div class="col-md-4" >                                        
                     <div class="form-group ">
                        <label for="unit" class="col-sm-3 control-label label-right">Unit </label>
                        <div class="col-sm-6">
                        <input readonly type="text" class="form-control" name="unit" id="unit"  value=" <?= _ent($amuco_details_customers_request->amuco_unit_types_name); ?>">
                        </div>
                     </div>
                  </div> 
                  <div class="col-md-2">  </div>  
               </div>
               <br>
               <div class="row">
                  <div class="col-md-2">  </div>
                  <div class="col-md-4" >                              
                     <div class="form-group ">
                        <label for="fcl" class="col-sm-3 label-right control-label">Fcl </label>
                        <div class="col-sm-8">
                        <input readonly type="number" class="form-control" name="fcl" id="fcl" placeholder="Fcl" value="<?= _ent($amuco_details_customers_request->fcl); ?>">
                        </div>
                     </div>
                  </div> 
                  <div class="col-md-4 col-sm-4" > 
                     <div class="form-group ">
                        <div class="row">
                              <label for="fcl" class="col-sm-3"> </label>
                              <div class="col-md-3  fcl_option_1">
                                 <label id="fcl_option_1">
                                 <input type="radio" class="flat-red" <?php echo $amuco_details_customers_request->fcl_option == 20 ? 'checked' : '' ?> name="fcl_option" id="fcl_option_1"  value="20" >
                                    20'
                                 </label>
                              </div>
                              <div class="col-md-3  fcl_option_2" >
                                 <label id ="fcl_option_2">
                                 <input type="radio" class="flat-red"  <?php echo $amuco_details_customers_request->fcl_option == 40 ? 'checked' : '' ?> name="fcl_option" id="fcl_option"  value="40" >
                                 40'
                                 </label>
                              </div>
                        </div> 
                     </div>
                  </div> 
               </div>
               <div class="row">
                  <div class="col-md-2">  </div> 
                  <div class="col-md-4"> 
                     <div class="form-group ">
                        <label for="Type" class="col-sm-3 label-right control-label">Type   </label>
                        <div class="col-sm-8">
                        <input readonly type="text" class="form-control" name="option" id="option"  value=" <?= _ent($amuco_details_customers_request->type_fcl); ?>">
                        </div>
                     </div>
                  </div> 
                  <div class="col-md-6">  </div> 
               </div> 
               <div class="row">  
                  <div class="col-md-12" > 
                     <h4 class="col-md-12">Packaging Details</h4>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-2">  </div>
                  <div class="col-md-4" >                                       
                     <div class="form-group ">
                        <label for="weight" class="col-sm-3 label-right control-label">Weight </label>
                        <div class="col-sm-8">
                           <input  readonly type="text" class="form-control" name="weight" id="weight" placeholder="Weight" value="<?=  _ent($amuco_details_customers_request->weight); ?>">
                        </div>
                     </div>
                  </div>
                  
                  <div class="col-md-4" >                                        
                     <div class="form-group ">
                        <label for="unit" class="col-sm-3 control-label label-right control-label">Unit </label>
                        <div class="col-sm-6">
                        <input readonly type="text" class="form-control" name="weight" id="weight" placeholder="Weight" value="<?=  _ent($amuco_details_customers_request->unit_pack); ?>">
                        </div>
                     </div>
                  </div> 
                  <div class="col-md-2">  </div>
               </div>
               <br> 
               <div class="row">
                  <div class="col-md-2">  </div>
                  <div class="col-md-4" >                                  
                     <div class="form-group ">
                        <label for="packing" class="col-sm-3 label-right control-label">Packing </label>
                          
                        <div class="col-sm-8">
                        <input readonly type="text" class="form-control" name="weight" id="weight" placeholder="Weight" value="<?=  _ent($amuco_details_customers_request->amuco_packing_name); ?>">
                        </div>
                     </div>
                  </div>
                  <div class="col-md-4" >                                       
                     <div class="form-group ">
                        <label for="material" class="col-sm-3 control-label label-right">Material </label>
                       
                        <div class="col-sm-6">
                        <input readonly type="text" class="form-control" name="weight" id="weight" placeholder="Weight" value="<?=  _ent($amuco_details_customers_request->amuco_material_name); ?>">
                        </div>
                     </div>
                  </div> 
               </div>
               <br>
               <div class="row">
                  <div class="col-md-2">  </div>
                  <div class="col-md-4" >                       
                     <div class="form-group">
                        <label class="col-sm-3 label-right"> Pallets</label>
                        <div  class="col-sm-6">
                              <input type="checkbox" <?php echo $amuco_details_customers_request->pallets == 1 ? 'checked' : '' ?> name="pallets" id="pallets"  value="0" >
                        </div>
                     </div>  
                  </div>
                  <div class="col-md-6">  </div> 
               </div>
               <br>
               <div class="row">
                  <div class="col-md-2">  </div>
                  <div class="col-md-4" > 
                     <div class="form-group ">
                        <label for="date_created" class="col-sm-3 control-label">ETD </label>
                        <div class="col-sm-8">
                           <div class="input-group date col-sm-12">
                              <input readonly type="text" class="form-control pull-right datepicker" name="etd"  placeholder="Date ETD" id="etd" value="<?= _ent(substr($amuco_details_customers_request->ETD,0,10)); ?>">
                           </div>
                           <small class="info help-block"></small>
                        </div>
                     </div>
                  </div>  
                  <div class="col-md-4" > 
                     <div class="form-group ">
                        <label for="date_created" class="col-sm-3 control-label">ETA </label>
                        <div class="col-sm-6">
                           <div class="input-group date col-sm-12">
                              <input readonly type="text" class="form-control pull-right datepicker" name="eta"  placeholder="Date ETA" id="eta" value="<?= _ent(substr($amuco_details_customers_request->ETA,0,10)); ?>">
                           </div>
                           <small class="info help-block"></small>
                        </div>
                     </div>
                  </div> 
                  <div class="col-md-2">  </div> 
               </div> 
               <br>
               <div class="row"> 
                  <div class="col-md-2">  </div>  
                  <div class="col-md-10" style="margin-left: -5%;">                                  
                     <div class="form-group ">
                        <label for="specific_remarks_2" class="col-sm-2 control-label">Specific Remarks </label>
                        <div class="col-sm-7">
                           <textarea readonly  class="form-control" style="resize:none" id="specific_remarks_2" name="specific_remarks" rows="5"> <?= _ent($amuco_details_customers_request->specific_remarks); ?></textarea>
                           <small class="info help-block"><b>Input Specific Remarks</b> Max Length : 250.</small>
                        </div>
                     </div>
                  </div>
               </div> 
               <div class="row">  
                  <div class="col-md-12" > 
                     <h4 class="col-md-12">Recipients</h4>
                  </div>
               </div>
               <div class="row" style="<?= $amuco_details_customers_request->supplier == null ? 'display:none' : 'display:block' ?>"> 
                  <div class="col-md-1">  </div>
                  <div class="col-md-9" style ="margin-left: -2.5%;">  
                      <div class="form-group ">
                        <label for="supplier" class="col-sm-3 label-right control-label">Supplier </label>
                        
                        <div class="col-sm-8">
                        <input readonly type="text" class="form-control" name="weight" id="weight" value="<?=  _ent($amuco_details_customers_request->amuco_suppliers_name); ?>">
                        </div>
                     </div>
                  </div>
               </div>
               <br>     
               <div class="row" style="<?= $amuco_details_customers_request->supplier == null ? 'display:none' : 'display:block' ?>"> 
                  <div class="col-md-1">  </div>
                  <div class="col-md-9"  style ="margin-left: -2.5%;" >  
                     <div class="form-group ">
                        <label for="contact" class="col-sm-3 label-right control-label">Contact   </label>
                        <div class="col-sm-8  csup">
                        <input readonly type="text" class="form-control" name="weight" id="weight" value="<?=  join_multi_select($amuco_details_customers_request->contacts, 'amuco_contacts', 'id', 'name');  ?>">
                        </div>
                     </div>
                  </div> 
               </div>  
               <br>   
               <div class="row" style="<?= $amuco_details_customers_request->purchasing == null ? 'display:none' : 'display:block' ?>"> 
                  <div class="col-md-1">  </div>
                     <div class="col-md-9" style ="margin-left: -2.5%;">  
                        <div class="form-group ">
                        <label for="supplier" class="col-sm-3 label-right control-label">Purchasing Office </label>
                        <div class="col-sm-8">
                        <input readonly type="text" class="form-control" name="weight" id="weight" value="<?=  _ent($amuco_details_customers_request->purchasing_username); ?>">
                        </div>
                     </div>
                  </div>   
               </div> 
            </div>
            </div-->
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>