
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Amuco Contacts      <small><?= cclang('detail', ['Amuco Contacts']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_contacts'); ?>">Amuco Contacts</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Amuco Contacts</h3>
                     <h5 class="widget-user-desc">Detail Amuco Contacts</h5>
                     <hr>
                  </div>

                  <div class="row">
                     <div class="tab-pane rest-page-test" id="tab_1" style="margin-top:20px;">
                        <div class="col-md-4">
                           <div class="box box-widget widget-user-2">
                              <!-- Add the bg color to the header using any of the bg-* classes -->
                              <div class="">
                                 <h3 class="">Contact Details</h3>
                              </div>
                              <div class="box-footer no-padding">
                                 <ul class="nav nav-stacked">
                                    <li><a href="#"><i class='fa fa-shield color-orange'></i> <?= cclang('status'); ?> 
                                       <?php if ($amuco_contacts->active) :?>
                                          <span class="pull-right badge bg-green">Y</span></a>
                                       <?php else: ?>
                                          <span class="pull-right badge bg-red">N</span></a>
                                       <?php endif; ?>
                                    </li>
                                    <li><a href="#"> Created <span class="pull-right "><?= _ent(substr($amuco_contacts->date_created,0,10)); ?></span></a></li>
                                    <li><a href="#"> Updated <span class="pull-right "><?= _ent(substr($amuco_contacts->date_updated,0,10)); ?></span></a></li>
                                    <li><a href="#"> Contact Type <span class="pull-right "><?= _ent($amuco_contacts->type_contact); ?></span></a></li>
                                    <li><a href="#"> First Name <span class="pull-right "><?= _ent($amuco_contacts->first_name); ?></span></a></li>
                                    <li><a href="#"> Last Name <span class="pull-right "><?= _ent($amuco_contacts->last_name); ?></span></a></li>
                                    <li><a href="mailto:<?= _ent($amuco_contacts->email); ?>"> Email <span  style="color:blue" class="pull-right "><?= _ent($amuco_contacts->email); ?></span></a></li>
                                  
                                    
                                 </ul>
                              </div>
                           </div>
                        </div>
                        <div class="col-md-4">
                           <div class="box box-widget widget-user-2">
                              <!-- Add the bg color to the header using any of the bg-* classes -->
                              <div class="">
                                 <h3 class="">Location Information</h3>
                              </div>
                              <div class="box-footer no-padding">
                                 <ul class="nav nav-stacked">
                                    <li><a href="#"> Country <span class="pull-right "><?= _ent($amuco_contacts->amuco_countries_name); ?></span></a></li>
                                    <li><a href="#"> City <span class="pull-right "><?= _ent($amuco_contacts->city); ?></span></a></li>
                                    <li><a href="#"> Address <span class="pull-right "><?= _ent($amuco_contacts->home_address); ?></span></a></li>
                                    <li><a href="#"> Mobile Phone <span class="pull-right "><?= _ent($amuco_contacts->mobile_phone); ?></span></a></li>
                                    <li><a href="#"> Office Phone <span class="pull-right "><?= _ent($amuco_contacts->office_phone); ?></span></a></li>
                                    <li><a href="#"> Home Phone <span class="pull-right "><?= _ent($amuco_contacts->home_phone); ?></span></a></li>
                                    <li><a href="#" > Fax <span class="pull-right"><?= _ent($amuco_contacts->fax); ?></span></a></li>
                                    
                                 </ul>
                              </div>
                           </div>
                        </div>
                        <div class="col-md-4">
                           <div class="box box-widget widget-user-2">
                              <!-- Add the bg color to the header using any of the bg-* classes -->
                              <div class="">
                                 <h3 class="">other Information</h3>
                              </div>
                              <div class="box-footer no-padding">
                                 <ul class="nav nav-stacked">
                                 <?php if(trim($amuco_contacts->amuco_customers_name) != NULL): ?>
                                    <li><a href="#"> Customer <span class="pull-right "><?= _ent($amuco_contacts->amuco_customers_name); ?></span></a></li>
                                     <?php endif?>
                                     <?php if(trim($amuco_contacts->amuco_suppliers_name) != NULL): ?>
                                     <li><a href="#"> Supplier <span class="pull-right "><?= _ent($amuco_contacts->amuco_suppliers_name); ?></span></a></li>
                                    <?php endif?>
                                  
                                    <li><a href="#"> Position <span class="pull-right "><?= _ent($amuco_contacts->position); ?></span></a></li>
                                    <li><a href="#"> Department <span class="pull-right "><?= _ent($amuco_contacts->department); ?></span></a></li>
                                    <li><a href="#"> Birthday <span class="pull-right "><?= _ent(substr($amuco_contacts->birthday,0,10)); ?></span></a></li>
                                    <li><a href="#"> Other <span class="pull-right "><?= _ent($amuco_contacts->additional_information); ?></span></a></li>
                                    
                                 </ul>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
                   <div class="form-horizontal form-step row" name="form_amuco_contacts" id="form_amuco_contacts" >
                     <div class="col-sm-4">
            
                                        
                    
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('amuco_contacts_update', function() use ($amuco_contacts){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit amuco_contacts (Ctrl+e)" href="<?= site_url('administrator/amuco_contacts/edit/'.$amuco_contacts->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Amuco Contacts']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_contacts/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Contacts']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){

   });
</script>