
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.

function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<?php if($current_page == 'View'):?>
<section class="content-header">
   <h1>
    <br>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_details_request_office'); ?>">Amuco Details Request Office</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<?php endif; ?>
<!-- Main content -->
<section class="content">
   <div class="row" >
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <h3 class="widget-user-username">Amuco Details Request </h3>
                     <h5 class="widget-user-desc">Detail Amuco Details Request </h5>
                     <h4 class="widget-user-desc"><?php echo  'ID:'. $amuco_details_request_office->customer_request_id; ?></h4>
                    
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_amuco_details_request_office" id="form_amuco_details_request_office" >
                     <div class="row"> 
                           <div class="col-md-4" >                          
                              <label for="content" class="col-sm-4 label-right">Product</label>
                              <div class="col-sm-8"><p><?= $amuco_details_request_office->amuco_products_name; ?> </p> </div>
                           </div>
                           <div class="col-md-4" >                          
                              <label for="content" class="col-md-6 col-sm-4 label-right">Quantity</label>
                              <div class="col-sm-6"><p ><?= $amuco_details_request_office->quantity == "" ? 'N/A' : $amuco_details_request_office->quantity  ?> </p> </div>
                           </div> 
                           <div class="col-md-4" >                          
                              <label for="content" class="col-sm-4 label-right">Unit</label>
                              <div class="col-sm-8"><p><?= $amuco_details_request_office->amuco_unit_types_name == "" ? 'N/A' : $amuco_details_request_office->amuco_unit_types_name ?> </p> </div>
                           </div>   
                     </div>
                     <div class="row"> 
                           <div class="col-md-4" >                          
                              <label for="content" class="col-sm-4 label-right">FCL</label>
                              <div class="col-sm-8"><p ><?= $amuco_details_request_office->fcl == "" ? 0 : $amuco_details_request_office->fcl ?> </p> </div>
                           </div>
                           <div class="col-md-4" >                          
                              <label for="content" class="col-md-6 col-sm-4 label-right">FCL Option</label>
                              <div class="col-sm-6"> <p ><?= $amuco_details_request_office->fcl_option == "" ? 'N/A' : $amuco_details_request_office->fcl_option ?> </p> </div>
                           </div>
                           <div class="col-md-4" >                          
                              <label for="content" class="col-sm-4 label-right">FCL Type</label>
                              <div class="col-sm-8"><p > <?= $amuco_details_request_office->type_fcl == "" ? 'N/A' : $amuco_details_request_office->type_fcl   ?> </p> </div> 
                           </div>  
                     </div>
                     <div class="row"> 
                           <div class="col-md-4" >                          
                              <label for="content" class="col-sm-4 label-right">Weight/Vol</label>
                              <div class="col-sm-8"><p ><?= $amuco_details_request_office->weight ==   "" ? 0 : $amuco_details_request_office->weight ?> </p> </div>
                           </div>
                           <div class="col-md-4" >                          
                              <label for="content" class="col-md-6 col-sm-4 label-right">Unit</label>
                              <div class="col-sm-6"> <p ><?= $amuco_details_request_office->amuco_unit_types_name == "" ? 'N/A' : $amuco_details_request_office->amuco_unit_types_name ?> </p> </div>
                           </div>
                           <div class="col-md-4" >                          
                              <label for="content" class="col-sm-4 label-right">Packing</label>
                              <div class="col-sm-8"><p > <?= $amuco_details_request_office->shape  == "" ? 'N/A' : $amuco_details_request_office->amuco_shape_name ?> </p> </div> 
                           </div>  
                     </div>
                     <div class="row"> 
                           <div class="col-md-4" >                          
                              <label for="content" class="col-sm-4 label-right">Material</label>
                              <div class="col-sm-8"><p ><?= $amuco_details_request_office->material == "" ? 'N/A' : $amuco_details_request_office->amuco_material_name ?> </p> </div>
                           </div>
                           <div class="col-md-4" >                          
                              <label for="content" class="col-md-6 col-sm-4 label-right">Pallets</label>
                              <div class="col-sm-6"> <p ><?= $amuco_details_request_office->pallets == 0 ? 'No' : 'Yes' ?> </p> </div>
                           </div>
                           
                     </div>
                     <br>
                     <div class="row"> 
                           <div class="col-md-12" >                          
                              <h4> Price Details</h4>
                           </div>
                     </div>
                    <br>
                     <div class="row"> 
                           <div class="col-md-3" >                          
                              <label for="content" class="col-sm-4 label-right">Price Fob</label>
                              <div class="col-sm-8"><p> <?= _ent(number_format($amuco_details_request_office->price_fob,2)); ?> </p> </div>
                           </div>
                           <div class="col-md-3" >                          
                              <label for="content" class="col-md-6 col-sm-4 label-right">Total Freight</label>
                              <div class="col-sm-6"><p > <?= _ent(number_format($amuco_details_request_office->total_freight,2)); ?> </p> </div>
                           </div> 
                           <div class="col-md-3" >                          
                              <label for="content" class="col-sm-4 label-right">Total Price</label>
                              <div class="col-sm-8"><p> <?= _ent(number_format($amuco_details_request_office->total_price,2)); ?> </p> </div>
                           </div>
                           <div class="col-md-3" >                          
                              <label for="content" class="col-sm-4 label-right">Incoterm</label>
                              <div class="col-sm-6">
                              <?php foreach (db_get_all_data('amuco_incoterm') as $row):
                                 if($amuco_details_request_office->incoterm_price ==  $row->id): 
                              ?> 
                                      <p> <?= _ent($row->name); ?> </p> 
                                 <?php endif; endforeach; ?>  
                             
                              </div>
                           </div>     
                     </div> 
                     <br>  
                     <div class="row"> 
                           <div class="col-md-3" >                          
                              <label for="content" class="col-sm-4 label-right">Supplier</label>
                              <div class="col-sm-8">
                              <?php foreach (db_get_all_data('amuco_suppliers') as $row):
                                 if($amuco_details_request_office->supplier_direct ==  $row->id || $amuco_details_request_office->supplier == $row->id ): 
                              ?> 
                              <p>  <?= _ent($row->name); ?> </p> 
                              
                              <?php endif; endforeach; ?> 
                              </div> 
                           </div>
                           <div class="col-md-3" >                          
                              <label for="content" class="col-md-6 col-sm-4 label-right">Brand</label>
                              <div class="col-sm-6"><p > <?= _ent($amuco_details_request_office->brand); ?> </p> </div>
                           </div> 
                           <div class="col-md-3" >                          
                              <label for="content" class="col-sm-4 label-right">Payment Terms</label>
                              <div class="col-sm-8"><p> <?= _ent($amuco_details_request_office->payment_terms); ?> </p> </div>
                           </div>
                           <div class="col-md-3" >                          
                              <label for="content" class="col-sm-6 label-right">Sup.Incoterm</label>
                              <div class="col-sm-6">
                              <?php foreach (db_get_all_data('amuco_incoterm') as $row):
                                 if($amuco_details_request_office->supplier_incoterm ==  $row->id): 
                              ?> 
                                      <p> <?= _ent($row->name); ?> </p> 
                                 <?php endif; endforeach; ?>  
                             
                              </div>
                           </div>     
                     </div> 
                     <br>
                     <div class="row"> 
                           <div class="col-md-3" >                          
                              <label for="content" class="col-sm-4 label-right">Shipping Port</label>
                              <div class="col-sm-8"><p>  <?= _ent($amuco_details_request_office->amuco_destination_port_name); ?> </p> </div>
                           </div>
                           <div class="col-md-3" >                          
                              <label for="content" class="col-md-6 col-sm-4 label-right">Delivery Date</label>
                              <div class="col-sm-6"><p > <?= _ent(substr($amuco_details_request_office->ETD,0,10)); ?> </p> </div>
                           </div> 
                           <div class="col-md-3" >                          
                              <label for="content" class="col-sm-4 label-right">Valid Until</label>
                              <div class="col-sm-8"><p> <?= _ent(substr($amuco_details_request_office->valid_until,0,10)); ?> </p> </div>
                           </div>
                           <div class="col-md-3" >                          
                              <label for="content" class="col-sm-4 label-right">Analysis Standard</label>
                              <div class="col-sm-8"><p> <?= _ent($amuco_details_request_office->analysis_standard); ?> </p> </div>
                           </div>     
                     </div>                  
                     <br>
                     <div class="row"> 
                        <div class="col-md-12" >                          
                           <label  for="content" class="col-md-1 col-sm-4 label-right">Remarks</label>
                           <div class="col-md-10 col-sm-8"><p><?= $amuco_details_request_office->comments ?> </p></div>  
                        </div> 
                     </div>              
                    
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('amuco_details_request_office_update', function() use ($amuco_details_request_office){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit amuco_details_request_office (Ctrl+e)" href="<?= site_url('administrator/amuco_details_request_office/edit/'.$amuco_details_request_office->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Amuco Details Request Office']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_details_request_office/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Details Request Office']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
<script>
$(document).ready(function(){
   
   });
</script>