
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Amuco Customers      <small><?= cclang('detail', ['Amuco Customers']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/amuco_customers'); ?>">Amuco Customers</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
  <div class="row" >
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <div class="col-md-12">
                  <div class="box box-widget widget-user">
                     <div class="widget-user-header " style="background: url('<?= BASE_ASSET; ?>admin-lte/dist/img/photo1.png') center center;">
                        <h3 class="widget-user-username text-white"  style="margin-left:1%"><?= _ent(ucwords($amuco_customers->name)); ?></h3>
                        <h5 class="widget-user-desc text-white"  style="margin-left:1.2%"><?= ' ID: '._ent($amuco_customers->id); ?></h5>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_URL.'uploads/user/'.(!empty($amuco_customers->avatar) ? $amuco_customers->avatar:'default.png'); ?>" alt="User Avatar" style="height: 80px; width: 80px" >
                     </div>
                     <div class="box-footer">         
                     <!-- /.row -->
                     </div>
                  </div>     
               </div>
               <div class="nav-tabs-custom padding-left-0 tab-page ">
                  <ul class="nav nav-tabs">
                  <li class="active"><a class=" active tab_animation" href="#tab_1" data-toggle="tab"><i class="fa fa-gear text-green"></i> Information</a></li>
                  <li><a class=" active btn-form-preview tab_animation" href="#tab_2" data-toggle="tab"><i class="fa fa-credit-card"></i> Credit Insurance</a></li>
                  <li><a class=" active btn-form-preview tab_animation" href="#tab_3" data-toggle="tab"><i class="fa fa-user"></i> Contacts</a></li>
                  <li><a class=" active btn-form-preview tab_animation" href="#tab_4" data-toggle="tab"><i class="fa fa-product-hunt"></i> Samples</a></li>
                  <li><a class=" active btn-form-preview tab_animation" href="#tab_5" data-toggle="tab"><i class="fa fa-sticky-note"></i> Visits</a></li>
                  </ul>
                  <div class="tab-content">
                     <div class="tab-pane rest-page-test active" id="tab_1" style="margin-top:20px;">
                        <div class="col-md-4">
                           <div class="box box-widget widget-user-2">
                              <!-- Add the bg color to the header using any of the bg-* classes -->
                              <div class="">
                                 <h3 class="">Details Customer</h3>
                              </div>
                              <div class="box-footer no-padding">
                                 <ul class="nav nav-stacked">
                                    <li><a href="#"><i class='fa fa-shield color-orange'></i> <?= cclang('status'); ?> 
                                       <?php if ($amuco_customers->active) :?>
                                          <span class="pull-right badge bg-green">Active</span></a>
                                       <?php else: ?>
                                          <span class="pull-right badge bg-red">Inactive</span></a>
                                       <?php endif; ?>
                                    </li>
                                    <li><a href="#"> Is Branche <span class="pull-right "><?= _ent($amuco_customers->is_branche == 1 ? 'yes' : 'no'); ?></span></a></li>
                                    <?php if($amuco_customers->is_branche == 1): ?><li><a href="#"> Head Office <span class="pull-right "><?= isset($head_office->name) ? $head_office->name : '' ; ?></span></a></li><?php endif;?>
                                    <li><a href="#"> NIT <span class="pull-right "><?= _ent($amuco_customers->nit); ?></span></a></li>
                                    <li><a href="#"> Code <span class="pull-right "><?= _ent($amuco_customers->code); ?></span></a></li>
                                    <li><a href="#"> EMAIL <span class="pull-right "><?= _ent($amuco_customers->email); ?></span></a></li>
                                    <li><a href="#"> URL <span class="pull-right "><?= _ent($amuco_customers->url); ?></span></a></li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                        <div class="col-md-4">
                           <div class="box box-widget widget-user-2">
                              <div class="">
                                 <h3 class="">Location Information</h3>
                              </div>
                              <div class="box-footer no-padding">
                                 <ul class="nav nav-stacked">

                                    <li><a href="#"> Country <span class="pull-right "> <?= _ent($amuco_customers->amuco_countries_name); ?></span></a></li>
                                    <li><a href="#"> City <span class="pull-right "><?= _ent($amuco_customers->city); ?></span></a></li>
                                    <li><a href="#"> State/Province <span class="pull-right "><?= _ent($amuco_customers->state); ?></span></a></li>
                                    <li><a href="#"> Address <span class="pull-right "><?= _ent($amuco_customers->address); ?></span></a></li>
                                    <li><a href="#"> Postal Code <span class="pull-right "><?= _ent($amuco_customers->postal_code); ?></span></a></li>
                                    <li><a href="#"> Mobile Phone <span class="pull-right "><?= _ent($amuco_customers->mobile_phone); ?></span></a></li>
                                    <li><a href="#"> Office Phone <span class="pull-right "><?= _ent($amuco_customers->office_phone); ?></span></a></li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                        <div class="col-md-4">
                           <div class="box box-widget widget-user-2">
                              <div class="">
                                 <h3 class="">Other Information</h3>
                              </div>
                              <div class="box-footer no-padding">
                                 <ul class="nav nav-stacked">
                              
                                    <li><a href="#"> Type Industries <span class="pull-right ">  <?= join_multi_select($amuco_customers->industry_type, 'amuco_industry_type', 'id', 'name'); ?></span></a></li>
                                    <li><a href="#"> Sales Agent <span class="pull-right "><?= join_multi_select($amuco_customers->sales_agent, 'aauth_users', 'id', 'username'); ?></span></a></li>
                                    <li><a href="#"> Created <span class="pull-right "><?= _ent($amuco_customers->date_created); ?></span></a></li>
                                    <li><a href="#"> Updated <span class="pull-right "><?= _ent( $amuco_customers->date_updated); ?></span></a></li>
                                    
                                 </ul>
                              </div>
                           </div>
                        </div>
                     </div> 

                     <div class="tab-pane" id="tab_2">
                        <div class="col-md-8">
                           <div class="box box-widget widget-user-2">
                              <div class="">
                                 <h3 class="">Credit Insurance</h3>
                              </div>
                              <div class="box-footer no-padding">
                                 <?php if(isset($credit_insurance) && is_array($credit_insurance) && count($credit_insurance) > 0):?>
                                 <ul class="nav nav-stacked">
                                    <li><a href="#"> Raiting  <span class="pull-right "><?= isset($credit_insurance[0]->raiting) ? _ent($credit_insurance[0]->raiting):'0.00';?></span></a></li>
                                    <li><a href="#"> Credit ever denied?  <span class="pull-right "><input  type="checkbox" name="is_denied"  class="switch-button" <?= isset($credit_insurance[0]->credit_ever_denied) && $credit_insurance[0]->credit_ever_denied ? 'checked':''; ?> disabled></span></a></li>
                                    <li><a href="#"> Insured credit <span class="pull-right "><?= isset($credit_insurance[0]->insured_credit) ? _ent($credit_insurance[0]->insured_credit):'0.00';?></span></a></li>
                                    <li><a href="#"> Available credit <span class="pull-right "><?= isset($credit_insurance[0]->available_credit) ? _ent($credit_insurance[0]->available_credit):'0.00'; ?></span></a></li>
                                    <li><a href="#"> Own risk <span class="pull-right "><?= isset($credit_insurance[0]->own_risk) ? _ent($credit_insurance[0]->own_risk):'0.00'; ?></span></a></li>
                                    <li><a href="#"> Highest ever insured <span class="pull-right "><?= isset($credit_insurance[0]->highest_ever_insured) ? _ent($credit_insurance[0]->highest_ever_insured):'0.00'; ?></span></a></li>
                                    <li><a href="#"> Request increase status<span class="pull-right "><?= isset($credit_insurance[0]->request_increase_status) ? _ent($credit_insurance[0]->request_increase_status):'0.00'; ?></span></a></li>
                                    <li><a href="#"> Mount Increase  <span class="pull-right "><?= isset($credit_insurance[0]->mount_request) ? _ent($credit_insurance[0]->mount_request):'0.00'; ?></span></a></li>
                                    <li><a href="#"> Last increased requested  <span class="pull-right "><?= isset($credit_insurance[0]->last_increased_requested) ? _ent($credit_insurance[0]->last_increased_requested):'0.00'; ?></span></a></li>
                                    <li><a href="#"> Date last increased requested <span class="pull-right "><?= isset($credit_insurance[0]->date_last_increased_requested) ? _ent($credit_insurance[0]->date_last_increased_requested):''; ?></span></a></li>
                                 </ul>
                                 <?php else: ?>
                                 <label> Customer does not have a credit</label>
                                    <div>
                                       <button type="button" class="btn btn-flat btn-success btn_add_new " data-toggle="modal" data-target="#modal-credit">Add Credit Insurance</button>
                                    </div>
                                 <?php endif;?>
                              </div>    
                           </div>    
                        </div>  
                     </div>

                     <div class="tab-pane" id="tab_3">
                        <div class="col-md-12">
                           <div class="">
                              <h3 class="">Contacts</h3>
                           </div>
                           <div>
                              <button type="button" class="btn btn-flat btn-success btn_add_new" data-toggle="modal" data-target="#modal-contact"> Add New Contact</button>
                           </div>
                           <?php if(isset($customer_contact) && is_array($customer_contact) && count($customer_contact) > 0):?>
                        
                           <?php foreach($customer_contact as $contact):?>
                           
                              <div class="col-12 col-sm-4 col-md-3 d-flex align-items-stretch">
                                 <div class="card bg-light">
                                    <div class="card-header text-muted border-bottom-0">
                                 
                                    </div>
                                    <div class="card-body pt-0">
                                       <div class="row">
                                          <div class="col-7">
                                             <h2 class="lead"><b><?php echo $contact->name;?></b></h2>
                                             <p class="text-muted text-sm"><b>About: </b> <?php echo $contact->departament.'/'.$contact->position;?><br>
                                                email: <?php echo $contact->email;?> </p>
                                             <ul class="ml-4 mb-0 fa-ul text-muted">
                                             <li class="small"><span class="fa-li"><i class="fa fa-lg fa-building"></i></span> Country/city: <?php echo $contact->country.' /'.$contact->city?></li>
                                             <li class="small"><span class="fa-li"><i class="fa fa-lg fa-building"></i></span> Address: <?php echo $contact->home_address ;?></li>
                                             <li class="small"><span class="fa-li"><i class="fa fa-lg fa-phone"></i></span> Phone #: <?php echo $contact->office_phone != null ? $contact->mobile_phone : 'N/A' ; ?></li>
                                             <li class="small"><span class="fa-li"><i class="fa fa-lg fa-phone"></i></span> Mobile Phone #: <?php echo $contact->mobile_phone != null ? $contact->mobile_phone : 'N/A' ; ?></li>
                                             </ul>
                                          </div>
                                          <div class="col-5" style="margin-left:15%">
                                             <img src="../../dist/img/user1-128x128.jpg" alt="" class="img-circle img-fluid">
                                             <a href="" ><?php  echo anchor('administrator/amuco_contacts/view/'.$contact->id.'?popup=show',' <i class="fa fa-user"></i> View', ['class' => 'popup-view']); ?>
                                          </div>
                                       </div>
                                    </div>
                                    <div class="card-footer">
                                       <div class="text-center">
                                         
                                             
                                          </a>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                          
                           <?php endforeach; else: ?>
                           <label> Customer does not have contacts</label>
                          
                           <?php   endif;?>
                        </div> 
                     </div> 
                  
                     <div class="tab-pane" id="tab_4">
                        <div class="col-md-12">
                           <div class="">
                                 <h3 class="">Samples</h3>
                           </div>
                           
                           <div>
                              <button  class="btn btn-flat btn-success btn_add_new" type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-sample"> Add New Sample</button>
                           </div>
                           <?php if(isset($customer_samples) && is_array($customer_samples) && count($customer_samples) > 0):?>
                        
                           <?php foreach($customer_samples as $samples):?>
                           <div class="col-md-6">
                              <div class="box box-widget widget-user-2">
                                 <!-- Add the bg color to the header using any of the bg-* classes -->
                                 <div class="">
                                    <h3 class="">Sample ID: <?php echo $samples->id?></h3>
                                 </div>
                                 <div class="box-footer no-padding">
                                    <ul class="nav nav-stacked">
                                       <li>  <div class="col-md-6">Product: </div> <div class="col-md-6" style="text-align: right;"><?php echo anchor('administrator/amuco_products/view/'.$samples->product_id.'?popup=show', $samples->amuco_products_name, ['class' => 'popup-view']); ?></div> <hr></li>
                                       <li> <div class="col-md-6">Supplier: </div> <div class="col-md-6" style="text-align: right;"><?php echo anchor('administrator/amuco_suppliers/view/'.$samples->supplier_id.'?popup=show', $samples->amuco_suppliers_name, ['class' => 'popup-view']); ?> </div><hr></li>
                                       <li><a href="#"> Status: <span class="pull-right "><?= _ent($samples->status); ?></span></a></li>
                                       <li><a href="#"> Lot: <span class="pull-right "><?= _ent($samples->lot); ?></span></a></li>
                                       <li><a href="#"> Note <span class="pull-right "><?= _ent($samples->note); ?></span></a></li>
                                       <li><a href="#"> Remark <span class="pull-right "><?= _ent($samples->remarks); ?></span></a></li>
                                       <li><a href="#"> Received <span class="pull-right "><?= _ent($samples->date_received); ?></span></a></li>
                                       <li><a href="#"> Sent <span class="pull-right "><?= _ent($samples->date_sent); ?></span></a></li>
                                       <li><a href="#"> Requested <span class="pull-right "><?= _ent($samples->date_requested); ?></span></a></li>
                                    </ul>
                                 </div>
                              </div>
                           </div> 
                           <?php endforeach; else: ?>
                              <label> Customer does not have Samples</label>
                           <?php   endif;?>
                        </div> 
                     </div> 
                     <div class="tab-pane" id="tab_5">
                        <div class="col-md-12">
                           <div class="box box-warning">
                              <div class="box-body ">
                                 <!-- Widget: user widget style 1 -->
                                 <div class="box box-widget widget-user-2">
                                    <!-- Add the bg color to the header using any of the bg-* classes -->
                                    <div class="widget-user-header ">
                                    <h3 ><?= cclang('amuco visits') ?></h3>
                                       <div >
                                          <?php is_allowed('amuco_visits_add', function(){?>
                                          <a class="btn btn-flat btn-success btn_add_new"  data-toggle="modal" data-target="#modal-visit" title="<?= cclang('add_new_button', [cclang('amuco_visits')]); ?>  (Ctrl+a)"  ?><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button'); ?> Visit</a>
                                          <?php }) ?>
                                         
                                       </div>
                     
                                       <!-- /.widget-user-image -->
                                       
                                      
                                    </div>

                                    <form name="form_amuco_visits" id="form_amuco_visits" action="<?= base_url('administrator/amuco_visits/index'); ?>">
                                    

                                       <div class="table-responsive"> 
                                          <table class="table table-bordered table-striped dataTable">
                                             <thead>
                                                <tr class="">
                                                   
                                                   <th data-field="id"data-sort="1" data-primary-key="1"> <?= cclang('id') ?></th>
                                                   <th data-field="user_id"data-sort="1" data-primary-key="0"> <?= cclang('user_id') ?></th>
                                                   <!--th data-field="customer_id"data-sort="1" data-primary-key="0"> <?= cclang('customer_id') ?></th-->
                                                   <th data-field="date_visit"data-sort="1" data-primary-key="0"> <?= cclang('date_visit') ?></th>
                                                   <th data-field="contact_name"data-sort="1" data-primary-key="0"> <?= cclang('contact_name') ?></th>
                                                   <th data-field="subject"data-sort="1" data-primary-key="0"> <?= cclang('Subject') ?></th>
                                                   <th>Action</th>                        
                                                </tr>
                                             </thead>
                                             <tbody id="tbody_amuco_visits">
                                                <?php foreach($customer_visits as $amuco_visits): ?>
                                                <tr>
                                                                     
                                                                        
                                                   <td><?= _ent($amuco_visits->id); ?></td> 
                                                   <td><?php if  ($amuco_visits->user_id) {

                                                       echo anchor('administrator/aauth_users/view/'.$amuco_visits->user_id.'?popup=show', $amuco_visits->aauth_users_username, ['class' => 'popup-view']); }?> </td>
                                             
                                                   <td><?= _ent($amuco_visits->date_visit); ?></td> 
                                                   <td><?php if  ($amuco_visits->contact_name) {

                                                   echo anchor('administrator/amuco_contacts/view/'.$amuco_visits->contact_name.'?popup=show', $amuco_visits->amuco_contacts_first_name, ['class' => 'popup-view']); }?> </td>
                                                   <td><?= _ent($amuco_visits->subject); ?></td> 
                                                   <td width="200">
                                             
                                                                              <?php is_allowed('amuco_visits_view', function() use ($amuco_visits){?>
                                                     
                                                   <?= anchor('administrator/amuco_visits/view/'.$amuco_visits->id.'?popup=show','<i class="fa fa-newspaper-o">See</i> ', ['class' => 'popup-view']); ?>
                                                   <?php }) ?>
                                                   <?php is_allowed('amuco_visits_update', function() use ($amuco_visits){?>
                                                   <a href="<?= site_url('administrator/amuco_visits/edit/' . $amuco_visits->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                                                   <?php }) ?>
                                                   <?php is_allowed('amuco_visits_delete', function() use ($amuco_visits){?>
                                                   <a href="javascript:void(0);" data-href="<?= site_url('administrator/amuco_visits/delete/' . $amuco_visits->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                                                   <?php }) ?>

                                                   </td>                        
                                                </tr>
                                                <?php endforeach; ?>
                                                <?php if (count($customer_visits) == 0) :?>
                                                   <tr>
                                                      <td colspan="100">
                                                      Amuco Visits data is not available
                                                      </td>
                                                   </tr>
                                                <?php endif; ?>

                                             </tbody>
                                          </table>
                                       </div>
                                    </div>
                                    <hr>
                                    <!-- /.widget-user -->
                                    <div class="row">
                                       </form>                 
                                        <div class="col-md-4">
                                          <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                                             <?= $pagination; ?>
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>  
                        </div>
                     </div> 
                  </div> 
            
               <div class="row-fluid col-md-12" style="top:15px" >
                        <?php is_allowed('amuco_customers_update', function() use ($amuco_customers){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit amuco_customers (Ctrl+e)" href="<?= site_url('administrator/amuco_customers/edit/'.$amuco_customers->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Amuco Customers']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/amuco_customers/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Amuco Customers']); ?></a>      
               </div>
            </div>
         </div>
      </div>
   </div>
</section>



<section>
   <div class="modal fade" id="modal-visit">
      <div class="modal-dialog modal-lg">
         <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
               <div class="row" >
                  <div class="box box-warning">
                     <div class="box-body ">
                        <!-- Widget: user widget style 1 -->
                        <div class="box box-widget widget-user-2">
                           <!-- Add the bg color to the header using any of the bg-* classes -->
                           <div class="widget-user-header ">
                              <div class="widget-user-image">
                                 <img class="img-circle" src="<?= BASE_ASSET; ?>/img/add2.png" alt="User Avatar">
                              </div>
                              <!-- /.widget-user-image -->
                              <h3 class="widget-user-username">Amuco Visits</h3>
                              <h5 class="widget-user-desc"><?= cclang('new', ['Amuco Visits']); ?></h5>
                             
                           </div>
                        </div>
                     <div>   
                  <?= form_open('', [
                            'name'    => 'form_amuco_visits_new', 
                            'class'   => 'form-horizontal form-step', 
                            'id'      => 'form_amuco_visits_new', 
                            'enctype' => 'multipart/form-data', 
                            'method'  => 'POST'
                            ]); ?>
                  <div class="form-group ">
                        <label for="type_client" class="col-sm-2 control-label">Type Client 
                        <i class="required">*</i>
                        </label>
                        <div class="col-sm-8">
                           <select  class="form-control chosen chosen-select" name="type_client" id="type_client" data-placeholder="Select Type Client" >
                              <option value=""></option>
                              <option value="Customer" selected>Customer</option>
                              <!--option value="Supplier">Supplier</option-->
                              </select>
                           <small class="info help-block">
                           </small>
                        </div>
                  </div>
                         
                  <div class="form-group ">
                     <label for="user_id" class="col-sm-2 control-label">User  
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <select  class="form-control chosen chosen-select-deselect" name="user_id" id="user_id" data-placeholder="Select User Id" >
                           <option value=""></option>
                           <?php foreach (db_get_all_data('aauth_users') as $row): ?>
                           <option value="<?= $row->id ?>"><?= $row->username; ?></option>
                           <?php endforeach; ?>  
                        </select>
                        <small class="info help-block">
                        <b>Input User Id</b> Max Length : 10.</small>
                     </div>
                  </div>

                                                 
                  <div class="form-group " id= "customer_select">
                     <label for="customer_id" class="col-sm-2 control-label">Customer  
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <select  class="form-control chosen chosen-select-deselect" name="customer_id" id="customer_id" data-placeholder="Select Customer Id" >
                           <option value=""></option>
                           <?php foreach (db_get_all_data('amuco_customers') as $row): ?>
                           <option <?=  ($row->id==$amuco_customers->id) ? 'selected' : ''; ?> value="<?= $row->id ?>"><?= $row->name; ?></option> 
                           <?php endforeach; ?>  
                        </select>
                        <small class="info help-block">
                        <b>Input Customer Id</b> Max Length : 10.</small>
                     </div>
                  </div>

                                                 
                  <div class="form-group ">
                     <label for="date_visit" class="col-sm-2 control-label">Date Visit 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-6">
                        <div class="input-group date col-sm-8">
                           <input type="text" class="form-control pull-right datetimepicker" name="date_visit"  id="date_visit">
                         </div>
                        <small class="info help-block">
                        </small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="contact_name" class="col-sm-2 control-label">Contact Name 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <select  class="form-control chosen chosen-select-deselect" name="contact_name" id="contact_name" data-placeholder="Select Contact Name" >
                           <option value=""></option>
                           <?php foreach (db_get_all_data('amuco_contacts') as $row): ?>
                           <option value="<?= $row->id ?>"><?= $row->first_name; ?></option>
                           <?php endforeach; ?>  
                        </select>
                        <small class="info help-block">
                        <b>Input Contact Name</b> Max Length : 50.</small>
                     </div>
                  </div>

                  <div class="form-group ">
                     <label for="subject" class="col-sm-2 control-label">Subject 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" value="<?= set_value('subject'); ?>">
                        <small class="info help-block">
                        <b>Input Subject</b> Max Length : 250.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="notes" class="col-sm-2 control-label">Notes 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <textarea id="notes" name="notes" rows="5" cols="80"><?= set_value('Notes'); ?></textarea>
                        <small class="info help-block">
                        </small>
                     </div>
                  </div>
                                                
                  <div class="message"></div>
                  <div class="modal-footer justify-content-between">
                     <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                     <button class="btn btn-flat btn-primary btn_save btn_action" id="btn_save_visit"  name="btn_save_visit" data-stype='stay' title="<?= cclang('save_button'); ?> (Ctrl+s)">
                        <i class="fa fa-save" ></i> <?= cclang('save_button'); ?>
                     </button>  
                  </div>
                 
                  <?= form_close(); ?>
               </div>
            </div>
         </div>
          <!-- /.modal-content -->
      </div>
        <!-- /.modal-dialog -->
   </div>
</section>

<section>
      <div class="modal fade" id="modal-credit">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="row" >
              
                  <div class="box box-warning">
                     <div class="box-body ">
                        <!-- Widget: user widget style 1 -->
                        <div class="box box-widget widget-user-2">
                           <!-- Add the bg color to the header using any of the bg-* classes -->
                           <div class="widget-user-header ">
                              <div class="widget-user-image">
                                 <img class="img-circle" src="<?= BASE_ASSET; ?>/img/add2.png" alt="User Avatar">
                              </div>
                              <!-- /.widget-user-image -->
                              <h3 class="widget-user-username">Amuco Credit Insurance</h3>
                              <h5 class="widget-user-desc"><?= cclang('new', ['Amuco Credit Insurance']); ?></h5>
                             
                           </div>
                        </div>
                     <div>   
                              <?= form_open('', [
                                 'name'    => 'form_amuco_credit_insurance', 
                                 'class'   => 'form-horizontal form-step', 
                                 'id'      => 'form_amuco_credit_insurance', 
                                 'enctype' => 'multipart/form-data', 
                                 'method'  => 'POST'
                                 ]); 
                              ?>
                                 
                           
                           <div class="form-group ">
                            <label for="customer_id" class="col-sm-2 control-label">Customer 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <select  class="form-control chosen chosen-select-deselect" name="customer_id" id="customer_id" data-placeholder="Select Customer Id" >
                                    <option value=""></option>
                                    <?php foreach (db_get_all_data('amuco_customers') as $row): ?>
                           <option <?=  ($row->id==$amuco_customers->id) ? 'selected' : ''; ?> value="<?= $row->id ?>"><?= $row->name; ?></option> 
                           <?php endforeach; ?> 
                                </select>
                                <small class="info help-block">
                                <b>Input Customer Id</b> Max Length : 10.</small>
                            </div>
                        </div>
                                                         
                           <div class="form-group ">
                              <label for="raiting" class="col-sm-2 control-label">Raiting 
                                 <i class="required">*</i>
                              </label>
                              <div class="col-sm-8">
                                 <input type="text" class="form-control" name="raiting" id="raiting" placeholder="Raiting" value="<?= set_value('raiting'); ?>">
                                    <small class="info help-block">
                                    </small>
                              </div>
                           </div>
                                                         
                           <div class="form-group ">
                              <label for="credit_ever_denied" class="col-sm-2 control-label">Credit Ever Denied 
                              <i class="required">*</i>
                              </label>
                              <div class="col-sm-6">
                                 <div class="col-md-2 padding-left-0">
                                       <label>
                                          <input type="radio" class="flat-red" name="credit_ever_denied" id="credit_ever_denied"  value="1">
                                          <?= cclang('yes'); ?>
                                       </label>
                                 </div>
                                 <div class="col-md-14">
                                       <label>
                                          <input type="radio" class="flat-red" name="credit_ever_denied" id="credit_ever_denied"  value="0">
                                          <?= cclang('no'); ?>
                                       </label>
                                 </div>
                                 <small class="info help-block">
                                 </small>
                              </div>
                           </div>
                                                         
                           <div class="form-group ">
                              <label for="available_credit" class="col-sm-2 control-label">Available Credit 
                                 <i class="required">*</i>
                              </label>
                              <div class="col-sm-8">
                                 <input type="text" class="form-control" name="available_credit" id="available_credit" placeholder="Available Credit" value="<?= set_value('available_credit'); ?>">
                                    <small class="info help-block">
                                       </small>
                              </div>
                           </div>
                                                         
                           <div class="form-group ">
                              <label for="insured_credit" class="col-sm-2 control-label">Insured Credit 
                                 <i class="required">*</i>
                              </label>
                              <div class="col-sm-8">
                                 <input type="text" class="form-control" name="insured_credit" id="insured_credit" placeholder="Insured Credit" value="<?= set_value('insured_credit'); ?>">
                                 <small class="info help-block">
                                       </small>
                              </div>
                           </div>
                                                         
                           <div class="form-group ">
                              <label for="own_risk" class="col-sm-2 control-label">Own Risk 
                              <i class="required">*</i>
                              </label>
                              <div class="col-sm-8">
                                 <input type="text" class="form-control" name="own_risk" id="own_risk" placeholder="Own Risk" value="<?= set_value('own_risk'); ?>">
                                 <small class="info help-block">
                                 </small>
                              </div>
                           </div>
                                                         
                           <div class="form-group ">
                              <label for="highest_ever_insured" class="col-sm-2 control-label">Highest Ever Insured 
                              <i class="required">*</i>
                              </label>
                              <div class="col-sm-8">
                                 <input type="text" class="form-control" name="highest_ever_insured" id="highest_ever_insured" placeholder="Highest Ever Insured" value="<?= set_value('highest_ever_insured'); ?>">
                                 <small class="info help-block">
                                 </small>
                              </div>
                           </div>
                                                         
                           <div class="form-group ">
                              <label for="request_increase_status" class="col-sm-2 control-label">Request Increase Status 
                              <i class="required">*</i>
                              </label>
                              <div class="col-sm-8">
                                 <input type="text" class="form-control" name="request_increase_status" id="request_increase_status" placeholder="Request Increase Status" value="<?= set_value('request_increase_status'); ?>">
                                 <small class="info help-block">
                                 <b>Input Request Increase Status</b> Max Length : 20.</small>
                              </div>
                           </div>
                                                         
                           <div class="form-group ">
                              <label for="mount_increase" class="col-sm-2 control-label">Mount Increase 
                              <i class="required">*</i>
                              </label>
                              <div class="col-sm-8">
                                 <input type="text" class="form-control" name="mount_increase" id="mount_increase" placeholder="Mount Increase" value="<?= set_value('mount_increase'); ?>">
                                 <small class="info help-block">
                                 </small>
                              </div>
                           </div>
                                                         
                           <div class="form-group ">
                              <label for="last_increased_requested" class="col-sm-2 control-label">Last Increased Requested 
                              <i class="required">*</i>
                              </label>
                              <div class="col-sm-8">
                                 <input type="text" class="form-control" name="last_increased_requested" id="last_increased_requested" placeholder="Last Increased Requested" value="<?= set_value('last_increased_requested'); ?>">
                                 <small class="info help-block">
                                 </small>
                              </div>
                           </div>
                                                         
                           <div class="form-group ">
                              <label for="date_last_increased_requested" class="col-sm-2 control-label">Date Last Increased Requested 
                              <i class="required">*</i>
                              </label>
                              <div class="col-sm-6">
                              <div class="input-group date col-sm-8">
                                 <input type="text" class="form-control pull-right datetimepicker" name="date_last_increased_requested"  id="date_last_increased_requested">
                              </div>
                              <small class="info help-block">
                              </small>
                              </div>
                           </div>
                                                         
                           <div class="message"></div>
                             
                            <div class="modal-footer justify-content-between">
                              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                              <button class="btn btn-flat btn-primary btn_save btn_action" id="btn_save_credit" data-stype='stay' title="<?= cclang('save_button'); ?> (Ctrl+s)">
                                 <i class="fa fa-save" ></i> <?= cclang('save_button'); ?>
                              </button>  
                           </div>     
                           <?= form_close(); ?>
                           </div>
                        </div>
                        <!--/box body -->
                     </div>
                     <!--/box -->
                  </div>
               </div>
            
           
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
</section>


<section>
   <div class="modal fade" id="modal-contact">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
               <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                        <div class="widget-user-image">
                           <img class="img-circle" src="<?= BASE_ASSET; ?>/img/add2.png" alt="User Avatar">
                        </div>
                        <!-- /.widget-user-image -->
                        <h3 class="widget-user-username">Amuco Contacts</h3>
                        <h5 class="widget-user-desc"><?= cclang('new', ['Amuco Contacts']); ?></h5>
                        <hr>
                  </div>
                  <?= form_open('', [
                        'name'    => 'form_amuco_contacts', 
                        'class'   => 'form-horizontal form-step', 
                        'id'      => 'form_amuco_contacts', 
                        'enctype' => 'multipart/form-data', 
                        'method'  => 'POST'
                        ]); ?>
                     
                                          <div class="form-group ">
                        <label for="type_contact" class="col-sm-2 control-label">Type Contact 
                        <i class="required">*</i>
                        </label>
                        <div class="col-sm-8">
                           <select  class="form-control chosen chosen-select" name="type_contact" id="type_contact" data-placeholder="Select Type Contact" >
                              <option value=""></option>
                              <!--option value="supplier">Supplier</option-->
                              <option value="Customer">Customer</option>
                              </select>
                           <small class="info help-block">
                           </small>
                        </div>
                  </div>
                                                 
                  <div class="form-group ">
                            <label for="name" class="col-sm-2 control-label">Name 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="name" id="name" placeholder="Name" value="<?= set_value('name'); ?>">
                                <small class="info help-block">
                                </small>
                            </div>
                        </div>
                                                 
                  
                                                 
                  <div class="form-group ">
                     <label for="position" class="col-sm-2 control-label">Position 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="position" id="position" placeholder="Position" value="<?= set_value('position'); ?>">
                        <small class="info help-block">
                        <b>Input Position</b> Max Length : 100.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="departament" class="col-sm-2 control-label">Departament 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="departament" id="departament" placeholder="Departament" value="<?= set_value('departament'); ?>">
                        <small class="info help-block">
                        <b>Input Departament</b> Max Length : 100.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="mobile_phone" class="col-sm-2 control-label">Mobile Phone 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="mobile_phone" id="mobile_phone" placeholder="Mobile Phone" value="<?= set_value('mobile_phone'); ?>">
                        <small class="info help-block">
                        <b>Input Mobile Phone</b> Max Length : 30.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="office_phone" class="col-sm-2 control-label">Office Phone 
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="office_phone" id="office_phone" placeholder="Office Phone" value="<?= set_value('office_phone'); ?>">
                        <small class="info help-block">
                        <b>Input Office Phone</b> Max Length : 30.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="personal_phone" class="col-sm-2 control-label">Personal Phone 
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="personal_phone" id="personal_phone" placeholder="Personal Phone" value="<?= set_value('personal_phone'); ?>">
                        <small class="info help-block">
                        <b>Input Personal Phone</b> Max Length : 30.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="fax" class="col-sm-2 control-label">Fax 
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="fax" id="fax" placeholder="Fax" value="<?= set_value('fax'); ?>">
                        <small class="info help-block">
                        <b>Input Fax</b> Max Length : 30.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="email" class="col-sm-2 control-label">Email 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="email" id="email" placeholder="Email" value="<?= set_value('email'); ?>">
                        <small class="info help-block">
                        <b>Input Email</b> Max Length : 100.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                        <label for="skype" class="col-sm-2 control-label">Skype 
                        </label>
                        <div class="col-sm-8">
                           <input type="text" class="form-control" name="skype" id="skype" placeholder="Skype" value="<?= set_value('skype'); ?>">
                           <small class="info help-block">
                           <b>Input Skype</b> Max Length : 100.</small>
                        </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="line_products" class="col-sm-2 control-label">Line Products 
                     </label>
                     <div class="col-sm-8">
                        <select  class="form-control chosen chosen-select" name="line_products[]" id="line_products" data-placeholder="Select Line Products" multiple >
                           <option value=""></option>
                           <?php foreach (db_get_all_data('amuco_category_product') as $row): ?>
                           <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                           <?php endforeach; ?>  
                        </select>
                        <small class="info help-block">
                        <b>Input Line Products</b> Max Length : 100.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="customer_id" class="col-sm-2 control-label">Customer 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <select  class="form-control chosen chosen-select-deselect" name="customer_id" id="customer_id" data-placeholder="Select Customer Id" >
                           <option value=""></option>
                           <?php foreach (db_get_all_data('amuco_customers') as $row): ?>
                           <?php if($row->id == $amuco_customers->id): ?>
                              <option selected value="<?= $row->id ?>"><?= $row->name; ?></option>
                           <?php endif; ?>   
                           <?php endforeach; ?>  
                        </select>
                        <small class="info help-block">
                        <b>Input Customer </b> Max Length : 10.</small>
                     </div>
                  </div>

                                                 
                  <div class="form-group ">
                     <label for="picture" class="col-sm-2 control-label">Picture </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="picture" id="picture" placeholder="Picture" value="<?= set_value('picture'); ?>">
                        <small class="info help-block">
                        <b>Input Picture</b> Max Length : 250.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="home_address" class="col-sm-2 control-label">Home Address 
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="home_address" id="home_address" placeholder="Home Address" value="<?= set_value('home_address'); ?>">
                        <small class="info help-block">
                        <b>Input Home Address</b> Max Length : 250.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="country" class="col-sm-2 control-label">Country 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <select  class="form-control chosen chosen-select-deselect" name="country" id="country" data-placeholder="Select Country" >
                           <option value=""></option>
                           <?php foreach (db_get_all_data('amuco_countries') as $row): ?>
                           <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                           <?php endforeach; ?>  
                        </select>
                        <small class="info help-block">
                        <b>Input Country</b> Max Length : 10.</small>
                     </div>
                  </div>

                                                 
                  <div class="form-group ">
                     <label for="city" class="col-sm-2 control-label">City 
                     <i class="required">*</i>
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="city" id="city" placeholder="City" value="<?= set_value('city'); ?>">
                        <small class="info help-block">
                        <b>Input City</b> Max Length : 100.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="home_phone" class="col-sm-2 control-label">Home Phone 
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="home_phone" id="home_phone" placeholder="Home Phone" value="<?= set_value('home_phone'); ?>">
                        <small class="info help-block">
                        <b>Input Home Phone</b> Max Length : 30.</small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="birthday" class="col-sm-2 control-label">Birthday </label>
                     <div class="col-sm-6">
                        <div class="input-group date col-sm-8">
                           <input type="text" class="form-control pull-right datetimepicker" name="birthday"  id="birthday">
                        </div>
                        <small class="info help-block"></small>
                     </div>
                  </div>
                                                 
                  <div class="form-group ">
                     <label for="additional_information" class="col-sm-2 control-label">Additional Information 
                     </label>
                     <div class="col-sm-8">
                        <input type="text" class="form-control" name="additional_information" id="additional_information" placeholder="Additional Information" value="<?= set_value('additional_information'); ?>">
                        <small class="info help-block">
                        <b>Input Additional Information</b> Max Length : 250.</small>
                     </div>
                  </div>
                                                
                  <div class="message"></div>
                  <div class="modal-footer justify-content-between">
                     <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                     <button class="btn btn-flat btn-primary btn_save btn_action" id="btn_save_contact" data-stype='stay' title="<?= cclang('save_button'); ?> (Ctrl+s)">
                        <i class="fa fa-save" ></i> <?= cclang('save_button'); ?>
                     </button>
                  </div>
                  
                  <?= form_close(); ?>
               </div>
            </div>
           
         
          <!-- /.modal-content -->
         </div>
        <!-- /.modal-dialog -->
      </div>
   </div>   
</section>

<section>
      <div class="modal fade" id="modal-sample">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="row" >
              
                  <div class="box box-warning">
                     <div class="box-body ">
                        <!-- Widget: user widget style 1 -->
                        <div class="box box-widget widget-user-2">
                           <!-- Add the bg color to the header using any of the bg-* classes -->
                           <div class="widget-user-header ">
                              <div class="widget-user-image">
                                 <img class="img-circle" src="<?= BASE_ASSET; ?>/img/add2.png" alt="User Avatar">
                              </div>
                              <!-- /.widget-user-image -->
                              <h3 class="widget-user-username">Amuco Samples</h3>
                              <h5 class="widget-user-desc"><?= cclang('new', ['Amuco Samples']); ?></h5>
                             
                           </div>
                        </div>
                     <div>   
                     <?= form_open('', [
                            'name'    => 'form_amuco_samples', 
                            'class'   => 'form-horizontal form-step', 
                            'id'      => 'form_amuco_samples', 
                            'enctype' => 'multipart/form-data', 
                            'method'  => 'POST'
                            ]); ?>
                         
                                                <div class="form-group ">
                            <label for="product_id" class="col-sm-2 control-label">Product  
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <select  class="form-control chosen chosen-select-deselect" name="product_id" id="product_id" data-placeholder="Select Product Id" >
                                    <option value=""></option>
                                    <?php foreach (db_get_all_data('amuco_products') as $row): ?>
                                    <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                    <?php endforeach; ?>  
                                </select>
                                <small class="info help-block">
                                <b>Input Product Id</b> Max Length : 10.</small>
                            </div>
                        </div>

                                                 
                                                <div class="form-group ">
                            <label for="supplier_id" class="col-sm-2 control-label">Supplier  
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <select  class="form-control chosen chosen-select-deselect" name="supplier_id" id="supplier_id" data-placeholder="Select Supplier Id" >
                                    <option value=""></option>
                                    <?php foreach (db_get_all_data('amuco_suppliers') as $row): ?>
                                    <option value="<?= $row->id ?>"><?= $row->name; ?></option>
                                    <?php endforeach; ?>  
                                </select>
                                <small class="info help-block">
                                <b>Input Supplier Id</b> Max Length : 10.</small>
                            </div>
                        </div>

                                                 
                                                <div class="form-group ">
                            <label for="note" class="col-sm-2 control-label">Note 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="note" id="note" placeholder="Note" value="<?= set_value('note'); ?>">
                                <small class="info help-block">
                                <b>Input Note</b> Max Length : 250.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="lot" class="col-sm-2 control-label">Lot 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="lot" id="lot" placeholder="Lot" value="<?= set_value('lot'); ?>">
                                <small class="info help-block">
                                <b>Input Lot</b> Max Length : 250.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="status" class="col-sm-2 control-label">Status 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="status" id="status" placeholder="Status" value="<?= set_value('status'); ?>">
                                <small class="info help-block">
                                <b>Input Status</b> Max Length : 50.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="remarks" class="col-sm-2 control-label">Remarks 
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="remarks" id="remarks" placeholder="Remarks" value="<?= set_value('remarks'); ?>">
                                <small class="info help-block">
                                <b>Input Remarks</b> Max Length : 250.</small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="date_received" class="col-sm-2 control-label">Date Received 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-6">
                            <div class="input-group date col-sm-8">
                              <input type="text" class="form-control pull-right datetimepicker" name="date_received"  id="date_received">
                            </div>
                            <small class="info help-block">
                            </small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="date_sent" class="col-sm-2 control-label">Date Sent 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-6">
                            <div class="input-group date col-sm-8">
                              <input type="text" class="form-control pull-right datetimepicker" name="date_sent"  id="date_sent">
                            </div>
                            <small class="info help-block">
                            </small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="date_requested" class="col-sm-2 control-label">Date Requested 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-6">
                            <div class="input-group date col-sm-8">
                              <input type="text" class="form-control pull-right datetimepicker" name="date_requested"  id="date_requested">
                            </div>
                            <small class="info help-block">
                            </small>
                            </div>
                        </div>
                                                 
                                                <div class="form-group ">
                            <label for="customer_id" class="col-sm-2 control-label">Customer  
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <select  class="form-control chosen chosen-select-deselect" name="customer_id" id="customer_id" data-placeholder="Select Customer Id" >
                                    <option value=""></option>
                                    <?php foreach (db_get_all_data('amuco_customers') as $row): ?>
                           <option <?=  ($row->id==$amuco_customers->id) ? 'selected' : ''; ?> value="<?= $row->id ?>"><?= $row->name; ?></option> 
                           <?php endforeach; ?>  
                                </select>
                                <small class="info help-block">
                                <b>Input Customer Id</b> Max Length : 10.</small>
                            </div>
                        </div>

                                                
                        
                                                <div class="message"></div>
                                                <div class="modal-footer justify-content-between">
                     <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                     <button class="btn btn-flat btn-primary btn_save btn_action" id="btn_save_sample" data-stype='stay' title="<?= cclang('save_button'); ?> (Ctrl+s)">
                        <i class="fa fa-save" ></i> <?= cclang('save_button'); ?>
                     </button>
                  </div>
                                                <div class="row-fluid col-md-7 container-button-bottom">
                           
                            <span class="loading loading-hide">
                            <img src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg"> 
                            <i><?= cclang('loading_saving_data'); ?></i>
                            </span>
                        </div>
                                                 <?= form_close(); ?>
                           </div>
                        </div>
                        <!--/box body -->
                     </div>
                     <!--/box -->
                  </div>
               </div>
            
           
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
</section>


<script src="<?= BASE_ASSET; ?>ckeditor/ckeditor.js"></script>
<!-- /.content -->
<script>
$(document).ready(function(){
   CKEDITOR.replace('notes'); 
      var notes = CKEDITOR.instances.notes;

      $('#btn_save_sample').click(function(){
        $('.message').fadeOut();
            
        var form_amuco_samples = $('#form_amuco_samples');
        var data_post = form_amuco_samples.serializeArray();
        var save_type = $(this).attr('data-stype');

        data_post.push({name: 'save_type', value: save_type});
    
        $('.loading').show();
    
        $.ajax({
          url: BASE_URL + '/administrator/amuco_samples/add_save',
          type: 'POST',
          dataType: 'json',
          data: data_post,
        })
        .done(function(res) {
          $('form').find('.form-group').removeClass('has-error');
          $('.steps li').removeClass('error');
          $('form').find('.error-input').remove();
          if(res.success) {
           /* $('#modal-sample').modal('hide');
            location.reload();*/
            if (save_type == 'back') {
              window.location.href = res.redirect;
              return;
            }
    
            $('.message').printMessage({message : res.message});
            $('.message').fadeIn();
            resetForm();
            $('.chosen option').prop('selected', false).trigger('chosen:updated');
                
          } else {
            if (res.errors) {
                
                $.each(res.errors, function(index, val) {
                    $('form #'+index).parents('.form-group').addClass('has-error');
                    $('form #'+index).parents('.form-group').find('small').prepend(`
                      <div class="error-input">`+val+`</div>
                      `);
                });
                $('.steps li').removeClass('error');
                $('.content section').each(function(index, el) {
                    if ($(this).find('.has-error').length) {
                        $('.steps li:eq('+index+')').addClass('error').find('a').trigger('click');
                    }
                });
            }
            $('.message').printMessage({message : res.message, type : 'warning'});
          }
    
        })
        .fail(function() {
          $('.message').printMessage({message : 'Error save data', type : 'warning'});
        })
        .always(function() {
          $('.loading').hide();
          $('html, body').animate({ scrollTop: $(document).height() }, 2000);
        });
    
        return false;
      }); /*end btn save*/

   $('#btn_save_visit').click(function(){
        $('.message').fadeOut();
        $('#notes').val(notes.getData());
   
        var form_amuco_visits_new = $('#form_amuco_visits_new');
        var data_post = form_amuco_visits_new.serializeArray();
        var save_type = $(this).attr('data-stype');

        data_post.push({name: 'save_type', value: save_type});
        console.log(data_post);
        $('.loading').show();
       
        $.ajax({
          url: BASE_URL + '/administrator/amuco_visits/add_save',
          type: 'POST',
          dataType: 'json',
          data: data_post,
        })
        .done(function(res) {
         
          $('form').find('.form-group').removeClass('has-error');
          $('.steps li').removeClass('error');
          $('form').find('.error-input').remove();
          if(res.success) {
            $('#modal-visit').modal('hide');
            location.reload();
            if (save_type == 'back') {
              window.location.href = res.redirect;
              return;
            }
    
            $('.message').printMessage({message : res.message});
            $('.message').fadeIn();
            resetForm();
            $('.chosen option').prop('selected', false).trigger('chosen:updated');
            notes.setData('');
                
          } else {
            if (res.errors) {
                
                $.each(res.errors, function(index, val) {
                    $('form #'+index).parents('.form-group').addClass('has-error');
                    $('form #'+index).parents('.form-group').find('small').prepend(`
                      <div class="error-input">`+val+`</div>
                      `);
                });
                $('.steps li').removeClass('error');
                $('.content section').each(function(index, el) {
                    if ($(this).find('.has-error').length) {
                        $('.steps li:eq('+index+')').addClass('error').find('a').trigger('click');
                    }
                });
            }
            $('.message').printMessage({message : res.message, type : 'warning'});
          }
    
        })
        .fail(function() {
          $('.message').printMessage({message : 'Error save data', type : 'warning'});
        })
        .always(function() {
          $('.loading').hide();
          $('html, body').animate({ scrollTop: $(document).height() }, 2000);
        });
    
        return false;
      }); /*end btn save*/

   $('#btn_save_contact').click(function(){
        $('.message').fadeOut();
            
        var form_amuco_contacts = $('#form_amuco_contacts');
        var data_post = form_amuco_contacts.serializeArray();
        var save_type = $(this).attr('data-stype');

        data_post.push({name: 'save_type', value: save_type});
    
        $('.loading').show();
    
        $.ajax({
          url: BASE_URL + '/administrator/amuco_contacts/add_save',
          type: 'POST',
          dataType: 'json',
          data: data_post,
        })
        .done(function(res) {
          $('form').find('.form-group').removeClass('has-error');
          $('.steps li').removeClass('error');
          $('form').find('.error-input').remove();
          if(res.success) {
            $('#modal-contact').modal('hide');
            location.reload();
            if (save_type == 'back') {
              window.location.href = res.redirect;
              return;
            }
    
            $('.message').printMessage({message : res.message});
            $('.message').fadeIn();
            resetForm();
            $('.chosen option').prop('selected', false).trigger('chosen:updated');
                
          } else {
            if (res.errors) {
                
                $.each(res.errors, function(index, val) {
                    $('form #'+index).parents('.form-group').addClass('has-error');
                    $('form #'+index).parents('.form-group').find('small').prepend(`
                      <div class="error-input">`+val+`</div>
                      `);
                });
                $('.steps li').removeClass('error');
                $('.content section').each(function(index, el) {
                    if ($(this).find('.has-error').length) {
                        $('.steps li:eq('+index+')').addClass('error').find('a').trigger('click');
                    }
                });
            }
            $('.message').printMessage({message : res.message, type : 'warning'});
          }
    
        })
        .fail(function() {
          $('.message').printMessage({message : 'Error save data', type : 'warning'});
        })
        .always(function() {
          $('.loading').hide();
          $('html, body').animate({ scrollTop: $(document).height() }, 2000);
        });
    
        return false;
      }); /*end btn save*/

      $('#btn_save_credit').click(function(){
        $('.message').fadeOut();
            
        var form_amuco_credit_insurance = $('#form_amuco_credit_insurance');
        var data_post = form_amuco_credit_insurance.serializeArray();
        var save_type = $(this).attr('data-stype');
        //console.log(data_post);
        data_post.push({name: 'save_type', value: save_type});
    
        $('.loading').show();
    
        $.ajax({
          url: BASE_URL + '/administrator/amuco_credit_insurance/add_save',
          type: 'POST',
          dataType: 'json',
          data: data_post,
        })
        .done(function(res) {
          $('form').find('.form-group').removeClass('has-error');
          $('.steps li').removeClass('error');
          $('form').find('.error-input').remove();
          if(res.success) {
            $('#modal-credit').modal('hide');
            location.reload();
            if (save_type == 'back') {
              window.location.href = res.redirect;
              return;
            }
    
            $('.message').printMessage({message : res.message});
            $('.message').fadeIn();
            resetForm();
            $('.chosen option').prop('selected', false).trigger('chosen:updated');
                
          } else {
            if (res.errors) {
                
                $.each(res.errors, function(index, val) {
                    $('form #'+index).parents('.form-group').addClass('has-error');
                    $('form #'+index).parents('.form-group').find('small').prepend(`
                      <div class="error-input">`+val+`</div>
                      `);
                });
                $('.steps li').removeClass('error');
                $('.content section').each(function(index, el) {
                    if ($(this).find('.has-error').length) {
                        $('.steps li:eq('+index+')').addClass('error').find('a').trigger('click');
                    }
                });
            }
            $('.message').printMessage({message : res.message, type : 'warning'});
          }
    
        })
        .fail(function() {
          $('.message').printMessage({message : 'Error save data', type : 'warning'});
        })
        .always(function() {
          $('.loading').hide();
          $('html, body').animate({ scrollTop: $(document).height() }, 2000);
        });
    
        return false;
      }); /*end btn save*/
});
</script>

