
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Amuco_customers/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('amuco_customers') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('amuco_customers') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('amuco_customers_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('amuco_customers')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/amuco_customers/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('amuco_customers')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('amuco_customers_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('amuco_customers') ?> " href="<?= site_url('administrator/amuco_customers/export?q='.$this->input->get('q').'&f='.$this->input->get('d')); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('amuco_customers_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('amuco_customers') ?> " href="<?= site_url('administrator/amuco_customers/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('amuco_customers') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('amuco_customers')]); ?>  <i class="label bg-yellow"><?= $amuco_customers_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_amuco_customers" id="form_amuco_customers" action="<?= base_url('administrator/amuco_customers/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th data-field="id"data-sort="1" data-primary-key="1" style="display:none"> <?= cclang('id') ?></th>
                           <th data-field="code"data-sort="1" data-primary-key="0"> <?= cclang('code') ?></th>
                           <th data-field="name"data-sort="1" data-primary-key="0"> <?= cclang('name') ?></th>
                          
                           <th style="display:none"  data-field="nit"data-sort="1" data-primary-key="0"> <?= cclang('nit') ?></th>
                           <th  style="display:none" data-field="email"data-sort="1" data-primary-key="0"> <?= cclang('email') ?></th>
                           <th data-field="country"data-sort="1" data-primary-key="0"> <?= cclang('country') ?></th>
                           <th  style="display:none" data-field="is_branche"data-sort="1" data-primary-key="0"> <?= cclang('is_branche') ?></th>
                           <th data-field="head_office"data-sort="1" data-primary-key="0"> <?= cclang('head_office') ?></th>
                           <th data-field="industry_type"data-sort="1" data-primary-key="0"> <?= cclang('industry_type') ?></th>
                           <th data-field="sales_agent"data-sort="1" data-primary-key="0"> <?= cclang('sales_agent') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_amuco_customers">
                     <?php foreach($amuco_customerss as $amuco_customers): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $amuco_customers->id; ?>">
                           </td>
                                                       
                           <td  style="display:none"><?= _ent($amuco_customers->id); ?></td> 
                           <td><?= _ent($amuco_customers->code); ?></td> 
                           <td><?= _ent($amuco_customers->name); ?></td> 
                           
                           <td  style="display:none"><?= _ent($amuco_customers->nit); ?></td> 
                           <td  style="display:none"><?= _ent($amuco_customers->email); ?></td> 
                           <td><?php 

                              echo $amuco_customers->amuco_countries_name ;?> </td>
                             
                           <td  style="display:none"><?= $amuco_customers->is_branche == 0 ? 'No': 'Yes'  ?></td> 
                           <?php if ($amuco_customers->head_office == 0) :?>
                                   <td><?= _ent($amuco_customers->head_office); ?></td> 
                           <?php else: ?>
                           <?php foreach($amuco_customerss as $head_office): ?>
                               <?php if ($amuco_customers->head_office == $head_office->id) :?>
                                   <td><?= anchor('administrator/amuco_customers/view/'.$head_office->id.'?popup=show', $head_office->name, ['class' => 'popup-view']); ?> </td> 
                              <?php endif; ?>
                           <?php endforeach; ?>   
                           <?php endif; ?>   
                           <td><?= join_multi_select($amuco_customers->industry_type, 'amuco_industry_type', 'id', 'name'); ?></td> 
                           <td><?= join_multi_select($amuco_customers->sales_agent, 'aauth_users', 'id', 'username'); ?></td> 
                           <!--td><?php if  ($amuco_customers->sales_agent) {

                              echo anchor('administrator/aauth_users/view/'.$amuco_customers->sales_agent.'?popup=show', $amuco_customers->aauth_users_username, ['class' => 'popup-view']); }?> </td-->
                             
                           <td width="200">
                            
                                                              <?php is_allowed('amuco_customers_view', function() use ($amuco_customers){?>
                               
                              <a href="<?= site_url('administrator/amuco_customers/view/' . $amuco_customers->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view'); ?>
                              <?php }) ?>
                              <?php is_allowed('amuco_customers_update', function() use ($amuco_customers){?>
                              <a href="<?= site_url('administrator/amuco_customers/edit/' . $amuco_customers->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('amuco_customers_delete', function() use ($amuco_customers){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/amuco_customers/delete/' . $amuco_customers->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($amuco_customers_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Amuco Customers data is not available
                           </td>
                         </tr>
                      <?php endif; ?>

                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'id' ? 'selected' :''; ?> value="id">Id</option>
                           <option <?= $this->input->get('f') == 'name' ? 'selected' :''; ?> value="name">Name</option>
                           <option <?= $this->input->get('f') == 'code' ? 'selected' :''; ?> value="code">Code</option>
                           <option <?= $this->input->get('f') == 'nit' ? 'selected' :''; ?> value="nit">Nit</option>
                           <option <?= $this->input->get('f') == 'email' ? 'selected' :''; ?> value="email">Email</option>
                           <option <?= $this->input->get('f') == 'country' ? 'selected' :''; ?> value="country">Country</option>
                           <option <?= $this->input->get('f') == 'is_branche' ? 'selected' :''; ?> value="is_branche">Is Branche</option>
                           <option <?= $this->input->get('f') == 'head_office' ? 'selected' :''; ?> value="head_office">Head Office</option>
                           <option <?= $this->input->get('f') == 'industry_type' ? 'selected' :''; ?> value="industry_type">Industry Type</option>
                           <option <?= $this->input->get('f') == 'sales_agent' ? 'selected' :''; ?> value="sales_agent">Sales Agent</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/amuco_customers');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
      
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_amuco_customers').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/amuco_customers/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });
    initSortable('amuco_customers', $('table.dataTable'));
    $('#filter').keyup(function(){
      setTimeout(
     function() 
     {
        $( "#form_amuco_customers" ).submit();
     }, 1000);
     
     //initSortable('amuco_visits', $('table.dataTable'));
   });
  }); /*end doc ready*/
</script>